### ISSUE TITLE
Test the descriptor module

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/bdk#101]
- [x] Test the `ToWalletDescriptor` trait
    - [x] From `&str` with and without checksum appended
    - [x] From `&str` with keys from the right/wrong network
    - [x] From the output of the `descriptor!()` macro

Moved to #193 
~- [ ] Test the `ExtractPolicy` trait
    - [ ] Simple descriptors like `wpkh()`, `sh(multi())`
    - [ ] Both with extended and single keys
    - [ ] More complicated descriptor that contains timelocks too in a `thresh()`
        - [ ] Mixed timelocks should fail
        - [ ] Multiple timelocks of the same type should be correctly merged together~ 

- [x] Test the `get_checksum()` function. It should return the same value as Bitcoin Core's `getdescriptorinfo`

- [x] Test the `descriptor!()` macro
    - [x] Ideally at least one of each "type" of operator should be tested (i.e. one modifier, one "leaf_opcode", one "leaf_opcode_value", etc)
    - [x] Test mixing up key types that implement `ToDescriptorKey` in `multi()` or `thresh()`
    - [x] Test that the `valid_networks` returned is correctly computed based on the keys present in the descriptor
    - [x] Test that the `key_maps` are correctly merged together
    - [x] Test that the `ScriptContext` is correctly validated (i.e. passing a type that only impl `ToDescriptorKey<Segwitv0>` to a `pkh()` descriptor should throw a compilation error

- [x] Test the existing descriptor templates, make sure they are expanded to the right descriptors

**Comment by notmandatory** [comment]
Moved `ExtractPolicy` testing to #193 since it needed for `0.2.0` release.
