### ISSUE TITLE
`log` dependency forces version for non-MSRV builds

### ISSUE THREAD

**Issue by tcharding** [bitcoindevkit/bdk#1013]
Currently the `log` dependency is set to a fixed version v0.4.18, this was done to keep the MSRV build passing however there is a better approach available. The problem with this approach is that it forces the `log` version even for non-MSRV builds and for folk with a more recent version of `log` in their dependency tree it forces them to have both versions in their dependency tree.

Instead we can pin the `log` dependency in CI when doing the MSRV build, this proves that the code builds for the stated MSRV while not forcing users of `bdk` to use the same version.

See https://github.com/bitcoindevkit/rust-esplora-client/pull/51 for an attempt at doing so in `rust-esplora-client` (be warned that I've not fully worked out the github actions syntax yet, in `rust-bitcoin` we use shell scripts to do the pinning).

**Comment by notmandatory** [comment]
Thanks for the suggestion, I like the approach. If we do it for `log` I think we should do it for all the dependencies we pin for MSRV purposes.

**Comment by tcharding** [comment]
Cool, that issue I link to above has passed CI so the method works.

**Comment by danielabrozzoni** [comment]
#1046 fixed this :)
