### ISSUE TITLE
Wallet::sent_and_received doesn't exist

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#1015]
This kind of utility function should be exposed to users of `Wallet`. others like `balance` have been and this is technically a regression since `TransactionDetails` used to offer this information.

There may be opportunities to further delegate this to the txout index elsewhere in wallet since I see that "sent" and "received" being calculated internally in places.

The same is true for `calculate_fee` of `TxGraph` -- it should be there on `Wallet`.

**Comment by notmandatory** [comment]
I think we should tag `1.0.0-alpha.1` as soon #1011 is in, can I move this issue to `alpha.2` ?

**Comment by LLFourn** [comment]
Hmm this one probably shouldn't have been dropped from `1.0.0-alpha.1` as it's trivial to implement and highest possible priority since users are rightly complaining about this one. How should we indicate that an issue *cannot* be moved from a milestone (without having to have a back and forth)? Just state that in a comment?

**Comment by nondiremanuel** [comment]
Last week, talking with Steve, we decided that I will try to be in charge of the priorities inside the different milestones (we communicated it in the last Lib Team Call but we should probably put it in the chat somewhere). 
So my proposal would be that if a specific issue needs to be solved within a specific realease/milestone, the procedure could be to either tag me in a comment on the specific issue (so that also others can see it) or contact me directly (I will then be responsible for the communication to the other team members). What do you think @notmandatory @LLFourn?

Regarding this specific issue, I propose to add a 4th priority to the alpha.2 milestone to include it

**Comment by notmandatory** [comment]
I'd prefer to move this sort of thing to the `alpha.4` milestone which has other wallet improvements. But if users need this now and it's won't be too big a distraction then I don't see a problem keeping it in `alpha.2`.

**Comment by LLFourn** [comment]
Thanks @nondiremanuel. I really think we should make sure these are in the next release. I can mentor anyone on how to do this if it's needed.

**Comment by notmandatory** [comment]
@LLFourn is the goal of this issue to add a new internal utility method to be used by existing code like the [Wallet::get_tx()](https://docs.rs/bdk/1.0.0-alpha.1/bdk/wallet/struct.Wallet.html#method.get_tx) function? 

If I understand correctly `get_tx()` already provides a public API to do what a `Wallet::sent_and_received(txid: Txid)` function would do. 

I created #1048 to add a simple test to verify `Wallet::get_tx()` works as expected.

**Comment by LLFourn** [comment]
No the goal is to add an API. 

> This kind of utility function should be exposed to users of `Wallet`

See https://github.com/bitcoindevkit/bdk/issues/922#issuecomment-1652814975 for comments about `get_tx` which shouldn't return this information. The goal is to give the user more power over querying data about transactions. You can use `Wallet::sent_and_received` even for transactions that aren't in your wallet -- it's `Wallet::sent_and_received(tx: &Transaction)` e.g. a Transaction you've just created or one that has been sent to you e.g. PSBT that has been given to you to sign.

**Comment by notmandatory** [comment]
Ok that comment makes it more clear, I'll take a stab at it. 

Shoudl this new function return a tuple for sent/received amounts, or are you thinking a struct? I prefer a simple struct for clarity, ie: 

```rust
pub struct TransactionAmounts {
  pub sent: u64,
  pub received: u64,
}
```

**Comment by LLFourn** [comment]
> Ok that comment makes it more clear, I'll take a stab at it.
> 
> Shoudl this new function return a tuple for sent/received amounts, or are you thinking a struct? I prefer a simple struct for clarity, ie:
> 
> ```rust
> pub struct TransactionAmounts {
>   pub sent: u64,
>   pub received: u64,
> }
> ```

Sure struct is fine. Add it to `bdk_chain` as well though. Not a big fan of the `TransactionAmounts` name though. Maybe just `SentAndReceived`.
