### ISSUE TITLE
Unify changeset APIs between all structures

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#1022]
- Each structure has a different name for its changeset. For example `TxGraph` it's called `Additions` while IndexedTxGraph is called `IndexedAdditions`. Rather they should have the same name and users should just use different module prefixes e.g. `tx_graph::Additions` or `indexed_tx_graph::Additions`.
- Since these are monotone they don't need a "preview" methods. You can always just apply the update right away. I'd also include `LocalChain` in this policy despite it not being monotone ([yet](#1005)).

**Comment by evanlinjin** [comment]
Since we are already on this, can I request for some more renamings?

- [ ] `CanonicalTx::observed_as` should be renamed to `CanonicalTx::chain_position`.
- [ ] `CanonicalTx::node` should be renamed to `CanonicalTx::tx_node`.

I think this will provide more clarity.

Thanks @danielabrozzoni

**Comment by danielabrozzoni** [comment]
bitcoindevkit/bdk#1065 fixed this
