### ISSUE TITLE
Bump MSRV to 1.63

### ISSUE THREAD

**Issue by adoerr** [bitcoindevkit/bdk#1024]
The current MSRV is at `1.57`.

AFAIK this is in order to maintain compatibility with Debain stable. [Debian 12 "bookworm](https://www.debian.org/releases/bookworm/) ships with [rustc 1.63.0](https://packages.debian.org/bookworm/rustc).

Since `1.57` is causing growing pains, we should bump the MSRV to `1.63`.

**Comment by notmandatory** [comment]
One of our key users still needs us to support MSRV 1.57 so we'll be sticking with it for now. We can continue the discussion in #331.
