### ISSUE TITLE
Better naming

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/bdk#103]
- [ ] Stop using `ExtendedDescriptor` around the code, replace it with the full expansion `Descriptor<DescriptorPublicKey>`
- [x] <s>Find a nice name for `GeneratableKey` and `DerivableKey` </s>
- [x] Replace the tuples returned by `descriptor!()` and `fragment!()` either with an alias or a proper type
- [x] Rename `ScriptType` to `KeychainKind` as suggested in #210

**Comment by afilini** [comment]
I'm having second thoughts on the first point: since we use `ExtendedDescriptor` in some even more complex types maybe it helps to have an alias to make things a bit more readable..

**Comment by notmandatory** [comment]
I agree, `ExtendedDescriptor` helps readability. By my count it's used in 14 type references, mainly return types and at least one other pub type (`DescriptorTemplateOut`).
