### ISSUE TITLE
Importing descriptors

### ISSUE THREAD

**Issue by sander2** [bitcoindevkit/bdk#1032]
Is it possible to import descriptors into an existing wallet? I'm looking into the possibility of switching from bitcoin-core to BDK, but our application requires importing of keys/descriptors (which are generated externally). I haven't found a way to do this by looking at the docs. If this is not possible yet, would it be feasible to add? Or is it incompatible with BDK's design?

**Comment by danielabrozzoni** [comment]
Hey, what you can do with BDK is create a `Wallet` using a descriptor you generated externally. At the moment every wallet supports only up to two descriptors (the "main" one + an optional change descriptor), so if you need to watch multiple descriptors, you will need to create multiple `Wallet`s. 
https://docs.rs/bdk/latest/bdk/#sync-the-balance-of-a-descriptor

Does this answer your question?

**Comment by notmandatory** [comment]
Closing this one for now, can re-open if @sander2 has any follow-up questions.
