### ISSUE TITLE
Log dependency fix makes use as library very hard

### ISSUE THREAD

**Issue by stevenroose** [bitcoindevkit/bdk#1035]
bdk depends on `log = "=0.4.18"`, which is really annoying for anyone having another version of `log` in their dependency tree.

**Comment by LLFourn** [comment]
Looks like this was done in #1009. I think the correct solution is to just pin the version in CI using a CI specific Cargo.lock?

On a side note I'd be in favor of not using `log` throughout the codebase as I don't find it very helpful as an app developer but maybe that's just me.

**Comment by tnull** [comment]
> Looks like this was done in #1009. I think the correct solution is to just pin the version in CI using a CI specific Cargo.lock?

I think other project (LDK, `rust-bitcoin`) just have a `msrv` flag in CI and pin the respective dependencies based on it, i.e., we just run this in CI:

```bash
	[ "$RUSTC_MINOR_VERSION" -lt 49 ] && cargo update -p log --precise "0.4.18" --verbose
```
(see  https://github.com/lightningdevkit/rust-lightning/blob/8a8f29a8bb970ef99137db7233ca85e1a2406b7a/ci/ci-tests.sh#L16)

**Comment by danielabrozzoni** [comment]
Sorry, when I pinned `log` I didn't realize it could be an issue for downstream projects. #1046 should fix :)
