### ISSUE TITLE
Use `max_weight_to_satisfy` instead of `max_satisfaction_weight`

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#1036]
Needs #1023

`max_satisfaction_weight` is deprecated, we should switch to using `max_weight_to_satisfy` instead.

Note that the switch is not an easy search and replace, the two methods have slightly different definitions

**Comment by realeinherjar** [comment]
@notmandatory and @danielabrozzoni I want to try to help this one out.

**Comment by evanlinjin** [comment]
We need to discuss whether this needs to go into the BDK v1.0.0 release.

If we are overshooting while using `.max_weight_to_satisfy`, I think it is okay to leave it as is. It will be a large change to use the new rust-bitcoin methods.

If there is a chance for undershooting, that will be high risk and we should switch to use the new API.

**Comment by storopoli** [comment]
@nondiremanuel assign me and unassign @realeinherjar.
