### ISSUE TITLE
Use `bitcoin::FeeRate` instead of `bdk::FeeRate`

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#1037]
Needs #1023 

Since `bdk::FeeRate` has a few helpful methods that `bitcoin::FeeRate` doesn't have (`fee_wu`, `fee_vb` etc), maybe we should submit a patch to rust-bitcoin first

**Comment by tcharding** [comment]
I had to think a bit to see if we supported this so I figured it was not discoverable enough :) https://github.com/rust-bitcoin/rust-bitcoin/pull/1947

FTR you can use `bitcoin::FeeRate` as it is today, 1947 just adds convenience methods.

**Comment by danielabrozzoni** [comment]
Closing in favor of #1136, which is the same issue, but better specified :)

**Comment by notmandatory** [comment]
oops! @danielabrozzoni sorry I forgot you already had this one open.
