### ISSUE TITLE
Remove `ComputeSighash`

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#1038]
Needs #1023

Use the rust-bitcoin methods instead, and contribute upstream if they're lacking. See https://github.com/bitcoindevkit/bdk/pull/1023#discussion_r1263140218

**Comment by notmandatory** [comment]
A likely small change but I think we should push to post 1.0 milestone.

**Comment by nondiremanuel** [comment]
Needs some more research to understand if it's needed for 1.0

**Comment by ValuedMammal** [comment]
I'm willing to have a go at this.
