### ISSUE TITLE
The Wallet.is_mine() function should return K

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1042]
**Describe the enhancement**  

The `Wallet.is_mine(&self, script: &[Script])` function currently returns a `bool` representing "whether or not a script is part of this wallet (either internal or external)". It would be more useful to know which `KeychainKind` the script was found for, or `None` if not one of my scripts:

```
pub fn is_mine(&self, script: &[Script]) -> Option<KeychainKind>
```

**Use case**  

A request came up on discord about how to figure out which output is the change. Having `is_mine()` tell you which chain a script is for would make this easy to figure out.

**Comment by LLFourn** [comment]
Note `is_mine` just takes a `&Script`. You probably want the keychain and dervation index. We have a method for that called `derivation_of_spk` so this can be fixed by just updating the docs to point to that function if you want it.

**Comment by notmandatory** [comment]
@nondiremanuel we didn't discussed this one yesterday but I think it belongs in alpha.3.

**Comment by nondiremanuel** [comment]
@notmandatory great, thanks for letting me know!

**Comment by realeinherjar** [comment]
As discussed in [W39 Lib Team Call](https://github.com/bitcoindevkit/.github/issues/78), I think that the methods prefixed with `is_*` should always return a `bool` for consistency sake.
We should create a new `Wallet` method that returns `Option<KeychainKind>`.

**Comment by notmandatory** [comment]
I agree we should add a new function. What should we call it? does something like this make sense? `in_keychain(&self, &Script) -> Option<KeychainKind>`

**Comment by LLFourn** [comment]
`which_keychain_derived(&self, &Script)`

**Comment by vladimirfomene** [comment]
Let me take this up, @notmandatory.

**Comment by LLFourn** [comment]
Is there actually anything to do here. What's wrong with `derivation_of_spk`?

**Comment by evanlinjin** [comment]
Idiomatically, I think `is_mine` should return a boolean. I think we can update the docs (as @LLFourn suggested) to use the `deriation_of_spk` method of Wallet.

**Comment by 15IITian** [comment]
@vladimirfomene 
are you still working on it?

**Comment by notmandatory** [comment]
A likely small change but I think we should push to 2.0 milestone.

**Comment by notmandatory** [comment]
Since we have `deriation_of_spk` closing the issue.  Can re-open if someone finds a reason not to use the existing function.
