### ISSUE TITLE
Examples should not use `temp_dir`

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#1045]
Things like database location this should be passed in on the command line. This creates a permanent file in the user's temp dir we never clean up. See:

https://github.com/bitcoindevkit/bdk/blob/f4d2a76661d465dd0640d54470b95cc7b5ece979/example-crates/wallet_electrum/src/main.rs#L18

**Comment by notmandatory** [comment]
Put this one in the beta.0 milestone since it's not a core functional change.

**Comment by ValuedMammal** [comment]
I think this can be closed now that all example crates are fixed to no longer use `std::env::temp_dir`
