### ISSUE TITLE
Descriptor Checksum does not work in Core

### ISSUE THREAD

**Issue by Rob1Ham** [bitcoindevkit/bdk#1050]
**Describe the bug**  
Built a descriptor wallet using BDK, and upon importing it into Bitcoin Core (Version 25), I get a checksum error.

**To Reproduce**  
Here is a reference descriptor I made:

```
wsh(or_d(pk([19fe24dc/48'/1'/0'/2']tpubDE7MGwcP7w5E3wfvUQn34sW3p397vJriWfZmELejesvimiro8Qubtbmw73MscX2bnRgQztJvmJhUwDMfpXZfnQRMsJ6DfctJHctnjgiC7T5/0/*),and_v(v:pk([d83593a2/48'/1'/0'/2']tpubDF4vhecRfUyYF5AEzfcFC7oNapKKVm24wdJmkjZ6QZefJsT6wAvFPotgAAPSCmWTDkysMHk9kv5pzwUDTNpDbAUj4vP6arLVt6YAysoan16/0/*),after(1690761600))))#2cksg9jk
```

I then took this descriptor, and loaded into bitcoin core (testnet) with the following steps:

1. Create a View Only Wallet `createwallet bdktest true`
2. Load the Descriptor Generated from BDK: `importdescriptors '[{ "desc": "wsh(or_d(pk([19fe24dc/48'/1'/0'/2']tpubDE7MGwcP7w5E3wfvUQn34sW3p397vJriWfZmELejesvimiro8Qubtbmw73MscX2bnRgQztJvmJhUwDMfpXZfnQRMsJ6DfctJHctnjgiC7T5/0/*),and_v(v:pk([d83593a2/48'/1'/0'/2']tpubDF4vhecRfUyYF5AEzfcFC7oNapKKVm24wdJmkjZ6QZefJsT6wAvFPotgAAPSCmWTDkysMHk9kv5pzwUDTNpDbAUj4vP6arLVt6YAysoan16/0/*),after(1690761600))))#2cksg9jk", "timestamp":1690724495, "range": [0,100], "internal": false}]'`

Response:

```

  {
    "success": false,
    "error": {
      "code": -5,
      "message": "Provided checksum '2cksg9jk' does not match computed checksum 'v50375vl'"
    }
  }
]
```

When reimported with the computed checksum from core, it loads, and is able to see balances.

**Build environment**  
 - BDK tag/commit: v0.28.0

**Comment by apoelstra** [comment]
This may be a bug in rust-miniscript. Thanks for reporting!

**Comment by apoelstra** [comment]
cc @sanket1729 in case you get a moment to look at this before I do.

**Comment by darosior** [comment]
Looks like it's an issue in Core. `2cksg9jk` is also what `getdescriptorinfo` gives you, which in turn gets refused by `importdescriptors`.

```
$ bc -signet getdescriptorinfo "wsh(or_d(pk([19fe24dc/48'/1'/0'/2']tpubDE7MGwcP7w5E3wfvUQn34sW3p397vJriWfZmELejesvimiro8Qubtbmw73MscX2bnRgQztJvmJhUwDMfpXZfnQRMsJ6DfctJHctnjgiC7T5/0/*),and_v(v:pk([d83593a2/48'/1'/0'/2']tpubDF4vhecRfUyYF5AEzfcFC7oNapKKVm24wdJmkjZ6QZefJsT6wAvFPotgAAPSCmWTDkysMHk9kv5pzwUDTNpDbAUj4vP6arLVt6YAysoan16/0/*),after(1690761600))))"
{
  "descriptor": "wsh(or_d(pk([19fe24dc/48'/1'/0'/2']tpubDE7MGwcP7w5E3wfvUQn34sW3p397vJriWfZmELejesvimiro8Qubtbmw73MscX2bnRgQztJvmJhUwDMfpXZfnQRMsJ6DfctJHctnjgiC7T5/0/*),and_v(v:pk([d83593a2/48'/1'/0'/2']tpubDF4vhecRfUyYF5AEzfcFC7oNapKKVm24wdJmkjZ6QZefJsT6wAvFPotgAAPSCmWTDkysMHk9kv5pzwUDTNpDbAUj4vP6arLVt6YAysoan16/0/*),after(1690761600))))#2cksg9jk",
  "checksum": "2cksg9jk",
  "isrange": true,
  "issolvable": true,
  "hasprivatekeys": false
}
```

```
$ bc -signet importdescriptors '[{"desc":"wsh(or_d(pk([19fe24dc/48'/1'/0'/2']tpubDE7MGwcP7w5E3wfvUQn34sW3p397vJriWfZmELejesvimiro8Qubtbmw73MscX2bnRgQztJvmJhUwDMfpXZfnQRMsJ6DfctJHctnjgiC7T5/0/*),and_v(v:pk([d83593a2/48'/1'/0'/2']tpubDF4vhecRfUyYF5AEzfcFC7oNapKKVm24wdJmkjZ6QZefJsT6wAvFPotgAAPSCmWTDkysMHk9kv5pzwUDTNpDbAUj4vP6arLVt6YAysoan16/0/*),after(1690761600))))#2cksg9jk","timestamp":"now"}]'
[
  {
    "success": false,
    "error": {
      "code": -5,
      "message": "Provided checksum '2cksg9jk' does not match computed checksum 'v50375vl'"
    }
  }
]
```

**Comment by darosior** [comment]
Hahaha actually no. You aren't escaping the `'` in the origin's derivation path. :-)

By using `"` instead of `'` to delimit the JSON in the Bash escape there is no issue:
```
$ bc -regtest -rpcwallet=test_rob importdescriptors "[{ \"desc\": \"wsh(or_d(pk([19fe24dc/48'/1'/0'/2']tpubDE7MGwcP7w5E3wfvUQn34sW3p397vJriWfZmELejesvimiro8Qubtbmw73MscX2bnRgQztJvmJhUwDMfpXZfnQRMsJ6DfctJHctnjgiC7T5/0/*),and_v(v:pk([d83593a2/48'/1'/0'/2']tpubDF4vhecRfUyYF5AEzfcFC7oNapKKVm24wdJmkjZ6QZefJsT6wAvFPotgAAPSCmWTDkysMHk9kv5pzwUDTNpDbAUj4vP6arLVt6YAysoan16/0/*),after(1690761600))))#2cksg9jk\", \"timestamp\":1690724495, \"range\": [0,100], \"internal\": false}]"
[
  {
    "success": true
  }
]
```

An alternative is to use `h` instead of `'`.

**Comment by Rob1Ham** [comment]
Ok, this explains another issue I saw in Core, where the PSBTs which are generated are removing the hardened flags for the public keys... So this would be a 2 for one fix for the other issue I was seeing.

**Comment by evanlinjin** [comment]
Thank you to @darosior for spotting the problem in https://github.com/bitcoindevkit/bdk/issues/1050#issuecomment-1658428482. Closing for now.
