### ISSUE TITLE
Further enhancements to `Update` and `ChangeSet` structures

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1061]
**Describe the enhancement**  

As suggested by @LLFourn:

1. LocalUpdate should be moved to bdk Wallet. 
2. We shouldn't use LocalUpdate in electrum API (it doesn't need to be there IMO). 
3. Delete LocalChangeSet or move it to bdk Wallet. We should implement `Append` for tuples (A,B) where A: Append, B:Append and use this as our changeset in the examples instead of `LocalChangeSet`. i.e. we can just go type ChangeSet = (local_chain::ChangeSet, indexed_tx_graph::ChangeSet<...>)

**Comment by evanlinjin** [comment]
We also need to remove `preview_..` methods from `TxGraph` since it is a monotone structure now.

**Comment by evanlinjin** [comment]
Something else I realized, is the `ForEachTxOut` trait strictly needed still?

**Comment by LLFourn** [comment]
> We also need to remove `preview_..` methods from `TxGraph` since it is a monotone structure now.

This is done in https://github.com/bitcoindevkit/bdk/pull/1065 I think.

**Comment by vladimirfomene** [comment]
Hi @evanlinjin ! I will like to take this up.

**Comment by evanlinjin** [comment]
@vladimirfomene Thanks for taking this on. Go hard!
