### ISSUE TITLE
Allow BDK to be built with `env_logger` version `0.10`

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1067]
**Describe the enhancement**

As noted by @monaka in #1012, `env_logger` versions below `0.10` uses `atty` (which is unmaintained). BDK should allow projects with higher MSRVs to use `env_logger`.

@apoelstra suggested in https://github.com/bitcoindevkit/bdk/pull/1012#issuecomment-1667796182:

> If the dep can really be bumped with no changes to the codebase, it may be possible to provide a ranged version that covers multiple major versions.

If this is even possible, we need to update CI to test for every version of `env_logger` in our specified range using `cargo update --precise`.

**Comment by LLFourn** [comment]
> If this is even possible, we need to update CI to test for every version of `env_logger` in our specified range using `cargo update --precise`.

what? :rofl: :rofl: Do we rely on the precise details of `env_logger` to communicate transactions surreptitiously between threads or something? How could `env_logger` even influence the outcome of a CI?

**Comment by LLFourn** [comment]
We can also just delete `env_logger` as a dev dependency. It's only used in examples in that we will delete before `1.0` (I hope anyway).
