### ISSUE TITLE
Implement `TxGraph::map_anchor` method

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1096]
Not part of this PR necessarily but the code below seems super complicated and uses changesets for no reason? How about we just have a function on `tx_graph.map_anchor(|anchor| get_new_anchor(anchor))` which consumes self and returns a new `TxGraph` with the new anchor.

_Originally posted by @LLFourn in https://github.com/bitcoindevkit/bdk/pull/1084#discussion_r1305418097_

**Comment by notmandatory** [comment]
Does this still need to be done? @LLFourn @evanlinjin 

For now I've put it in the alpha.4 milestone so we don't forget to address it.

**Comment by LLFourn** [comment]
The code I was complaining about seems to be a bit improved. I think it still might be a nice method to have but we can close this until the need arises.
