### ISSUE TITLE
CI: dependabot to automate GitHub actions updates

### ISSUE THREAD

**Issue by realeinherjar** [bitcoindevkit/bdk#1118]
Currently there's a bunch of actions that are outdated, e.g. https://github.com/bitcoindevkit/bdk/blob/2867e88b64b4a8cf7136cc562ec61c077737a087/.github/workflows/audit.yml#L16
which is already on `v4`.

Adding a [`dependabot.yml`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) to update these on a sane interval (weekly?) could help us.
It will automatically create PRs updating the CI GitHub actions.

dependabot was recently implemented in `rust-bitcoin`, see https://github.com/rust-bitcoin/rust-bitcoin/pull/2052.

**Comment by realeinherjar** [comment]
Assign it to me, I will add these today after work hours.

**Comment by apoelstra** [comment]
We did this in rust-bitcoin. I think it's been a net positive. It opens PRs to update versions of various things in the CI pipeline. Usually these are 1-line changes. No visible effects, but keeps us from getting too out of date.
