### ISSUE TITLE
Calling `example_electrum sync` on an unconfirmed tx may result in the tx being stuck as unconfirmed eternally (according to the cli))

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1125]
**Describe the bug**  
Calling `example_electrum sync` on an unconfirmed tx may result in the tx being stuck as unconfirmed eternally (according to the cli)).

**To Reproduce**  
1. Send a transaction: `example_electrum send 123456 <insert-address-here>`.
2. Perform `example_electrum sync` until the transaction is confirmed (according to the block explorer).
3. Do `example_electrum balance` -> You'll see that the transaction is not confirmed (according to our cli).
4. Do `example_electrum scan && example_electrum balance` -> The transaction is still NOT confirmed!

The transaction is forever stuck as unconfirmed according to our cli.

**Expected behavior**  

That the tx is viewed as confirmed by our cli.

**Comment by evanlinjin** [comment]
New discovery: The cli saw it as confirmed after I called `scan` after one additional confirmation.

**Comment by realeinherjar** [comment]
Here's a full detail.

You can reproduce with this testnet wallet:

```bash
> RUST_BACKTRACE=1 cargo run --bin example_electrum -- "wpkh([5a900f0d/84h/0h/0h]tpubDD3XVLEKGcQtRC4Yir3crZDHZapMr4chWsXBgscV4j7Vf522PL2gvu3UkZ1taM6x9LdQWK224LDmsdJAkZ9uPC1Q5K8vJcfzc3h7h83ozTw/0/*)#lts5g0c5" send 1402800 mohjSavDdQYHRYXcS3uS6ttaHP8amyvX78
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/example_electrum 'wpkh([5a900f0d/84h/0h/0h]tpubDD3XVLEKGcQtRC4Yir3crZDHZapMr4chWsXBgscV4j7Vf522PL2gvu3UkZ1taM6x9LdQWK224LDmsdJAkZ9uPC1Q5K8vJcfzc3h7h83ozTw/0/*)#lts5g0c5' send 1402829 mohjSavDdQYHRYXcS3uS6ttaHP8amyvX78`
thread 'main' panicked at 'not yet implemented', /Users/storopoli/git/bdk/nursery/tmp_plan/src/lib.rs:437:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:117:5
   3: bdk_tmp_plan::plan_satisfaction
             at ./nursery/tmp_plan/src/lib.rs:437:32
   4: example_cli::create_tx
             at ./example-crates/example_cli/src/lib.rs:462:23
   5: example_cli::run_send_cmd
             at ./example-crates/example_cli/src/lib.rs:348:33
   6: example_cli::handle_commands
             at ./example-crates/example_cli/src/lib.rs:673:13
   7: example_electrum::main
             at ./example-crates/example_electrum/src/main.rs:93:23
   8: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It hits
https://github.com/bitcoindevkit/bdk/blob/59fc1b341ba94212b2ea3e888e51fb6fcd00589f/example-crates/example_cli/src/lib.rs#L462

which calls
https://github.com/bitcoindevkit/bdk/blob/59fc1b341ba94212b2ea3e888e51fb6fcd00589f/nursery/tmp_plan/src/lib.rs#L427-L442
which has a bunch of `todo!()` in the satisfaction logic.

PS: the address is the testnet faucet that I took the coins out.

**Comment by danielabrozzoni** [comment]
Re-opening as #1145 didn't fix this

**Comment by evanlinjin** [comment]
May be fixed by this: https://github.com/bitcoindevkit/bdk/issues/1354

**Comment by notmandatory** [comment]
Move to beta milestone to re-test.

**Comment by evanlinjin** [comment]
Because `bdk_electrum` has already been re-architectured so that chain updates and anchor updates are fetched orthogonal to each other, I don't think this bug can occur any longer...

However let's have tests to make sure previously unconfirmed transactions get confirmed again in both reorg and no-reorg situations.

**Comment by LagginTimes** [comment]
I'll take a look at this.
