### ISSUE TITLE
`TxGraph::direct_conflicts_of_tx` should just be called `direct_conflicts`

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#1138]
See https://github.com/bitcoindevkit/bdk/pull/1064#discussion_r1329414295

**Comment by rustaceanrob** [comment]
Before I submit a PR this is just a rename of `TxGraph::direct_conflicts_of_tx` to `TxGraph::direct_conflicts`?

**Comment by danielabrozzoni** [comment]
> Before I submit a PR this is just a rename of TxGraph::direct_conflicts_of_tx to TxGraph::direct_conflicts?

Yes, but please either build your PR on top of #1064 or wait for it to be merged before working on this :)
