### ISSUE TITLE
Coinbase transaction that is not anchored in the best chain should always be filtered out

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1144]
**Describe the bug**  

Coinbase transactions cannot exist in the mempool and be unconfirmed. `TxGraph::try_get_chain_position` should always return `None` for coinbase transactions which are not anchored in the best chain.

**To Reproduce**  

A proper test has not been written for this scenario. The test would mine blocks which has the coinbase send to a tracked/owned spk. A reorg should not result in an unconfirmed balance.

**Expected behavior**  

Coinbase transactions cannot be "unconfirmed".

**Comment by evanlinjin** [comment]
I recommend working on this only AFTER #1064 is merged.

**Comment by LagginTimes** [comment]
I can take a look at this.

**Comment by evanlinjin** [comment]
> I can take a look at this.

Go for it. Base it on #1064 and I guess start with writing the test case.
