### ISSUE TITLE
bdk + esplora not seeing an old transaction as confirmed

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#1151]
**Describe the bug**  
When syncing using bdk and esplora, we might not see that a certain tx is confirmed, and consider it unconfirmed forever

**To Reproduce**  
See https://github.com/sebastianmontero/bdk-esplora-test

**Expected behavior**  
bdk correctly seeing a transaction as confirmed when it is

**Build environment**  
 - BDK tag/commit: 4ee11aae12f5f5b636008195998833268d5edc66

**Comment by LLFourn** [comment]
The bug is in the above code and in the wallet example. You're meant to ask the update what heights are missing from the current chain not the wallet. Though I'm not sure why it would be unconfirmed forever. The transaction should be added with its anchors anyway so it should be missing the next time I would have thought. Can we confirm why the anchor is not returned from `missing_heights` in the future? Is it never inserted? If it's there and not returned it's probably a bug in `missing_heights`.

**Comment by danielabrozzoni** [comment]
@LLFourn `missing_heights` would return the anchor, but `update_local_chain` wouldn't insert it as it's older than `ASSUME_FINAL_DEPTH`:

https://github.com/bitcoindevkit/bdk/blob/4a65a12c4fe9bb419906d5c921bbff8b8b4e5379/crates/esplora/src/blocking_ext.rs#L134-L140

**Comment by LLFourn** [comment]
> @LLFourn `missing_heights` would return the anchor, but `update_local_chain` wouldn't insert it as it's older than `ASSUME_FINAL_DEPTH`:
> 
> https://github.com/bitcoindevkit/bdk/blob/4a65a12c4fe9bb419906d5c921bbff8b8b4e5379/crates/esplora/src/blocking_ext.rs#L134-L140

But it should be part of `request_heights` is what I mean. The things in `request_heights` are always fetched:

https://github.com/bitcoindevkit/bdk/blob/4a65a12c4fe9bb419906d5c921bbff8b8b4e5379/crates/esplora/src/blocking_ext.rs#L107-L117

So more succinct question why isn't the things in `missing_heights` going into `request_heights` and then being returned.
Maybe something going wrong here:

https://github.com/bitcoindevkit/bdk/blob/4a65a12c4fe9bb419906d5c921bbff8b8b4e5379/crates/esplora/src/blocking_ext.rs#L178-L186

**Comment by danielabrozzoni** [comment]
Yeah, I can look better into it tomorrow, but as far as I can tell the block is fetched as part of the request heights, but then not added to the chain because the earliest agreement checkpoint is not early enough. I initially thought it was because of ASSUME_FINAL_DEPTH, but I might be wrong.
-------- Original Message --------

**Comment by LLFourn** [comment]
This seems like a bug if so. Thanks a lot for looking into it. I'll just reopen this because I think although this is not the main problem it should have fixed itself. FWIW I don't understand why we are doing a `split_off` which seems like it might be the culprit.

cc @evanlinjin

**Comment by evanlinjin** [comment]
https://github.com/sebastianmontero/bdk-esplora-test/blob/master/src/main.rs#L34

Would this line be the culprit?

**Edit:** okay this is already bought up, I didn't read the above conversation.

**Comment by nondiremanuel** [comment]
I close this issue since it was fixed by #1152

**Comment by danielabrozzoni** [comment]
Fair, I opened #1199 to keep track of the bug we discovered while investigating this one
