### ISSUE TITLE
Need a method to set the index lookahead for Wallet

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#1166]
See https://github.com/bitcoindevkit/bdk/pull/1152#issuecomment-1753088941

**Comment by nondiremanuel** [comment]
@notmandatory why in alpha.4? I see it will be closed by #1172 that is in the alpha.3

**Comment by notmandatory** [comment]
I think I moved it based on the title without seeing the comment that it's linked to #1172.

**Comment by notmandatory** [comment]
Should be fixed by #1229
