### ISSUE TITLE
Fix clippy warnings and enable the clippy CI job

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#118]
To find [clippy](https://github.com/rust-lang/rust-clippy) warnings that need to be fixed (or selectively disabled) run: `cargo clippy -- -D warnings`

To enable the clippy CI job un-comment the `clippy` job in `.github/workflows/cont_integration.yml` 

Depends on https://github.com/bitcoindevkit/bdk/pull/117

**Comment by notmandatory** [comment]
Looks like the only code warnings we have are for `cargo +1.45.0 check` or `cargo +1.45.0 clippy` but not for +stable. This can be fixed by just changing the CI job to only do `check` and `clippy` for +stable.

**Comment by afilini** [comment]
Yeah that's probably fine. We want to support 1.45 for compilation but it doesn't really matter if it throws clippy warnings.
