### ISSUE TITLE
Question: Support for Discreet Log Contracts (DLCs)

### ISSUE THREAD

**Issue by nud3l** [bitcoindevkit/bdk#1181]
**Describe the enhancement**  
I was wondering if support for DLCs is planned as I think they would make a decent addition to constructing spending conditions in wallets. I found a reference for proof of reserves in https://github.com/bitcoindevkit/bdk/pull/356 and the repo https://github.com/bitcoindevkit/bdk-reserves.

**Use case**  
We'd be interested in constructing DLC within a Rust-only wallet implementation for a two-way Bitcoin<>EVM bridge. However, there are several other teams working on DLCs for all sorts of use cases.

**Additional context**
I'm aware of the early stage Rust DLC library https://github.com/p2pderivatives/rust-dlc

**Comment by LLFourn** [comment]
Hi @nud3l, I'd expect there never to be support for DLC protocols maintained as part of this project. The research at every level still in flux and there are many ways to approach the protocol implementation. As you mentioned the `rust-dlc` project is the most bleeding edge attempt at a standardized implementaiton -- but is still changing a lot. We are of course open to adding APIs and features that make it easier to use bdk with projects like `rust-dlc`.

**Comment by nud3l** [comment]
Thanks, makes sense.
