### ISSUE TITLE
Rename `ConfirmationTimeAnchor` to `ConfirmationTimeHeightAnchor`

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#1187]
From the `ConfirmationTimeAnchor` docs:

> An [Anchor](https://docs.rs/bdk_chain/0.6.0/bdk_chain/trait.Anchor.html) implementation that also records the exact confirmation time and height of the transaction.

If it records both the time and height, why is only "time" included in the name?

**Comment by LLFourn** [comment]
I guess we felt height was obvious. Maybe not though. Fine with the rename.

**Comment by danielabrozzoni** [comment]
Reopening as it might have been closed by mistake

**Comment by LLFourn** [comment]
It was oops.
