### ISSUE TITLE
Make script_sync public

### ISSUE THREAD

**Issue by e1a0a0ea** [bitcoindevkit/bdk#1189]
**Describe the enhancement**  
Publicly expose `script_sync` fn to be able to use it outside of BDK

**Use case**  
I need to build both a custom client and backend that would be simple wrappers around electrum-client (with some api part tweaked) and ElectrumBlockchain. Everything needed is well exposed from BDK except this function to trigger wallet sync. 

**Additional context**
I tried to copy `script_sync` into my wrapper's code but in the end I figured out `MissingCachedScripts` struct (not enum element) is not exposed neither. While exposing only `MissingCachedScripts` would unblock me, I believe it makes more sense to make the whole `script_sync` thingy public, to allow building such wrappers around electrum conveniently.

**Comment by notmandatory** [comment]
Is this issue for the pre-1.0.0-alpha code? Check the new `bdk_chain` and `bdk_electrum` and `bdk_esplora` crates and related examples and let us know if they work for your use case.

**Comment by LLFourn** [comment]
This is not longer relevant. You should be able to customize anything you want when fetching blockchain data.
