### ISSUE TITLE
Add CI job to calculate and publish test coverage metrics

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#119]
Test coverage results should be published to [codecov](https://codecov.io/) or [coveralls](https://coveralls.io/) and add badge/link to results on README.md.

Two possible plugins to use are:

[actions-rs/grcov](https://github.com/actions-rs/grcov)
[actions-rs/tarpaulin](https://github.com/actions-rs/tarpaulin)

Depends on https://github.com/bitcoindevkit/bdk/pull/117

**Comment by afilini** [comment]
Done in #150
