### ISSUE TITLE
Upgrade to `rust-bitcoin` 0.31.0

### ISSUE THREAD

**Issue by tnull** [bitcoindevkit/bdk#1196]
**Describe the enhancement**  
`rust-bitcoin` 0.31.0 was recently released and includes changes that so far kept LDK from upgrading to 0.3X.Y (cf. https://github.com/lightningdevkit/rust-lightning/issues/2124#issuecomment-1791464639).

**Additional context**
Probably currently blocked on https://github.com/rust-bitcoin/rust-miniscript/issues/622

**Comment by tnull** [comment]
This now seems unblocked as `rust-miniscript` 11.0 was just released.

**Comment by tnull** [comment]
@notmandatory Is the current plan to do this as part of `1.0-alpha.3` or `1.0-alpha.4`? Trying to wrap my head around when I need for LDK to upgrade to be able to use the latest `bdk`/`rust-esplora-client`/`rust-electrum-client` in LDK Node.

**Comment by notmandatory** [comment]
@tnull this PR is still scheduled for the `bdk` `1.0-alpha.X` milestone release. But you are correct we also need to  make sure the below PRs are released first:

1. bitcoindevkit/rust-electrum-client#121  released in 0.19.0
2. RCasatta/electrsd#74 released in 0.27.0
3. bitcoindevkit/rust-esplora-client#79 released in 0.7.0
4. bitcoindevkit/rust-hwi#91 released in 0.8.0

**Comment by nondiremanuel** [comment]
Needs to stay in 1.0.0 milestone in order to not block LDK, but we need to check also other dependencies
It makes sense to upgrade to rust 0.31.0 for beta (It doesn't seem 0.31 changes are too drastic)

**Comment by notmandatory** [comment]
take a look at #1191 when this one is done.
