### ISSUE TITLE
bdk + esplora `update_local_chain` logic might be off 

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#1199]
See the discussion in #1151: https://github.com/bitcoindevkit/bdk/issues/1151#issuecomment-1752555182 (and following comments)

**Comment by evanlinjin** [comment]
@LagginTimes didn't you have a WIP progress PR to fix this? I remember we just needed to update the tests to "prove" the fix (which is waiting on the `TestEnv`.

**Comment by LagginTimes** [comment]
The PR #1145 fixed an electrum issue which seems to be unrelated to the esplora problem described here.

**Comment by evanlinjin** [comment]
I'm looking into this now!
