### ISSUE TITLE
Add oldest first coin selection next to largest first coin selection

### ISSUE THREAD

**Issue by murchandamus** [bitcoindevkit/bdk#120]
According to @afilini in the developer meeting today, BDK currently uses "dumb" largest first selection. Largest first selection tends to create small input sets in the short term but tends to grind the biggest UTXO to smaller chunks until it eventually causes a huge input set.

As discussed, it would be good to replace it with something that has a better average performance such as oldest first selection or random selection. Optimally, all of the above would be run and the best input set would be chosen per a simple heuristic among the candidate input sets. 

This task should coordinate with implementation efforts for #48.

**Comment by kafaichoi** [comment]
I am interested in contributing to bdk. Can I work on this issue?

**Comment by notmandatory** [comment]
Hi, yes it's all yours, I'll put your name on it. If you have any questions feel free to comment here or on the Bitcoin Dev Kit discord.

**Comment by csralvall** [comment]
Hi! this issue also mentions random selection.
I see that SRD is implemented as a method for the BnB algorithm, but It might be useful to trait each one as a different algorithm, as in Bitcoin Core.
Do you think that it will be useful?

**Comment by kafaichoi** [comment]
just made a draft PR https://github.com/bitcoindevkit/bdk/pull/557. I will really appreciate for a quick look to see if it's heading to right direction😬

**Comment by danielabrozzoni** [comment]
Closed by #557
