### ISSUE TITLE
Make sure all docs and example derivation paths correspond to the network

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1209]
unrelated to this PR, but the derivation path should correspond to the network, e.g. `m/86h/1h/0h/0`

_Originally posted by @ValuedMammal in https://github.com/bitcoindevkit/bdk/pull/1028#discussion_r1391637131_

**Comment by ValuedMammal** [comment]
This is the only place I noticed where `Network::Testnet` is used but the derivation path starts with `m/86h/0h`. I guess nothing prevents you from using any deriv path you like (the network is checked against the xpub?), but for consistency and as a general best practice, testnet examples should also use the testnet coin type as described in BIP44, for example `m/86h/1h`. 

https://github.com/bitcoindevkit/bdk/blob/46d39beb2caa759f19bcf3e6397de3029b1aab6a/crates/bdk/examples/mnemonic_to_descriptors.rs#L35-L37

If others agree, this could probably get lumped in with #1223

**Comment by notmandatory** [comment]
Thanks for checking @ValuedMammal, @realeinherjar can you fix this in your #1223?

**Comment by ValuedMammal** [comment]
From what I can tell, all of our documented examples use a derivation path that makes sense for the network, in particular using coin type 1 for testnet. Also addressed by #1286, #1378
