### ISSUE TITLE
Add DIY logger

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1222]
Should we open an issue to introduce some sort of diy logger as ldk does?

_Originally posted by @danielabrozzoni in https://github.com/bitcoindevkit/bdk/issues/1204#issuecomment-1814170348_

**Comment by notmandatory** [comment]
Added this issue as a placeholder. It's not part of the user API so can do it at any time.

**Comment by LLFourn** [comment]
My take is that our architecture doesn't require logging. We no longer have any long running processes occurring in bdk itself. You could do logging in the blockchain crates for example but that can be decided on a crate by crate basis.

**Comment by notmandatory** [comment]
Closing this issue since we only depend on the `log` crate in examples, not in any of the lib crates.

**Comment by LLFourn** [comment]
(might be a nice idea to remove `log` from the examples. You can just use `println!` in examples)
