### ISSUE TITLE
Document spending wsh descriptor with sha256 primage

### ISSUE THREAD

**Issue by 0x330a** [bitcoindevkit/bdk#1244]
I have been trying to write a wsh descriptor and provide a way to spend relying on sha256 preimages however when analyzing the policy or output descriptor I can't seem to find a way to provide the actual data that's hashed, or after creating the wallet with a descriptor and a private key for signing one of the internal pk() nodes the .finish() call is resulting in an Err saying that an external spending policy is missing. Not sure if I'm doing something the "wrong way" but I haven't been able to find any documentation on which stage I should be trying to put this preimage into my data as opposed to just manually building transactions and inserting it as witness data myself. I was hoping the miniscript and descriptors stuff would let me do this easier but so far no luck. 

Not sure if better docs or just pointers to the right place to look would help here

**Comment by LLFourn** [comment]
https://docs.rs/miniscript/latest/miniscript/plan/index.html

The planning module in miniscript is the modern way to do what you're aiming at I think. You can use it to update a PSBT with with the "assets" you have available (like sha256 pre-image) and then finish the PSBT with it. It looks like you can also manually produce the witness without a PSBT too if you implment the `Satisfier` trait yourself: https://docs.rs/miniscript/latest/miniscript/plan/struct.Plan.html#method.satisfy or by using PSBTs by constructing: https://docs.rs/miniscript/latest/miniscript/psbt/struct.PsbtInputSatisfier.html

**Comment by 0x330a** [comment]
Thanks for the pointer, do the miniscript 11.0.0 descriptors work for the bdk 0.29.0 wallets / descriptors or will I have to figure out some workaround? Wasn't sure if the 1.0.0 alphas were stable enough to use as

**Comment by LLFourn** [comment]
I'd say you should use the alpha versions and see if you can break them. Regardless I think you should do all signing and stuff outside of BDK with the planning module (eventually BDK will use the planning module internally). Maybe it won't matter too much if the versions are incompatible as long as you can convert between them.

**Comment by 0x330a** [comment]
My thinking right now is I'll have to get a duplicate descriptor from the public information, create a `Wallet` instance out of that so I can sync the transactions and get all the appropriate UTXOs to spend, start building a transaction using this wallet, somehow serialize the TxBuilder to the duplicated descriptor using the planning module for building and signing the Tx, then serialize that Transaction back into the bdk `Wallet` to broadcast and keep track of the transactions. Not sure if I can think of a better way than something like that for now, unless anyone has any other ideas but as I said I'm not too familiar with the structures and how all these versions are supposed to work together

**Comment by LLFourn** [comment]
Huh why do you want to serialize the TxBuilder? Why can't you just let `Wallet` create the PSBT for you and fill it in? I don't think broadcasting through the `Wallet` does anything special. You can braodcast yourself.

**Comment by 0x330a** [comment]
I'm not sure honestly, it's giving me some kind of error for an external spending policy requirement when I try to call `finish()` on a transaction. Figured it was because the descriptor didn't have the required information to create a signature or something like that but I can't really follow where and why these errors are being created, I'm following the public/private key descriptors as closely to the documentation as I can

**Comment by LLFourn** [comment]
Hmmm I have no idea why it would do that. Can you debug print the error?

**Comment by 0x330a** [comment]
The error I'm getting is `Err(SpendingPolicyRequired(External))` when trying to build the wallet and finish the tx. The transaction is basically just `.drain_wallet().drain_to(some other address)`

**Comment by 0x330a** [comment]
the process I'm going through is building a wsh descriptor using the `descriptor!` macro in bdk, creating a wallet from this descriptor, adding a signer of `KeychainKind::External` to the wallet generated from the wsh descriptor, when I check the wallet's policies for KeychainKind::External I'm getting a list of policies for the EcdsaSignature which has `satisfaction: None` but `contribution: Complete` which I'm guessing means it is fulfilled or something, the `Sha256Preimage` policy which is the other component has no satisfaction or contribution (obviously, as I have no way to add that yet) but I'm not sure if this is the reason or something else entirely

**Comment by 0x330a** [comment]
It seems like this might be an issue whenever I add an extra path to the descriptor, even duplicating (with a different pubkey) the `and` section and wrap it into any kind of `or`, maybe it doesn't look deep enough or something I'm not sure

**Comment by 0x330a** [comment]
I'm just going to try build this with the 1.0.0-alpha.2 once I fix all the migrations

**Comment by 0x330a** [comment]
I think I've finally figured it out, seems like it needed the policy path and some way to potentially figure out which `vec![]` was required for the root id, I'm assuming I'll be able to just use 1 or 0 depending on the paths i.e. if I have two paths in the root policy it would be [1,0] for using the first path or [0,1] for the second route but seems the actual TX building problem is solved for now
