### ISSUE TITLE
Error when importing descriptor containing `zprv`

### ISSUE THREAD

**Issue by ghost** [bitcoindevkit/bdk#1248]
**Describe the bug**  
I have a wallet descriptor that looks like:
```
wpkh([f00b4r/84h/0h/0h]zprvAWidj[...])
```
Trying to import the descriptor into a `bdk` based wallet produces the error:
```
Descriptor error: Miniscript error: unexpected «unexpected «Public keys must be 64/66/130 characters in size»»
```
When I convert the `zprv` to `xprv` using [this tool](https://3rditeration.github.io/btc-extended-key-converter/) and replace the `zprv` in the wallet descriptor with the `xprv`, the descriptor imports fine.

`bdk` should really support zprv-based wallet descriptors.

**Build environment**  
- `bdkpython` 0.30.0

**Comment by apoelstra** [comment]
cc https://github.com/rust-bitcoin/rust-bitcoin/issues/2190 where rust-bitcoin describes why it does not, and will not, support ypubs and zpubs.

I've never heard of using these *inside* a descriptor. My understanding is that the point of these key types is to imply a descriptor. What if you had a descriptor that was, say, a `zpub` inside of `pkh()`? If this has a well-defined meaning we may want to support it as an import format in rust-miniscript, though of course the result will be internally converted to a normal descriptor.

**Comment by notmandatory** [comment]
question was answered above, closing.
