### ISSUE TITLE
Better names for methods

### ISSUE THREAD

**Issue by Ademan** [bitcoindevkit/bdk#1249]
It looks like `LocalUtxo` was renamed to `LocalOutput` in master, which seems like a great improvement in clarity. I came across #665 trying to determine whether or not `Wallet::get_utxo` actually returns *unspent* outputs or not. I'd propose renaming the rest of the wallet API (and database API) to reflect this type change in 1.x

**Comment by Ademan** [comment]
Maybe this is better labeled as a discussion.

**Comment by notmandatory** [comment]
Is the proposal here to find places in the new 1.0 APIs where we return `LocalOutput` and make sure the function names and docs are updated to not use the terms unspent ? I found a couple cases of this in the `bdk` crate:

- [ ] `LocalOutput` struct docs
- [ ] `Utxo` enum docs ? I'm not 100% sure this one is wrong

Are there other places that need fixing?

**Comment by ValuedMammal** [comment]
Feel free to leave suggestions on #1221 as well, where the idea is to come up with more idiomatic names

**Comment by notmandatory** [comment]
A small change but I think we should push to 2.0 milestone.

**Comment by nondiremanuel** [comment]
get_utxos seems in fact getting utxos
