### ISSUE TITLE
Wallet initialization require many time compared to `1.0.0-alpha.2`

### ISSUE THREAD

**Issue by yukibtc** [bitcoindevkit/bdk#1262]
**Describe the bug**  

Hi, I noticed a huge increase of time for construct a Wallet (ex. with `Wallet::new_no_persist`).

At commit 3fdab87ee7c02439b18a9e114ff588b282525402 the time to construct a `Wallet` with `new_no_persist` **in debug** was ~1 ms. 
Using `v1.0.0-alpha.3` (9efaead8f16a5a0bed18cea514cd94d6a9a0a582) require:
* between 1.5 and 2 sec in debug
* ~200 ms in release

**To Reproduce**  

```rust
use std::time::Instant;

use bdk::Wallet;
use bdk::bitcoin::Network;

fn main() {
    let descriptors = [
        "tr(d36cdca84bc66b9999fc5a28e7fbb05816cea06c55c6d7bc2fc6af60a1a1e91f,and_v(v:pk([7356e457/86'/1'/784923']tpubDCvLwbJPseNux9EtPbrbA2tgDayzptK4HNkky14Cw6msjHuqyZCE88miedZD86TZUb29Rof3sgtREU4wtzofte7QDSWDiw8ZU6ZYHmAxY9d/0/*),older(2)))#spvz86cq",
        "tr([e157a520/86'/1'/784923']tpubDCCYFYCyDkxo1xAzDpoFNdtGcjD5BPLZbEJswjJmwqp67Weqd2C7fg6Jy1SBjgn3wYnKyUtoYKXG4VdQczjqb6FJnqHe3NmFdgy8vNBSty4/0/*,pk([7356e457/86'/1'/784923']tpubDCvLwbJPseNux9EtPbrbA2tgDayzptK4HNkky14Cw6msjHuqyZCE88miedZD86TZUb29Rof3sgtREU4wtzofte7QDSWDiw8ZU6ZYHmAxY9d/0/*))#m9nhr276",
        "tr(99a6a987b2a5609d14a873aff531e878d723f24bac746ac3e6469c4d22645d68,thresh(3,pk([7356e457/86'/1'/784923']tpubDCvLwbJPseNux9EtPbrbA2tgDayzptK4HNkky14Cw6msjHuqyZCE88miedZD86TZUb29Rof3sgtREU4wtzofte7QDSWDiw8ZU6ZYHmAxY9d/0/*),s:pk([4eb5d5a1/86'/1'/784923']tpubDCLskGdzStPPo1auRQygJUfbmLMwujWr7fmekdUMD7gqSpwEcRso4CfiP5GkRqfXFYkfqTujyvuehb7inymMhBJFdbJqFyHsHVRuwLKCSe9/0/*),s:pk([f3ab64d8/86'/1'/784923']tpubDCh4uyVDVretfgTNkazUarV9ESTh7DJy8yvMSuWn5PQFbTDEsJwHGSBvTrNF92kw3x5ZLFXw91gN5LYtuSCbr1Vo6mzQmD49sF2vGpReZp2/0/*),snl:older(2)))#tdvgdnxk"
    ];

    for descriptor in descriptors.into_iter() {
        test_wallet_init(descriptor);
    }
}

fn test_wallet_init(descriptor: &str) {
    let now = Instant::now();
    let _wallet = Wallet::new_no_persist(descriptor, None, Network::Testnet).unwrap();
    println!("Took {} ms", now.elapsed().as_millis());
}
```

**Build environment**  
 - BDK tag/commit: 9efaead8f16a5a0bed18cea514cd94d6a9a0a582
 - Rust/Cargo version: 1.75.0 
 - Rust/Cargo target: x86_64-unknown-linux-gnu

**Comment by yukibtc** [comment]
Investigating I noticed that is related to the `KeychainTxOutIndex::replenish_lookahead` method

**Comment by evanlinjin** [comment]
Hey @yukibtc thank you for pointing this out. This is most likely due to the default `lookahead` value in the wallet's indexer. The wallet caches 1000 spks ahead of last revealed.

We can look at how to optimize deriving/caching spks. Additionally, we can have a lookahead parameter when constructing the wallet.

**Comment by evanlinjin** [comment]
Note that I think `lookahead` is not strictly necessary for spk-based syncing such as electrum/esplora. However, it is crucial for bock-by-block syncing to work properly.

**Comment by LLFourn** [comment]
I think we should just change the default to 25.
