### ISSUE TITLE
An alternative approach to `AnchorFromBlockPosition`.

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1266]
> This was done previously in #1041 but I missed it. Why can't we just have `BlockPosition: Into<A>` bound instead of adding our own conversion trait?

_Originally posted by @LLFourn in https://github.com/bitcoindevkit/bdk/pull/1172#discussion_r1444094122_

@evanlinjin's response:

> It's because there are 3 inputs and doing `A: From<(&Block, BlockId, usize)>` is confusing and we won't know what the `usize` is for.
> 
> An alternative would be to have:
> 
> ```rust
> /// Parameters for constructing an [`Anchor`].
> pub struct AnchorParams<'b> {
>     pub block: &'b Block,
>     pub block_id: BlockId,
>     pub tx_pos: usize,
> }
> 
> fn some_method<A: Anchor + From<AnchorParams>>() { todo!() }
> ```
> 
> What do you think? (`AnchorParams` will be nicely documented of course!)

**Comment by LLFourn** [comment]
I think the "alternative" is what I was suggesting. `AnchorParams` looks like a worse named version of `BlockPosition` which is what I suggested originally.
