### ISSUE TITLE
`TxGraph<A>` should be able to transform anchor types.

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1295]
**Describe the enhancement**  

```rust
impl<A1, A2: From<A1>> From<TxGraph<A1>> for TxGraph<A2> {
    // TODO
}
```

If `A2: From<A1>` is impossible, we can have a method:

```rust
impl<A> TxGraph<A> {
    pub fn map_anchors<A2, F>(self, f: F) -> TxGraph<A2> where F: Fn(A) -> A2 { todo!() }
}
```

**Use case**  

Some chain source methods return `TxGraph`s. It will be good to update original `TxGraph`s with different anchor types.

**Comment by LLFourn** [comment]
Same as #1096 I think. I closed it since we didn't have a concrete situation to do this. Do we have one now?

**Comment by evanlinjin** [comment]
@LLFourn I think we need this. There were a couple of times I was like "this functionality would be nice". Otherwise I've been recreating a `TxGraph` by getting an initial changeset and working from there.

**Comment by yanganto** [comment]
I want to try this. :smile:

**Comment by evanlinjin** [comment]
> I want to try this. 😄

Go for it!
