### ISSUE TITLE
Rename `bdk` crate to `bdk_wallet`

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#1305]
All it has in it is a Wallet and the README says:

> The `bdk` crate provides the [`Wallet`](`crate::Wallet`) type which is a simple, high-level
interface built from the low-level components of [`bdk_chain`].

It should probably just be called `bdk_wallet`

**Comment by evanlinjin** [comment]
Thanks for creating a ticket. Everyone was thinking this for a long while.

**Comment by notmandatory** [comment]
I put this on the project board, I think we should do it after #1203 and #1101 are merged. But should grab the `bdk_wallet` account in crates.io ASAP.

**Comment by thunderbiscuit** [comment]
Feels right to me as well. It makes it explicit that the wallet is _one_ of the crates the bdk project supports without giving it a special status (in that sense the simple `bdk` name was more confusing than anything given the 6 new crates).
