### ISSUE TITLE
[chain] keychain module doesn't need to exist

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#1317]
The module tries to explain itself as follows:

> A keychain here is a set of application-defined indexes for a miniscript descriptor where we can derive script pubkeys at a particular derivation index.

Which is very difficult to read. More importantly it only has one thing in it `KeyChainTxOutIndex`. We can just have `keychain_txout_index.rs`. We could move indexers into their own module so `indexers/keychain_txout.rs`, `indexers/spk_txout.rs`.

**Comment by evanlinjin** [comment]
Let's do this after #1203. I'll take responsibility for the convoluted crate docs.

**Comment by ValuedMammal** [comment]
@evanlinjin If you want I can open a PR and have you make suggestions for the crate docs.. Actually, removing this module means we won't need the old docs. This also gives us a chance to finally relocate the Balance struct
