### ISSUE TITLE
last_seen is wrong on both electrum and esplora

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#1336]
1. Esplora never sets `last_seen`
2. Electrum workflow sets it even for transactions it sees as confirmed.

`last_seen` should be strictly set when the transaction is seen in the mempool. If you set it superfluously you create db churn. Every change to it is added to the changeset and written to disk.

**Comment by evanlinjin** [comment]
For anyone new reading this ticket, I'll provide some more context on:

> `last_seen` should be strictly set when the transaction is seen in the mempool. If you set it superfluously you create db churn. Every change to it is added to the changeset and written to disk.

Our one and only `PersistenceBackend` implementation (`bdk_file_store`) is an append only flat file (hence, the db churn). There is no disastrous consequence if we have a `last_seen` for every transaction. However, it will be good to minimize data written.

**Comment by evanlinjin** [comment]
I didn't include `last_seen` with Esplora because of API limitations. Someone please prove me wrong!

**Comment by LLFourn** [comment]
@evanlinjin API limitations? I think you're just meant to get the `SystemTime::now`. That's what we do in the electrum example why can't the same thing work in esplora?

**Comment by evanlinjin** [comment]
> @evanlinjin API limitations? I think you're just meant to get the `SystemTime::now`. That's what we do in the electrum example why can't the same thing work in esplora?
> 

I forgot that's what we did. Does esplora return conflicting unconfirmed txs though? (For some reason I remember it did) If it does, the timestamp won't be helpful.

**Comment by LLFourn** [comment]
@evanlinjin I think it does. That's a good point but there's nothing we can do about that here. The `TxGraph` will resolve that.

**Comment by evanlinjin** [comment]
If it does, would it be useful to use System time to get the timestamp for last_seen?

**Comment by LLFourn** [comment]
It's better than it not having `last_seen` at all?

**Comment by evanlinjin** [comment]
> It's better than it not having `last_seen` at all?

How so? The last seen is only used for conflict resolution and with Esplora acting in this way, all unconfirmed transactions will have the same last seen.

**Comment by LLFourn** [comment]
It's informational. You can display this to the user in the app. It gives you an ordering on unconfirmed transactions. You can use it to tell when a tx was replaced (roughly).

**Comment by ValuedMammal** [comment]
@evanlinjin I'm curious what you mean by esplora returns conflicting unconfirmed txs. The approach to use `SystemTime::now` seems reasonable, although I recall someone made a related comment that system time wouldn't be available for no-std builds

**Comment by LLFourn** [comment]
> @evanlinjin I'm curious what you mean by esplora returns conflicting unconfirmed txs.

Esplora can return two transactions related to a spk that actually conflict with each other. The replaced one will eventually disappear but not atomically with the new one being added in this kind of query. At least that's how I remember it.
