### ISSUE TITLE
KeychainTxOutIndex method should behave consistently when non-existent keychains are passed in as arguments

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#1340]
Some KeychainTxOutIndex methods panic if a non-existent keychain is passed in as an argument. Some examples include:
- `unbounded_spk_iter`
- `next_index`

Instead, the methods that return an iterator simply return an empty one. Some examples are:
- `keychain_outpoints`
- `unused_keychain_spks`

I think we should be consistent, and either panic everywhere, or return a Result/Option everywhere. I personally don't like returning empty iterators, as the mistake of passing a non-existent keychain might be overlooked.

More discussion here: https://github.com/bitcoindevkit/bdk/pull/1203#discussion_r1474319073

**Comment by c0llinx** [comment]
Can I work on this? Although I will need some briefing

**Comment by LLFourn** [comment]
starting work on this will need to wait until #1203 is merged.

**Comment by notmandatory** [comment]
Looks like this was also fixed in #1203.
