### ISSUE TITLE
Update CI to prevent merging any prints to stdout 

### ISSUE THREAD

**Issue by stevenroose** [bitcoindevkit/bdk#1362]
```rust
                #[cfg(feature = "std")]
                debug_assert!({
                    println!("txid={} skip={}", txid, skip);
                    true
                });
```

this piece of code in tx_graph.rs prints out stuff when run in dev profile. That's pretty annoying tbh, I don't think it's uncommon for people to use CLIs in the dev profile and this messes up with stdout for these CLIs.

I reckon this has something to do with debugging, but I think there must be better ways to get these kinds of printouts without bothering users?

**Comment by LLFourn** [comment]
I think we should add to ci that:

```
rg 'dbg!|println!' -g '!*tests*' -g '!*examples*' -g '*.rs' crates
```

Should always show up clean

**Comment by ValuedMammal** [comment]
This might actually be fixed in #1194

**Comment by notmandatory** [comment]
Ya I did remove this `debug_assert!` in #1194 but if someone wants to remove it sooner in another PR that's fine by me.

**Comment by oleonardolima** [comment]
I tried a different approach on https://github.com/bitcoindevkit/bdk/pull/1425, using both `print_stdout` and `print_stderr` lints, instead of adding a new step on the CI, wdyt @LLFourn @notmandatory ?
