### ISSUE TITLE
absolute fee

### ISSUE THREAD

**Issue by ulrichard** [bitcoindevkit/bdk#137]
I need to be able to construct transactions with an absolute value for the fee. To come close, I could construct a tx, measure the size, and use some reverse calculation to approximate the FeeRate. But that might not be exact enough.
I am willing to implement this feature myself, and make a pull request. Which of the following directions should I go:
`wallet.create_tx(TxBuilder::with_recipients(vec![(address.script_pubkey(), satoshis)]).fee_rate(FeeRate::absolute(fee))`
or
`wallet.create_tx(TxBuilder::with_recipients(vec![(address.script_pubkey(), satoshis)]).fee_absolute(fee)`
I would opt for the latter.

**Comment by afilini** [comment]
Agreed, the latter also looks much better to me.

In `Wallet::create_tx()` and `Wallet::bump_fee()` you can set the `fee_rate` to 0.0 if an absolute fee is specified, and then set the `fee_amount` to the value you want.
