### ISSUE TITLE
Is `height` field name of `receive_output` function  misleading?

### ISSUE THREAD

**Issue by 15IITian** [bitcoindevkit/bdk#1376]
**Describe the enhancement**  
https://github.com/bitcoindevkit/bdk/blob/c01983d02aac6ee49c1bb34ade833e5d72bc8738/crates/bdk/tests/wallet.rs#L28

IMO ,Naming `ConfirmationTime` enum value as `height` is misleading-> 
 * https://github.com/bitcoindevkit/bdk/blob/c01983d02aac6ee49c1bb34ade833e5d72bc8738/crates/chain/src/chain_data.rs#L50
 *  `ConfirmationTime` can give  either `Unconfirmed` struct contaning `Timestamp` or `Confirmed` struct which consist of `Height` and `Time`  -> but the `Height` field name  gives first intuition that it would contain some value representing `height` of a block but doesn't.
 
**Use case**  
 * Brings more clarity to others regarding the function field name.

**Comment by notmandatory** [comment]
Hi, as I've mentioned before you should look for improvements that are more than superficial name changes. This issue in particular is a small name change for test code, so it does not even improve a public facing API. Please do not open up any more issues or PRs for minor documentation or name names like this that do not meaningfully improve the project.
