### ISSUE TITLE
Have more code conventions and guidelines

### ISSUE THREAD

**Issue by ValuedMammal** [bitcoindevkit/bdk#1394]
Using rustfmt means we always agree on code formatting. If rustfmt allows it, then matters of code style can be left to personal preference.

However we could benefit from defining more code conventions in `CONTRIBUTING.md` for the sake of consistency. Just some ideas:

- Forbid `unsafe` (or handle case by case)
- Use [StdExternalCrate](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#group_imports) style for grouping imports
- Return as much context as possible with errors
- Refer liberally to bitcoin BIPs and relevant historical context for a piece of code
- Follow rust API guidelines for [documentation](https://rust-lang.github.io/api-guidelines/documentation.html) and [naming](https://rust-lang.github.io/api-guidelines/naming.html)
- Name tests after the functional unit they're testing
- If using emoji, use them to their intended effect: [code-review-emoji-guide](https://github.com/erikthedeveloper/code-review-emoji-guide)

Approving changes:
- All comments resolved
- 2-ACK rule to merge

**Use case**  
Facilitates code review and improves readability of the codebase

**Additional context**
bitcoindevkit/bdk#1221 
https://github.com/bitcoindevkit/bdk/pull/1203#discussion_r1510453405

**Comment by notmandatory** [comment]
Great suggestions!

**Comment by ValuedMammal** [comment]
Provide a reason for ignoring tests. See bitcoindevkit/bdk_wallet#95

**Comment by oleonardolima** [comment]
Concept ACK, thanks for the suggestions!

**Comment by storopoli** [comment]
I really like this, I am totally on-board.
Can we discuss this in the next dev meeting? (PS: @ValuedMammal should go first since we almost never go alphabetical descending order)
Cc @nondiremanuel

**Comment by oleonardolima** [comment]
Adding another comment, I think we should try to enforce such conventions as much as possible on CI + GitHub features so we can set and forget, as by experience on fedimint if it's not enforced by CI it gets hard to maintain such conventions/rules, and on CI I mean even as a simple semgrep if it does the job.
