### ISSUE TITLE
Introduce `bdk_persist` crate

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1409]
**Describe the enhancement**  

Now that #1387 is merged, we should move the persistence structs/traits into a separate `bdk_persist` crate. This way, `bdk_chain` would not need to depend on `anyhow`. 

**Additional context**

https://github.com/bitcoindevkit/bdk/pull/1387#pullrequestreview-1972719664

**Comment by rustaceanrob** [comment]
@ValuedMammal and I are collaborating on this

**Comment by ValuedMammal** [comment]
If this touches `store.rs` again, it would be a good opportunity to remove any reference (I see at least 2) to "the tracker", which is a type that's no longer used.

My other question is whether it's necessary to bound the generic `C` by auto traits `Send + Sync` everywhere in the file_store. I'm inclined to only include a bound if not doing so would result in a compiler error. I recall @jirijakes made the point that enforcing `Send + Sync` on the wallet database was necessary to ensure the wallet remains threadsafe, but I don't see a similar concern in the case of Store. In other words, do we lose anything by not having `C: Send + Sync` ?
