### ISSUE TITLE
need custom lookahead

### ISSUE THREAD

**Issue by arronzhang** [bitcoindevkit/bdk#1410]
I generated 100 btc addresses and transferred. It was found that only the first 25 could be signed. It is should be restricted by DEFAULT_LOOKAHEAD, and no configurable code was found. Is there any other way?

**Comment by arronzhang** [comment]
We can create the address by `AddressIndex::New` first to fix it.
```Rust
for _ in 0..100 {
        wallet.try_get_address(AddressIndex::New)?;
    }
```

**Comment by LLFourn** [comment]
I think #1250 will allow you to configure `DEFAULT_LOOKAHEAD`
