### ISSUE TITLE
Upgrade rust-bitcoin to 0.32

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1422]
**Describe the enhancement**  

The LDK team would like to use `rust-bitcoin` version 0.32 so BDK should update too. To do so we also need to update the following crates to the versions that depend on `rust-bitcoin` 0.32:

- [x] [rust-miniscript](https://github.com/rust-bitcoin/rust-miniscript)
- [x] [rust-bitcoincore-rpc](https://github.com/rust-bitcoin/rust-bitcoincore-rpc)
- [x] [bitcoind](https://github.com/rust-bitcoin/bitcoind)
- [x] [electrsd](https://github.com/rcasatta/electrsd)
- [x] [rust-electrum-client](https://github.com/bitcoindevkit/rust-electrum-client)
- [x] [rust-esplora-client](https://github.com/bitcoindevkit/rust-esplora-client)
- [x] [rust-hwi](https://github.com/bitcoindevkit/rust-hwi)

**Use case**  

Updating to `rust-bitcoin` 0.32 removes the need for a specific `no-std` feature, it will be implied by not enabling the `std` feature. It also includes a new io crate.

**Additional context**

https://discord.com/channels/753336465005608961/753367451319926827/1228314439133171795

**Comment by oleonardolima** [comment]
I'm willing to give a try on this one.

**Comment by notmandatory** [comment]
Thanks @oleonardolima you'll need to keep an eye to see when rust-miniscript and rust-bitcoincore-rpc are ready. Feel free to start making PRs for any of the crate that only need rust-bitcoin updated to 0.32.

**Comment by notmandatory** [comment]
Another thing this PR should fix is the broken docs.rs for `bdk_persist`. I think they're breaking because it doesn't build with `default` features.

https://docs.rs/crate/bdk_persist/0.1.0/builds/1208655

**Comment by oleonardolima** [comment]
> Thanks `@oleonardolima` you'll need to keep an eye to see when rust-miniscript and rust-bitcoincore-rpc are ready. Feel free to start making PRs for any of the crate that only need rust-bitcoin updated to 0.32.

Sure, I'll keep an eye and initially start from other crates.

> Another thing this PR should fix is the broken docs.rs for `bdk_persist`. I think they're breaking because it doesn't build with `default` features.
> 
> https://docs.rs/crate/bdk_persist/0.1.0/builds/1208655

Cool, I'll check if it solves the docs once the PR is done.

**Comment by ValuedMammal** [comment]
@notmandatory Would #1423 fix the docs.rs fail? - Oh I see you mentioned it wouldn't be needed after the rust-bitcoin upgrade. Still maybe a quick fix in the interim

**Comment by ValuedMammal** [comment]
I forgot to mention there was a suggestion https://github.com/bitcoindevkit/bdk/pull/1412#discussion_r1582685111 for a better crate description for `bdk_persist` that maybe we can fix when the opportunity arises.

**Comment by oleonardolima** [comment]
**update:** Some of the rust-bitcoin crates have been released, and the `rust-electrum-client`, and `electrsd` are ready to review (depends on each other).

- [x] [rust-miniscript](https://github.com/rust-bitcoin/rust-miniscript)
- [x] [rust-bitcoincore-rpc](https://github.com/rust-bitcoin/rust-bitcoincore-rpc)
- [x] [bitcoind](https://github.com/rust-bitcoin/bitcoind)
- [x] [electrsd](https://github.com/RCasatta/electrsd) https://github.com/RCasatta/electrsd/pull/80
- [x] [rust-electrum-client](https://github.com/bitcoindevkit/rust-electrum-client) https://github.com/bitcoindevkit/rust-electrum-client/pull/133
- [x] [rust-esplora-client](https://github.com/bitcoindevkit/rust-esplora-client) https://github.com/bitcoindevkit/rust-esplora-client/pull/85
- [x] [rust-hwi](https://github.com/bitcoindevkit/rust-hwi) https://github.com/bitcoindevkit/rust-hwi/pull/99
- [x] [bdk](https://github.com/bitcoindevkit/bdk) https://github.com/bitcoindevkit/bdk/pull/1448

EDIT: habemus `rust-miniscript` 🥳

**Comment by oleonardolima** [comment]
**NOTE:** it's not done yet, only consider it done after #1448, mistakenly marked as completed probably because my comment `partially fixes ...` at other PR 😅

**Comment by notmandatory** [comment]
@oleonardolima I published the 0.9.0 `rust-hwi` crate, thanks for keeping on it! 🎉 https://crates.io/crates/hwi
