### ISSUE TITLE
Help spending a tr aggregated key using musig2

### ISSUE THREAD

**Issue by 0x330a** [bitcoindevkit/bdk#1436]
Hey I've been trying to work out the APIs to get a single taproot key address from an aggregated key, starting off without any tweaks or fancy taptree things and signing a specific transaction in an external process using musig2. As I currently understand the aggregated public key should be fine to use as a taproot key and the sighash should be for spending the inputs from that key to do the aggregated signatures. I think either my initial descriptor:
```rust
    let key_agg = aggregate_sec(sec_keys);
    let btc = bdk::bitcoin::PublicKey::from(key_agg.aggregated_pubkey_untweaked::<secp256k1::PublicKey>());

    let descriptor = bdk::descriptor! {
        tr(btc)
    }.unwrap();

    Wallet::new_no_persist(
        descriptor,
        None,
        Network::Testnet,
    ).expect("no wallet creation")
```

or my creation / signing message bytes is incorrect?
```rust
    let mut psbt = {
        let mut tx = wallet.build_tx();
        tx.drain_wallet()
            .drain_to(addr.script_pubkey())
            .sighash(PsbtSighashType::from(TapSighashType::Default))
            .fee_absolute(3000);
        tx.finish().unwrap()
    };

    psbt.inputs.iter_mut().enumerate().for_each(|(idx,input)| {
        // addr.script_pubkey() should just be OP_PUSHNUM_1 OP_PUSHBYTES_32 <internal key>
        input.witness_script = Some(addr.script_pubkey());
    });

    let funding: Vec<&TxOut> = psbt.iter_funding_utxos().map(|t| t.unwrap()).collect();

    let unsigned = &psbt.unsigned_tx;
    let mut sighash_cache = SighashCache::new(&psbt.unsigned_tx);

    // only have 1 input and prev out is 0 index for input to our addr
    let sig_hash = sighash_cache.taproot_signature_hash(0,  &Prevouts::All(&funding), None, None, TapSighashType::Default).unwrap();

    /* signing process of sig_hash.as_byte_array().as_slice() */

    // this part maybe ??
    psbt.inputs.iter_mut().enumerate().for_each(|(idx,input)| {
        // let mut witness = Witness::new();
        // witness.push(&final_sig);
        // or?
        input.tap_key_sig = Some(taproot::Signature::from_slice(final_sig.as_slice()).unwrap());
    });
```

Is there anyone who has a good idea about how this should all fit together or maybe what I'm doing wrong if someone is more familiar than me. I'm currently just getting invalid schnorr signature which makes me think it's either the bytes I'm signing are incorrect or maybe it's transforming the address I'm using in the initial descriptor / wallet creation code possibly. Maybe a finalize or something else is needed idk

**Comment by storopoli** [comment]
I don't fully understand the workflow, but the idea behind key aggr in Taproot is that if you add private keys (SK), public keys (PK), or signatures (sig); you get a valid aggregation.

That means that the if you sign the same message with SK_1, then the same message with with SK_2; and you combine both sigs, it is a valid signature for the combined SK = SK_1 + SK_2.

The way you sign PSBTs in BDK is by using the [`wallet.sign`](https://docs.rs/bdk/1.0.0-alpha.10/bdk/wallet/struct.Wallet.html#method.sign) function,
like in

https://github.com/bitcoindevkit/bdk/blob/fb7ff298a4bb6254e6d847dbda8bd604552e527e/example-crates/wallet_electrum/src/main.rs#L101C5-L101C6

However you might need to manually change the sigs inside the [`Psbt`](https://docs.rs/bitcoin/0.31.2/bitcoin/psbt/struct.Psbt.html) with some [`Secp256k1`](https://docs.rs/bitcoin/0.31.2/bitcoin/key/struct.Secp256k1.html) operations/primitives.

I haven't seen an example of this kind of workflow or haven't had the opportunity to do something similar yet.

**Comment by 0x330a** [comment]
I think I've solved this now, it might have been with an issue in the musig2 library I was using to build an aggregated public key. Essentially the goal was to use BDK just to create a watch only address as well as an unsigned btc transaction which is then signed externally in this musig2 crate. The solution that *seemed* to work was to build the public key as a `KeyAggContext` (this is all a completely different library so just posting here in case anyone is interested) modified with `with_unspendable_taproot_tweak()` which basically just outputs a public key I'm using in the `descriptor!{ tr(pk) }` for bdk's watch only wallet. It seems to internally be tweaking that aggregated key with `t = int(H_taptweak(xbytes(P), k))` and some kind of provable lack of merkle tree or something? I'm not too sure but at the end of the day the transaction was confirmed so maybe that was the only issue. I didn't change anything except signing the sighash from the `sighash_cache.taproot_signature_hash()` function and setting that as the only parameter in the final witness.

**Comment by rustaceanrob** [comment]
Hey I know this is closed now, but the topic of provably unspendable tweaks is interesting and worth understanding. This blog by Elle Mouton is great, it has to do with taproot channels, but these are facilitated by MuSig2: https://ellemouton.com/posts/taproot-chan-txs/

**Comment by 0x330a** [comment]
this is very useful @rustaceanrob thanks, I'm running back into issues after refactoring so I might be able to just start from somewhere again :joy:

**Comment by 0x330a** [comment]
for anyone who happens across this same issue, turns out that the aggregate context for all **signing** should use the unspendable tweak, *HOWEVER*, the actual **address derivation** should use the regular aggregated pubkey from all pubkeys internally

**Comment by storopoli** [comment]
@0x330a how did you manage the `PubNonces`? Did you just inserted in the `Psbt`?

**Comment by 0x330a** [comment]
> @0x330a how did you manage the `PubNonces`? Did you just inserted in the `Psbt`?

@storopoli I just managed everything musig2 separately to bdk, from the bdk side using only the group key as a Taproot key in mini script wallet generation to get wallet info and build psbts then with the sighashes per input index I used those as the messages to sign and did the signing process externally with a serialized psbt and list of sughashes to sign before re-assembling that and iterating through all the inputs and setting the witness to those aggregated signatures before submitting it
