### ISSUE TITLE
Examples don't show how to properly initialize a IndexedTxGraph etc from disk

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#1462]
See example_esplora, example_electrum and example_bitcoind_rpc_polling

- for some reasons each of these independently apply the initial changeset to the graph (why can't it just be done inside `example_cli::init`).
- The initialization is a bit of a mess where the examples insert the descriptors but don't persist them. Are we doing this intentionally? It's an interesting feature that you can actually change the descriptors in the example and not have to delete the database. If we are doing this intentionally then we should explain this.

I think with the example cli we should have an init command which takes in the descriptor assignments and persists them. It would be great if it could also generate a random bip86 descriptor too. Then future calls should require the db has been initialized -- no more environment variables.

+ can we run the cli examples in CI against a regtest node somehow?

**Comment by ValuedMammal** [comment]
@notmandatory This is mostly complete except for
> - can we run the cli examples in CI against a regtest node somehow?

therefore probably not critical to have for beta but worth keeping open.

**Comment by notmandatory** [comment]
@ValuedMammal I agree running against a regtest node would be great but not essential for the 1.0.0-beta milestone, should be in a new issue so we can close this.

**Comment by ValuedMammal** [comment]
Fixed by #1495, but I'll open an issue to carry over the remaining tasks #1618
