### ISSUE TITLE
Remove nursery/tmp_plan

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1469]
The planning module has been added to `rust-miniscript` so this crate is no longer needed.

https://docs.rs/miniscript/latest/miniscript/plan/index.html

**Comment by notmandatory** [comment]
❓ Should the whole nursery folder be removed since in-development work can be done in a fork/feature_branch ?

**Comment by LLFourn** [comment]
Sure just get the examples to work without it?

**Comment by ValuedMammal** [comment]
I'm working on this
