### ISSUE TITLE
Move change creation/addition inside `CoinSelectionAlgorithm`

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/bdk#147]
See https://github.com/bitcoindevkit/bdk/issues/121#issuecomment-716723002 for why that would be preferred.

We could simply tell the coin selection algorithm how much the change output costs in terms of weight units, and then we would get back a boolean from the coin selection that tells the wallet whether it should actually add the change or not.

**Comment by danielabrozzoni** [comment]
Also, this is needed for correctly implementing the waste metric, as you need to know if you're going to create the change or not in order to calculate the `creation_cost` (see https://bitcoincore.reviews/22009 for a better explanation of the waste metric)
