### ISSUE TITLE
Add back finish() and sort_tx() with rand if std enabled  

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1479]
>  I was going to make a separate PR to introduce a feature flag to bring back `finish` as a method to build transactions, but that was mostly for user convenience and shouldn't be covered here.

_Originally posted by @rustaceanrob in https://github.com/bitcoindevkit/bdk/issues/1395#issuecomment-2104312995_

**Comment by ValuedMammal** [comment]
I guess we could also add back `GeneratableKey::generate` that uses `thread_rng()` behind the `rand-std` feature

**Comment by rustaceanrob** [comment]
Yeah I was unaware that `thread_rng` satisfies `CryptoRng`. I think we should add it back.

**Comment by storopoli** [comment]
> Yeah I was unaware that `thread_rng` satisfies `CryptoRng`. I think we should add it back.

`ThreadRng` uses the same PRNG as [`StdRng`](https://docs.rs/rand/latest/rand/rngs/struct.StdRng.html) for security and performance and is automatically seeded from [`OsRng`](https://docs.rs/rand/latest/rand/rngs/struct.OsRng.html).

Ref: https://docs.rs/rand/latest/rand/rngs/struct.ThreadRng.html

`OsRng` is very robust, we should rely on that.

PS: If you want a very good crash-course into entropy and randomness in computers check Chapter 8 of https://www.manning.com/books/real-world-cryptography

**Comment by ValuedMammal** [comment]
Do we also plan to get rid of `Bip69Lexicographic` ordering variant?

**Comment by evanlinjin** [comment]
We can consider having associated methods take in a closure which shuffles index order.

**Comment by notmandatory** [comment]
Fixed in #1395
