### ISSUE TITLE
`DescriptorId` is not unique enough

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1483]
**Describe the bug**  

As mentioned on [`Discord#development`](https://discord.com/channels/753336465005608961/753367451319926827/1253198896897724446), there is a fundamental problem with how we define a `DescriptorId`. Currently `DescriptorId` does not uniquely identify a descriptor. I.e. we can change how the xpub is portrayed and it would completely change the `DescriptorId`. This is a problem because the whole point of `DescriptorId` is so that the last derivation index is stored with something that uniquely represents a descriptor.

**Proposed Solutions**

An idea (first mentioned to me by @LLFourn) is to use the hash of the first derived spk for the `DescriptorId`. We can consider disallowing non-wildcard descriptors in `KeychainTxOutIndex` (as they aren't keychains) and it allows us full uniqueness for `DescriptorId`s.

**Comment by notmandatory** [comment]
I like the proposal to use a hash of the descriptor's first derived SPK as the unique descriptor Id.

I don't know if anyone needs non-wildcard descriptors, but it feels like a regression to not allow them.  What if we don't mix wildcard and non-wildcard keychains in the same `KeychainTxOutIndex`?

**Comment by notmandatory** [comment]
Since this is an edge case and doesn't affect the external API can I move this to the `beta` milestone? We can put a caveat in the beta release notes that this is a known issue.  Or we can partially fix this by using the first SPK for each keychain, but document the open issue that using wildcard and non-wildcard descriptors that overlap are not supported.

**Comment by notmandatory** [comment]
@evanlinjin I tried implementing your proposed solution in #1486, let me know what you think. We shouldn't have to disallow non-wildcard xkeys as long as we clearly document that the user must ensure they have unique parent keys or derivation indexes other than the last index.
