### ISSUE TITLE
Remove `keychain::ChangeSet::keychains_added` and add this to `bdk_wallet::ChangeSet`

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1498]
Sub-task for #1103

**Comment by gnapoli23** [comment]
@notmandatory Can I pick this one? It should be just a refactor right? If ok I would go for it.

**Comment by notmandatory** [comment]
@gnapoli23 thanks for offering to pitch in on this, I need to check with @evanlinjin and make sure he's not doing this in the PR he's working on.

**Comment by gnapoli23** [comment]
All right, ok please let me know @notmandatory . Thanks.

**Comment by evanlinjin** [comment]
Sorry I'm already working on this.
