### ISSUE TITLE
Simplify `public_descriptor` by using `get_descriptor` and remove redundant API function.

### ISSUE THREAD

**Issue by KnowWhoami** [bitcoindevkit/bdk#1501]
**Describe the enhancement**  
* The `public_descriptor` function returns a reference to an `ExtendedDescriptor`, similar to `get_descriptor` on `KeychainTxOutIndex`, which returns an `Option<Descriptor<DescriptorPublicKey>>`

https://github.com/bitcoindevkit/bdk/blob/a112b4d97c02c3acb9728c55c6c150560b5cc0b7/crates/wallet/src/wallet/mod.rs#L1770

https://github.com/bitcoindevkit/bdk/blob/a112b4d97c02c3acb9728c55c6c150560b5cc0b7/crates/chain/src/keychain/txout_index.rs#L407

   Currently, `public_descriptor` finds the descriptor from scratch. Instead, it can directly call `get_descriptor `  to simplify its implementation.

  ``` rust
       pub fn public_descriptor(..) -> &ExtendedDescriptor {
       match self.indexed_graph.index.get_descriptor {
          // implementation
        }
       }
 ```

* Additionally, the `get_descriptor_for_keychain` function is essentially a wrapper around `public_descriptor`:

https://github.com/bitcoindevkit/bdk/blob/a112b4d97c02c3acb9728c55c6c150560b5cc0b7/crates/wallet/src/wallet/mod.rs#L1882.

 Both functions logically serve the same purpose:

   `public_descriptor`: Returns the public version of the descriptor.
   `get_descriptor_for_keychain`: Returns the descriptor used to create addresses for a specific keychain

  Therefore, we can eliminate `get_descriptor_for_keychain` and include its documentation in `public_descriptor`. 
  This   change will reduce redundancy in Wallet API's.

**Use case**  
  * Reduce redundancy in the API.
  * Simplify the implementation of public_descriptor.

**Comment by f3r10** [comment]
Hello, could I take this issue?

**Comment by notmandatory** [comment]
@f3r10 we already have a PR from @gnapoli23, feel free to add a PR review for #1503.

**Comment by gnapoli23** [comment]
Done. @notmandatory
