### ISSUE TITLE
Consider making the CI run `cargo test` instead of `cargo check`

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/bdk#151]
It looks like most of the jobs are not actually running the tests but only "checking" the code. I would consider running the tests, I have just ran into a problem with the `all-keys` feature that I would have expected the CI to find..

**Comment by notmandatory** [comment]
I'll take a look, I think I just copied the prior Travis behavior, but if I can run tests on all the features I'll do that.

**Comment by afilini** [comment]
Yeah sorry, didn't wanna blame this on you. I'm pretty sure Travis was doing the same thing, I just realized now that it might not be the best idea

**Comment by notmandatory** [comment]
No worries ! I knew this needed to be fixed at some point and it's a good reminder to get it done now.
