### ISSUE TITLE
Move `bdk_hwi` to `hwi` module

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1516]
**Describe the enhancement**  

We should move `bdk_hwi` from the `bdk` repo crates and include it with to the `hwi` crate. 

**Use case**  

Removing `bdk_hwi` will simplify the `bdk` workspace and ci testing because we won't need to use pyo3.

**Additional context**

If we determine no one is using the `hwi` module we can more easily deprecate both `hwi` and `bdk_hwi` when they're together in the same crate. But also they will be together in case someone does want to use and maintain them.

**Comment by oleonardolima** [comment]
I can take this cleanup if nobody has already.

**Comment by oleonardolima** [comment]
For future reference: https://github.com/wizardsardine/async-hwi.

If it becomes the standard for the ecosystem, or maybe a new one from rust-bitcoin, we can get deprecate and get rid of `rust-hwi` without much problem, referring users towards `async-hwi`.
