### ISSUE TITLE
Support sortedmulti descriptor expression

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#155]
Once `sortedmulti` is supported by the `rust-miniscript` lib then `bdk` should be updated to support it also. The related `rust-miniscript` issue is https://github.com/rust-bitcoin/rust-miniscript/issues/164.

**Comment by justinmoon** [comment]
I've got a PR up to address this: https://github.com/rust-bitcoin/rust-miniscript/pull/171

**Comment by justinmoon** [comment]
PR was merged. Now we just need rust-miniscript to roll a new release.

**Comment by afilini** [comment]
Fixed in #167
