### ISSUE TITLE
Should `bdk_electrum` `sync`/`full_scan` set `last_seen`?

### ISSUE THREAD

**Issue by LagginTimes** [bitcoindevkit/bdk#1550]
Getting a balance from `TxGraph` will not return a balance for unconfirmed transactions immediately after `sync`/`full_scan` with `bdk_electrum`. This is because the `last_seen` for these transactions is missing, and has to be set separately from `sync`/`full_scan` with `TxGraph::update_last_seen_unconfirmed`. Would it make sense to set the `last_seen` for unconfirmed transactions during the `sync`/`full_scan` process?

**Comment by ValuedMammal** [comment]
Yeah we could have something like `time_of_sync` be a member of `SyncRequest` for example.

**Comment by evanlinjin** [comment]
> Yeah we could have something like `time_of_sync` be a member of `SyncRequest` for example.

I think that's a great idea.

@LagginTimes thoughts?

**Comment by notmandatory** [comment]
This looks like the kind of issue we should try to fix in the beta to prevent users from running into it. The fix proposed by @ValuedMammal sounds relatively painless.

**Comment by notmandatory** [comment]
Also @ValuedMammal mentioned in the call today that we need to be careful not to call functions like `std::time` internally and break the `no-std` (and WASM) compatibility.  Passing `time_of_sync` in with the sync/full_scan request should also work with `no-std` apps.
