### ISSUE TITLE
Update to rust-bitcoin 1.0.0

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1574]
The `rust-bitcoin` project is re-versioning 0.32 to 1.0 and we should use that in our beta release. TBD on what the new `rust-miniscript` version will be. 

See: https://github.com/rust-bitcoin/rust-bitcoin/pull/3241

**Comment by notmandatory** [comment]
cc: @thunderbiscuit @reez @tnull 

Should update the `rust-bitcoin-ffi` to `rust-bitcoin` 1.0 also.

**Comment by reez** [comment]
> cc: @thunderbiscuit @reez @tnull
> 
> Should update the `rust-bitcoin-ffi` to `rust-bitcoin` 1.0 also.

Thanks for the heads up on this, cool to see that’s the direction they’re headed!

**Comment by Kixunil** [comment]
We're not, that's just a proposal and it would create a bunch of work for you and your users with the only value being that a number changed. See my comment at the PR.

**Comment by notmandatory** [comment]
Ok sorry this was a false alarm. Looks like `rust-bitcoin` will stick with the `0.32.x` versioning which we are already using for BDK 1.0.  When a `rust-bitcoin` 1.0 is released it will be a good milestone to update to it and bump BDK to 2.0.

**Comment by tnull** [comment]
> Ok sorry this was a false alarm. Looks like `rust-bitcoin` will stick with the `0.32.x` versioning which we are already using for BDK 1.0.  When a `rust-bitcoin` 1.0 is released it will be a good milestone to update to it and bump BDK to 2.0.

The Nashville agreement prevails :)
