### ISSUE TITLE
Move stuff from `crates/chain/tests/common` to `bdk_testenv` and make them publicly-accessible

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1602]
**Describe the enhancement**  

These macros, fake-tx-construction-tools are helpful in other crates too. Let's move them to `bdk_testenv` and make them publicly available. 

**Use case**  

Better test tooling.

**Comment by tvpeter** [comment]
@evanlinjin I would like to work on this issue.

**Comment by evanlinjin** [comment]
@tvpeter all yours!

**Comment by tvpeter** [comment]
@evanlinjin, can you please review the PR [here](https://github.com/bitcoindevkit/bdk/pull/1612#issue-2526619373). I can't tag you there because the workflows require approval from a maintainer. 

Thank you.
