### ISSUE TITLE
Remove unneeded `Wallet` functions

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1622]
As we were reviewing which `Wallet` functions to expose in the language bindings we found some functions that likely aren't needed by `Wallet` users. I'll use this issue to list which ones I don't think are needed or can be called directly on `LocalChain`. Comment below if you have any other suggestions. 

I'd like to remove any unneeded ones now before we have a final 1.0 API.

**Comment by ValuedMammal** [comment]
I had another look at the API docs. Originally I thought `get_psbt_input` shouldn't be public but I don't really see a problem with it. We could possibly try to streamline the "stage" API - right now we have `staged`, `take_staged`, and `staged_mut` all with slightly different semantics.

Some other ideas for better organization are to reintroduce a unit test module for testing non public wallet functions, and consider making the common test utils available through a public `test_util` module.

**Comment by notmandatory** [comment]
fixed by #1658
