### ISSUE TITLE
`bdk_testenv` docs are not building on docs.rs

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1627]
**Describe the bug**  

https://docs.rs/bdk_testenv

In docs.rs sandboxed build environment, network access is blocked.

**Comment by riverKanies** [comment]
pr for potential fix https://github.com/bitcoindevkit/bdk/pull/1679

**Comment by notmandatory** [comment]
Fixed by #1722

**Comment by riverKanies** [comment]
> Fixed by #1722

@notmandatory  this won't be confirmed until docs.rs rebuilds bdk. Looks like that won't happen automatically until a new release, but looks like we can create an issue to request a rebuild https://github.com/rust-lang/docs.rs/issues/new?template=crate-build-failure.yaml

**Comment by notmandatory** [comment]
We'll verify this solved the problem with the upcoming 1.0.0-beta.6, if it doesn't fix it for some reason we'll re-open this issue and fix it in a 1.0.1 patch release.
