### ISSUE TITLE
The last version on crate.io is 1.0.0-alpha.11, released 4 month ago, is there a release plan for future versions?

### ISSUE THREAD

**Issue by jjyr** [bitcoindevkit/bdk#1631]
The last release on crate.io is [1.0.0-alpha.11](https://crates.io/crates/bdk/1.0.0-alpha.11)

Is there a release plan for future versions on crates.io?

**Comment by MaxFangX** [comment]
For anyone else who was confused, this is because the `bdk` crate was renamed to `bdk_wallet`. 

[docs.rs](https://docs.rs/bdk_wallet)
