### ISSUE TITLE
Is it supposed that BDK doesn't remember txs after signing and only adds them after seeing them in the mempool?

### ISSUE THREAD

**Issue by stevenroose** [bitcoindevkit/bdk#1633]
This sounds like a bug to me, but it could be intended behavior.

I am making and signing a tx, then another and bdk re-uses the same input utxos. It gets solved when I run a sync in between, presumably because it learns from its own transaction from the mempool.

Is the supposed correct way to do this to use the `insert_tx` method to "save" the tx ourselves manually?

**Comment by luisschwab** [comment]
I believe so, since `insert_tx` updates the local graph and marks these coins as spent, although this transaction won't be cannonical: 
    
>/// By default the inserted `tx` won't be considered "canonical" because it's not known
>/// whether the transaction exists in the best chain. To know whether it exists, the tx
>/// must be broadcast to the network and the wallet synced via a chain source.

**Comment by notmandatory** [comment]
Yes, @luisschwab is correct that you must use `insert_tx` to insert any tx into your wallet after it is created if you want it to count towards your wallet history and balance without broadcasting and syncing to the blockchain.

**Comment by tnull** [comment]
Mhh, IIUC, `insert_tx` would also solve https://github.com/bitcoindevkit/bdk_wallet/issues/166 then?

Or are there any further concerns? Will the inserted tx be persisted via `ChangeSet`s, or will it be lost across restarts? 
And what happens if the inserted tx won't make it into the chain? Do we somehow need to manually remove it again to unlock the UTXOs?

**Comment by thunderbiscuit** [comment]
This is the sort of thing that would be a great addition to the book of bdk. I'm opening issue here: bitcoindevkit/book-of-bdk#49

Anyone should feel free to claim it if they feel so inclined!

**Comment by stevenroose** [comment]
Perfect. I would personally also suggest adding this in a code comment on the built_tx or maybe better sign methods on the Wallet api.

**Comment by ValuedMammal** [comment]
@stevenroose Good question

> Is it supposed that BDK doesn't remember txs after signing and only adds them after seeing them in the mempool?

Yes this is the way things are designed currently.

> you must use insert_tx to insert any tx into your wallet after it is created if you want it to count towards your wallet history and balance without broadcasting

A bit of nuance that is missing is whether the tx is given a "last seen" timestamp which happens naturally for transactions that are seen in the mempool but is not the case when using `insert_tx` on its own.

You can imagine a problem where you create several transactions but don't broadcast them. If the wallet immediately remembered all of them, it would be inconvenient for them to reflect in your final balance before they are known to exist on chain. Granted that could also be a limitation of the `Balance` type in the sense that you can't just "roll back" a pending balance using something like `cancel_tx`. In that case the only way to undo the effect of a previously inserted transaction is to broadcast a conflicting one (but then where are you getting the inputs if they are already marked spent).

Regarding the reuse of utxos there are a few ways around it
- You can mark certain outpoints `unspendable` using TxBuilder or tell the builder explicitly which ones to spend
- If you know for sure that you intend to broadcast, you can do `insert_tx` and then manually mark it seen, see [test_insert_tx_balance_and_utxos](https://github.com/bitcoindevkit/bdk/blob/5c8cfcc8b53cffd8afacb0a26676b45e9bb18ea1/crates/wallet/tests/wallet.rs#L4219) but this is decidedly a hack and sounds risky for the reasons I just mentioned
- There are also some ideas related to utxo locking over on issue bitcoindevkit/bdk_wallet#166

I agree it will valuable to have a demonstration of the "multiple unbroadcast txs" workflow. There are probably different scenarios to consider such as when they all try to spend the same inputs or if they make up a package where each one depends on the previous. If you decide that the Wallet is a good place to store unbroadcast txs, then yes you will need to persist the changes as well, but then the question becomes what information is used to later find the ones you care about (txid, address, etc) and where is that info kept?
