### ISSUE TITLE
SyncResult should not have "Result" in the name

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#1647]
A "Result" type in rust is conventionally always meant to be a enum with an error variant. 

This should be called `SyncResponse` since it is what you get after sending a `SyncRequest`.

The present name should be deprecated and type alias to `SyncRequest`.

**Comment by notmandatory** [comment]
This is only a low-risk rename so I'd like to get it in with 1.0 rather than creating the type alias.
