### ISSUE TITLE
Performance issue with `get_chain_position` and associated methods for unconfirmed transactions

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1665]
**Describe the bug**  

`get_chain_position` for unconfirmed transactions is very inefficient if we have "nested conflicts". Since unconfirmed transactions that spend from evicted transactions are also evicted, we need to iterate over and check all unconfirmed descendants.

This problem is exacerbated in `list_canonical_txs`, `filter_chain_txouts`, etc. as these methods call `get_chain_position` for each transaction.

Worst case is `O(n^2)` for building the canonical tx history.

**Proposed Solution**  

Let's pass an `evicted_txs: &mut HashSet<Txid>` input to `get_chain_position` which takes record of any tx that is deemed to be evicted from the canonical history. Note that descendants of evicted transactions are also evicted and should be included in `evicted_txs`. The logic to fill `evicted_txs` can stop when we insert an already-existing `txid` (since descendants of that `txid` will already be included in `evicted_txs`).

`list_canonical_txs`, `filter_chain_txouts`, etc. methods will construct an `evicted_txs` hashset which is passed to each internal call to `try_get_chain_position`.

**Comment by evanlinjin** [comment]
@LagginTimes this one is for you.

**Comment by LLFourn** [comment]
ConceptNACK. I don't think we should change the API of `get_chain_position`. The problem is that the other batch methods should not be calling `get_chain_position` at all but rather implement a fast batch canonicalization algorithm.

**Comment by evanlinjin** [comment]
@LLFourn and myself have discussed solutions for this in person and have come to consensus on the direction to move forwards with this.

In summary, we want to traverse backwards from transactions starting with latest `last_seen`s, and fill up txid sets; `must_be_canonical` and `must_not_be_canonical`. An unconfirmed sub-graph with the highest last-seen is considered canonical if it does not conflict with confirmed transactions. Descendants of non-canonical txs are also non-canonical. Ancestors of canonical txs are automatically canonical.
