### ISSUE TITLE
wallet: Don't call `get_chain_position` redundantly

### ISSUE THREAD

**Issue by ValuedMammal** [bitcoindevkit/bdk#1677]
`chain_position` is a field of `LocalOutput`, so shouldn't this just get the chain position of the utxo rather than call `get_chain_position` again?

https://github.com/bitcoindevkit/bdk/blob/dc0511fcaba0a94e127ca52560e5f10bf18edff9/crates/wallet/src/wallet/mod.rs#L2061-L2068

**Comment by jirijakes** [comment]
#1670 refactors this part, the task may not be needed anymore if it gets merged.

**Comment by notmandatory** [comment]
@jirijakes thanks for taking a l look at this and identifying that it's being fixed in #1670.

**Comment by notmandatory** [comment]
Fixed in #1670
