### ISSUE TITLE
How to generate a wallet from a vpub key?

### ISSUE THREAD

**Issue by f-squirrel** [bitcoindevkit/bdk#1678]
Hi folks,

Thank you for a great crate!

I am using v0.29.0 since v1 is still in beta.
How can I generate a wallet using a vpub key?

I tried the basic example:

```rust
    let wallet = Wallet::new(
        "wpkh([c258d2e4/84h/1h/0h]vpub5YnDu2Ju3dZ3bN6dsbsUNTyXsyCFq297s9BZ5amqKL2GTjDbDZZwft4HM2sJAD55EhXbvVPvccNoVWNYN74tfkaUxpGbs8PXhvFXQmgCrAA/0/*)",
        None,
        Network::Testnet,
        MemoryDatabase::default(),
    ).unwrap();
```
It returns `Descriptor(Miniscript(Unexpected("unexpected «Error while parsing xkey.»")))`.

What do I do wrong?
Another question: Is it possible to get balances per address instead of the total?

**Comment by apoelstra** [comment]
Descriptors are not compatible with vpubs because they supercede them. (What would you expect to happen if you used a vpub in a non-`wpkh` descriptor?)

You'll need to reencode as an xpub first.

**Comment by f-squirrel** [comment]
@apoelstra thank you for the prompt reply.
I have a few follow-up questions:

- Is there a way to re-encode the key using `bdk`? If yes, is there an example?
- If I re-encode the key, will I receive different addresses? For example, if I want to generate addresses from the `vpub`?

**Comment by apoelstra** [comment]
> * Is there a way to re-encode the key using `bdk`? If yes, is there an example?

Not that I know of -- to do this you want to base58-decode the string, change the first four bytes (which are magic bytes that produce `xpub`/`vpub`/etc when encoded) then re-encode. I think there is a bip84 crate somewhere and maybe it can do this?

In general this is a bit dangerous because if you turn a vpub into an xpub it can then be used in any descriptor, but presumably the wallet that made the key is only expecting to handle wpkh.

The right way to go about this is to find whatever wallet produced the vpub and convince it to make an xpub instead. The second-most-right way is to convert the bare vpub to a wpkh descriptor (as you're trying to do). But this would be the job of a bip84 crate, not bdk.

> * If I re-encode the key, will I receive different addresses? For example, if I want to generate addresses from the `vpub`?

Nope, they'll be the same. Though you should double-check of course to make sure you did the conversion right.

**Comment by f-squirrel** [comment]
@apoelstra , thank you again for a quick reply.

I did the following:

```rust
fn convert_vpub_to_tpub(vpub_key: &str) -> String {
    let mut decoded = base58::decode(vpub_key).expect("Failed to decode base58 key");
    decoded[0..4].copy_from_slice(&[0x04, 0x35, 0x87, 0xCF]);
    base58::encode(&decoded)
}
```
The output is `tpubDCpP2bUR4GbTZkfizWRozZVuZ2aohedBEzpHzvckRFXvKDWko6kA4T3PdUsFgXL9qtJ8326v52uwxG6HCMkA9fPym6QkiUgjqKyDwwSvDtA`.

I reimplemented this implementation: https://github.com/jlopp/xpub-converter/blob/master/js/xpubConvert.js.
The actual online tool can be found [here](https://jlopp.github.io/xpub-converter/).
It was mentioned at the [SO](https://bitcoin.stackexchange.com/a/103254).


Do you think it looks legit?

P.S. Unfortunately, this is not an option to convince someone.
P.P.S. Thank you for the helpful replies.

**Comment by apoelstra** [comment]
>Do you think it looks legit?

Yep, that looks like what I'd do. (Though again, double-check with a few examples. And bear in mind the caveats about risk of wallet incompatibility that I've mentioned above.)

**Comment by f-squirrel** [comment]
Thank you, @apoelstra for verification!

**Comment by RCasatta** [comment]
https://github.com/RCasatta/electrum2descriptors you can double check here

**Comment by f-squirrel** [comment]
> @apoelstra , thank you again for a quick reply.
> 
> I did the following:
> 
> ```rust
> fn convert_vpub_to_tpub(vpub_key: &str) -> String {
>     let mut decoded = base58::decode(vpub_key).expect("Failed to decode base58 key");
>     decoded[0..4].copy_from_slice(&[0x04, 0x35, 0x87, 0xCF]);
>     base58::encode(&decoded)
> }
> ```
> 
> The output is `tpubDCpP2bUR4GbTZkfizWRozZVuZ2aohedBEzpHzvckRFXvKDWko6kA4T3PdUsFgXL9qtJ8326v52uwxG6HCMkA9fPym6QkiUgjqKyDwwSvDtA`.
> 
> I reimplemented this implementation: https://github.com/jlopp/xpub-converter/blob/master/js/xpubConvert.js. The actual online tool can be found [here](https://jlopp.github.io/xpub-converter/). It was mentioned at the [SO](https://bitcoin.stackexchange.com/a/103254).
> 
> Do you think it looks legit?
> 
> P.S. Unfortunately, this is not an option to convince someone. P.P.S. Thank you for the helpful replies.

EDIT:
The code does not take into account the checksum, this is the fixed version:

```rust
use std::collections::HashMap;

use bdk::bitcoin::base58 as BitcoinBase5858;
use sha2::{Digest, Sha256};

use lazy_static::lazy_static;

// DD: See https://github.com/satoshilabs/slips/blob/master/slip-0132.md
lazy_static! {
    static ref PREFIX_MAP: HashMap<[u8; 4], ([u8; 4], &'static str, bdk::bitcoin::Network)> = {
        let mut data: HashMap<[u8; 4], ([u8; 4], &str, bdk::bitcoin::Network)> = HashMap::new();
        data.insert(
            [0x04, 0x88, 0xb2, 0x1e],
            (
                [0x04, 0x88, 0xb2, 0x1e],
                "wpkh([c258d2e4/44/0h/0h]",
                bdk::bitcoin::Network::Bitcoin,
            ),
        );
        data.insert(
            [0x04, 0xb2, 0x47, 0x46],
            (
                [0x04, 0x88, 0xb2, 0x1e],
                "wpkh([c258d2e4/49/0h/0h]",
                bdk::bitcoin::Network::Bitcoin,
            ),
        );
        data.insert(
            [0x04, 0x9D, 0x7C, 0xB2],
            (
                [0x04, 0x88, 0xb2, 0x1e],
                "wpkh([c258d2e4/84/0h/0h]",
                bdk::bitcoin::Network::Bitcoin,
            ),
        );

        data.insert(
            [0x04, 0x35, 0x87, 0xCF],
            (
                [0x04, 0x35, 0x87, 0xCF],
                "wpkh([c258d2e4/44/1h/0h]",
                bdk::bitcoin::Network::Testnet,
            ),
        );

        data.insert(
            [0x04, 0x4A, 0x52, 0x62],
            (
                [0x04, 0x35, 0x87, 0xCF],
                "wpkh([c258d2e4/49/1h/0h]",
                bdk::bitcoin::Network::Testnet,
            ),
        );

        data.insert(
            [0x04, 0x5F, 0x1C, 0xF6],
            (
                [0x04, 0x35, 0x87, 0xCF],
                "wpkh([c258d2e4/84/1h/0h]",
                bdk::bitcoin::Network::Testnet,
            ),
        );
        data
    };
}

fn calculate_checksum(data: &[u8]) -> [u8; 4] {
    let hash = Sha256::digest(Sha256::digest(data));
    [hash[0], hash[1], hash[2], hash[3]]
}

fn update_decoded_and_checksum(decoded: &mut [u8], new_prefix: &[u8], decoded_len: usize) {
    decoded[0..4].copy_from_slice(new_prefix);
    let checksum = calculate_checksum(&decoded[..decoded_len - 4]);
    decoded[decoded_len - 4..].copy_from_slice(&checksum);
}

// DD: See https://github.com/jlopp/xpub-converter/blob/master/js/xpubConvert.js
pub(crate) fn make_descriptor_from_pubkey(
    pub_key: &str,
) -> anyhow::Result<(bdk::bitcoin::Network, String)> {
    log::debug!("Building descriptor from pubkey: {}", pub_key);
    let mut decoded = BitcoinBase5858::decode(pub_key)?;
    let decoded_len = decoded.len();

    let (new_prefix, new_path, network) = PREFIX_MAP
        .get(&decoded[0..4])
        .ok_or_else(|| anyhow::anyhow!("Unsupported key"))?;

    log::debug!(
        "prefix: {:x?}, path: {:?}, network: {:?}",
        new_prefix,
        new_path,
        network
    );

    update_decoded_and_checksum(&mut decoded, new_prefix, decoded_len);

    let full_path = format!("{}{}/0/*)", new_path, BitcoinBase5858::encode(&decoded));
    Ok((*network, full_path))
}
```
