### ISSUE TITLE
Remove `ACTIONS_ALLOW_UNSECURE_COMMANDS` from the CI

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/bdk#168]
Apparently the actions from `actions-rs` that we use are trying to change the `PATH`env variable, which is not allowed anymore and make the CI fail. See: https://github.com/bitcoindevkit/bdk/runs/1408731180 

Adding `ACTIONS_ALLOW_UNSECURE_COMMANDS` make them work, but it's not recommended and should be removed if possible.

**Comment by notmandatory** [comment]
ugh.. I'll try replacing the `actions-rs` commands with multiple `run:` commands, it will be a little more verbose but should work.
