### ISSUE TITLE
Benchmark the transaction graph reconciliation

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1687]
"Benchmark the transaction graph reconciliation with the canonical chain in the presence of large unconfirmed transaction chains and/or high number of conflicts."

**Comment by notmandatory** [comment]
This should be done before and after #1670 is merged.

**Comment by ValuedMammal** [comment]
This is some data collected around the time of 1.0.0-beta.5 https://hackmd.io/@valuedmammal/rywvTTgQkl

**Comment by notmandatory** [comment]
Fixed in #1670
