### ISSUE TITLE
Improve try_get_chain_position the logic

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1691]
"In try_get_chain_position the logic to filter out confirmed ancestors was copy-pasted for the descendants (you can see as the comment wasn't updated, it still mentions "We're filtering the ancestors"). But if a confirmed descendant is encountered it means the transaction is confirmed too, so it could shortcut?"

**Comment by oleonardolima** [comment]
It can be closed now, as #1670 has been merged, right ?

**Comment by notmandatory** [comment]
Yes you're right, the `try_get_chain_position` function was removed in #1670 so we can close this one now too.
