### ISSUE TITLE
Sqlite: check anchor to tx foreign key constraint

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1712]
"In the SQLite persistence the foreign key constraint from anchor to transactions is not checked. Adding an anchor for a non-existing transaction will prevent persisting the wallet."

**Comment by notmandatory** [comment]
Is there a scenario where were need to insert an `Anchor` without a corresponding transaction id?

**Comment by ValuedMammal** [comment]
We should also revisit #961 when trying to reproduce the SQL error.

**Comment by notmandatory** [comment]
@oleonardolima is taking a look at this one. Or possibly just helping with testing @evanlinjin's PR #1736.
