### ISSUE TITLE
Question: BDK audit report

### ISSUE THREAD

**Issue by darioAnongba** [bitcoindevkit/bdk#1720]
Hi BDK team,

My company (and others) are interested in using BDK to integrate Bitcoin and they are curious if the version 0.29 was audited or if the future release v1 is going to be audited (and if the report is public). We see some issues labeled "audit" and we know big companies are using BDK so we are confident but some kind of report would be nice.

Cheers,
Dario

**Comment by notmandatory** [comment]
Hi @darioAnongba the Spiral team recently paid for a code audit for the BDK 1.0 beta rust lib. I'll be publishing a blog post, hopefully this week, with a summary and link to the original report. In the meantime you can see the recommendations from this report with the new "audit" label. 

I recommend any new projects should start with the BDK 1.0.0-beta which is nearly done with beta testing and ready for a final release. I'll be posting regular updates on remaining work for the final 1.0.0 release on discord.

**Comment by darioAnongba** [comment]
Great ! Looking forward to your blog post
