### ISSUE TITLE
Better comment for `TxGraph::empty_outspends`

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1747]
> No need to call this an "atrocity" since it's the best way to do it.
> 
> ```suggestion
>     // This exists so that `TxGraph::outspends()` can return a reference to an empty set of `Txid`s.
> ```

_Originally posted by @notmandatory in https://github.com/bitcoindevkit/bdk/pull/1670#discussion_r1831290121_

**Comment by notmandatory** [comment]
fixed by #1670
