### ISSUE TITLE
First time contributions

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk#1762]
This issue lays out our thoughts and policy around first-time contributions that focus on simple grammatical fixes of documentation and the like.

If it is your first time contributing to the BDK family of libraries, welcome! We're glad to have you with us. If your first (or few first) PRs are focused on very small fixes to documentation, however, they might not meet our threshold for acceptance for first time contributors.

Minor grammar and punctuation fixes aren't a good way to start contributing to a project, and instead we suggest you start with something a little more substantial. It's better to find an issue where you can demonstrate some knowledge of bitcoin or the code base, such as improving the substance of documentation, testing, or fixing some small issue even if it's considered low priority.

This being said we are always looking forward to working with new folks interested in contributing to our libraries. If you are looking for issues to work on, check out the [`good first issue`](https://github.com/bitcoindevkit/bdk/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) label and join our Discord server!

**Comment by thunderbiscuit** [comment]
This issue is opened so that it can be linked and referenced in PRs that fall in this category across the bitcoindevkit org.

**Comment by Gudnessuche** [comment]
Thank you for this clarification.
I actually came here to probably get Silent Payment merged to BDK and felt like starting with docs first.
Would heed to the above advice still.
