### ISSUE TITLE
Investigate using `testcontainers-rs` in github-actions CI tests

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#179]
https://github.com/testcontainers/testcontainers-rs

**Comment by thomaseizinger** [comment]
Hi!

Primary maintainer of `testcontainers-rs` here. Feel free to ping me if you have any questions :)

We've originally built `testcontainers-rs` at work to make testing of blockchain protocols against actual nodes easier!

**Comment by justinmoon** [comment]
They already have [Bitcoin Core support](https://github.com/testcontainers/testcontainers-rs/blob/dev/src/images/coblox_bitcoincore.rs) in the project.

[Here's how you run it](https://github.com/testcontainers/testcontainers-rs/blob/f95a5c22167b6b0093ec97479c6070fae134a498/tests/images.rs#L26).

**Comment by notmandatory** [comment]
We decided to use the `bitcoind` and `electrsd` crates for integration testing.
