### ISSUE TITLE
Validate block header data from multiple public data sources

### ISSUE THREAD

**Issue by remyers** [bitcoindevkit/bdk#198]
Our current blockchain data sources are focused on connecting to a single (trusted) full node. This makes sense both from a best practices standpoint and for getting a minimal viable implementation up and running faster.

SPV clients need some additional functionality if they use untrusted public servers to watch for and validate transactions:
 - gossip and manage which peers to connect to
 - query multiple peers for the chain tip
 - download block headers (from genesis or a checkpoint) from a single peer (or multiple peers in parallel)
 - validate the header chain
 - prioritize fast peers and ban peers that supply bad headers

This functionality can be implemented at a layer above the individual block chain data sources that provide block headers.

Support for logic to manage peers, headers and compact filters from public data sources is needed by users of mobile wallets that do not have a trusted full node they can connect to. 

Public data sources running Electrum servers and full nodes that support compact block filters should be able to share the same logic.

**Comment by justinmoon** [comment]
This would also be nice for enterprise wallets which want to check against every major version of bitcoind (maybe btcd etc) and make sure they're always in agreement.

**Comment by remyers** [comment]
Ideally the parts of Bitcoin Core that do peer management and block header management could be wrapped into a Rust interface. We will most likely have to just reimplement the same logic in Rust, but worth investigating how hard it would be to modularize these functions in Bitcoin Core first.

**Comment by RCasatta** [comment]
When we implement block headers validation we can probably take some code from https://github.com/Blockstream/gdk/blob/master/subprojects/gdk_rust/gdk_electrum/src/headers/bitcoin.rs and 
https://github.com/Blockstream/gdk/pull/59

**Comment by notmandatory** [comment]
This is covered in #81 under "Receive Filter Headers" but for doing it for and between other block data sources I'm closing this until we find some wallets who need this feature.
