### ISSUE TITLE
Error parsing multisig descriptor

### ISSUE THREAD

**Issue by justinmoon** [bitcoindevkit/bdk#21]
Example:
```
use magical_bitcoin_wallet::descriptor::ExtendedDescriptor;
use std::str::FromStr;

fn main() {
    let desc_str = "wsh(multi(1,[9d033c9d/48'/1'/0'/2']tpubDEHKJA6XKc6QaRvc5gunJY9T9cst9m1y8o2owqrvUmXK69ZjWySB7hgB6HvFdTp5MamaKYumSGxL49VUiEjWrhDE8N8BympFWDknLBEPG38/0/*,[6bb3d403/48'/1'/0'/2']tpubDDw2d4rKFtn5ECCq4KQ6GTi73YUQt3Wz2gqyv19kLAPJQKKKzNvEESi9v44sG4Fc6DsBuDgo5FQ9ZxbzQfV2X7jRvsBcT7N5s6g57xS4aUM/0/*))";
    ExtendedDescriptor::from_str(&desc_str).unwrap();
}
```

Output:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Miniscript(Unexpected("multi(3 args) while parsing Miniscript"))', examples/magical.rs:6:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

[Here is where the error is being created in rust-miniscript](https://github.com/apoelstra/rust-miniscript/blob/master/src/miniscript/astelem.rs#L497). You can see a couple lines above that is where `multi` should be handled, but it seems there hasn't been a rust-miniscript release [since it was added](https://github.com/apoelstra/rust-miniscript/commit/3dac01d662efe7f2b816caa0127af16fb99bf4ef).

**Comment by justinmoon** [comment]
The above descriptor does work if I replace `multi` with `thresh_m` ...

**Comment by afilini** [comment]
Exactly, I was waiting for them to tag a new release before I upgrade the library here in Magical. I'll keep this issue open as a tracking task for the upgrade, in the meantime I'll keep an eye on their repo and see when they plan to release the upgrade.

**Comment by justinmoon** [comment]
[1.0.0 was released](https://crates.io/crates/miniscript)
