### ISSUE TITLE
Fix code-coverage reports

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/bdk#230]
There's something wrong with codecov.io, it says "unable to find commit on github" for most of the recent commits, and even for commits that are available there are no reports visible (this could be because the report is only generated for every new `master` "tip" and not for every single commit)`

**Comment by notmandatory** [comment]
Drat, I think I broke it when I removed `actions-rs`, it stopped working after my commit. I'll work on fixing it.

https://github.com/bitcoindevkit/bdk/commit/13c1170304e5df6b09139a58fc5377fd44d463a8
