### ISSUE TITLE
Reduce build time for `docs.rs`

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/bdk#244]
`docs.rs` has a timeout of 15 minutes for building the docs, which is very close to how long it takes to build `bdk`, mainly due to the `rocksdb` dependency for `compact_filters`. We should figure something out to reduce the build time, otherwise we risk getting build failures as the project grows.

**Comment by notmandatory** [comment]
Fixed with #416 in [release 0.11.0](https://github.com/bitcoindevkit/bdk/releases?page=1)
