### ISSUE TITLE
Signing a PSBT already signed with the same key

### ISSUE THREAD

**Issue by RCasatta** [bitcoindevkit/bdk#254]
It may be useful to know if the signature generated by bdk is the same contained in the PSBT, since bdk is using RFC6979 for signatures, this would prove also the other signer is using it.

We may want to handle this as an option of the `TxBuilder`, like `check_nonce` or for other use cases `always_override`

**Comment by afilini** [comment]
We've talked about this in a meeting, we feel like this is a bit too specific and probably not worth implementing.

If one really needs this behavior, it could be replicated by implementing a custom signer that wraps `bitcoin::PrivateKey` and does the extra checks: for instance, the custom signer could temporarily remove the signature, ask the underlying signer to produce one, and then compare it with the old one.
