### ISSUE TITLE
Should be a way to get the blockchash of a block a transaction was included in 

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#292]
Right now `Blockchain::get_tx` just returns the transaction. We don't know if it's confirmed or not and there is no way to figure this out. This might not be useful for wallets but I need this and it's weird that I can't get this info -- it seems like existing backends that support getting a transaction support this via `get_merkle`.

**Comment by LLFourn** [comment]
So it looks like by the API that electrum offers this sort of thing is not really possible. You can do it with esplora but not with electrum.

I will leave this open for further comments but if you see this issue down the road just close it if i haven't already.

**Comment by RCasatta** [comment]
I think you can do it with electrum API with a synced headers chain and using https://github.com/bitcoindevkit/rust-electrum-client/blob/af10aeac99bcd2b68c1b84b264d0971c76873301/src/api.rs#L175 ?

**Comment by LLFourn** [comment]
@RCasatta That's what I thought too but you already have to know the height (it's an argument) that the tx was in so that doesn't really work.

**Comment by RCasatta** [comment]
Yeah, sorry, you did specify it in the first comment...

In the electrum protocol the tx height is returned by `script_get_history` https://github.com/bitcoindevkit/rust-electrum-client/blob/af10aeac99bcd2b68c1b84b264d0971c76873301/src/api.rs#L124
So in theory we can have a convoluted method asking the tx then asking `script_get_history` for one of its outputs...

If you have a synced Wallet the height it's in `TransactionDetails`

**Comment by LLFourn** [comment]
Right so what I went with was creating a temporary wallet for a particular output on a transactions and syncing the wallet and seeing if it has any transactions!

Tracking whether a certain output exists or has been confirmed or not is a really common task in Bitcoin L2 protocols so it would be wonderful if there was a less awkward way of doing this. I think I might close this in favor of an issue like that once I've thought about it some more.

**Comment by LLFourn** [comment]
Closed in favor of: https://github.com/bitcoindevkit/bdk/issues/306

**Comment by shesek** [comment]
Electrs has a `blockchain.transaction.get_confirmed_blockhash` RPC method for this purpose, added in https://github.com/romanz/electrs/commit/a0a3d4f9392e21f9e92fdc274c88fed6d0634794.

It's the only Electrum server implementation that has it.

**Comment by LLFourn** [comment]
@shesek thanks. It does indeed look like to be maximally efficient we'll have to fingerprint the particular electrum server we are pointed to and figure out at runtime what it is capable of.
