### ISSUE TITLE
Setting input_index = None makes all the signers panic

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#295]
I am not sure why `input_index` would be `None` but I think the signer should not panic in this case or it should not be an `Option`: 

https://github.com/bitcoindevkit/bdk/blob/master/src/wallet/signer.rs#L210-L220

Incidentally I don't really see a problem with it panicking if the index is out of range which is normally the caller's responsibility.

**Comment by afilini** [comment]
This is a bit convoluted, but the idea is that if `Signer::sign_whole_tx()` returns `false`, then the index should always be provided.

There are some signers that can't sign inputs individually (one example is the GreenAddress server), so in that case you can override the default implementation for `sign_whole_tx()`, return `true` and then ignore the index and just sign everything.

Ideally a signer should know how to sign individual inputs, for example to support foreign utxos in a tx. Not all of them can, so we have this weird hack

**Comment by LLFourn** [comment]
Hmm ok I see. So you ask the thing first what it is and then call the appropriate method. The signers could be a enum of `Box<dyn Signer>` or `Box<dyn SignWholeTx>` i.e. two different traits.

Perhaps just having a different method for each type of signing would be clearer with one being `unreachable!()`. Having an `.unwrap` on the first line of a method confused me.

**Comment by afilini** [comment]
Yeah there's definitely room for improvement. I like your idea of the two individual traits: we could then implement a `sign(psbt: PartiallySignedTransaction)` on the enum, and internally it would either do the inputs individually or the whole tx at once.

I would call them something like `InputSigner` or `TransactionSigner`, is it clear enough?

**Comment by davemo88** [comment]
I took a crack at this by removing `sign_whole_tx` and using the `input_index` argument to communicate the intention to sign all or just one.

I agree with LLFourn's initial idea that `input_index` should not be an `Option`. Perhaps `Signer` should only sign a specific input and multiple input signing should happen at the wallet level. This is because "sign the whole transaction" always means "try to sign all the inputs one by one", right?

**Comment by LLFourn** [comment]
@davemo88 the problem is you can't instruct some devices to only sign single inputs "at the wallet level". You can only tell them to sign all or none. I think what @afilini suggested is the way forward.

**Comment by davemo88** [comment]
I see - if you wanted to implement `Signer` for something that can't sign individual inputs, you'd be stuck.

**Comment by davemo88** [comment]
I [tried again](https://github.com/bitcoindevkit/bdk/compare/master...davemo88:two-signer-traits), following the InputSigner / TransactionSigner dual trait suggestion, but I wasn't sure how to handle the `id` and `descriptor_secret_key` methods. I ended up making another trait for those and requiring it in the others.

**Comment by danielabrozzoni** [comment]
Closing as I believe this is fixed (now we have a `TransactionSigner` and an `InputSigner`). Feel free to re-open if I'm mistaken :)
