### ISSUE TITLE
Relicensing MIT + Apache

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#301]
This issue is based on a [similar issue] from the LDK project. 

There has been some discussion recently on Discord about dual licensing BDK under [MIT] and [Apache 2.0] instead of only MIT. Both licenses are simple and permissive, making it easy for open source and commercial projects to adopt BDK. The primary advantages of dual licensing are:

1. the [Apache 2.0] licenses provides additional "patent use" permission
2. most [Rust crates] are dual licensed under MIT and Apache 2.0 
3. the [LDK] project is dual license MIT and Apache 2.0 so will make collaboration easier

To go forward with this change we need anyone who's made significant contributions before to sign off. I've listed all of the folks who show up in `git shortlog` below. If we don't get everyone that may be OK, but we'll need to go back and check that their contributions were relatively minor.

If you're on the below list and agree with this change please add a comment with "I hereby re-license my previous contributions to BDK under [Apache 2.0] in addition to the existing [MIT] license." 

[similar issue]: https://github.com/rust-bitcoin/rust-lightning/issues/659
[Apache 2.0]: https://choosealicense.com/licenses/apache-2.0/
[MIT]: https://choosealicense.com/licenses/mit/
[Rust crates]: https://choosealicense.com/community/
[LDK]: https://github.com/rust-bitcoin/rust-lightning

- [x] @afilini 
- [x] @danielabrozzoni 
- [x] @dspicher 
- [x] @eupn
- [x] @justinmoon 
- [x] @LLFourn 
- [x] @luckysori 
- [x] @Xekyo 
- [x] @RCasatta 
- [x]  @ulrichard 
- [x] @notmandatory 
- [x] @thomaseizinger 
- [x] @tcharding 
- [x] @willcl-ark

**Comment by notmandatory** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by willcl-ark** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by dspicher** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by RCasatta** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by luckysori** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by LLFourn** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in
addition to the existing MIT license.

**Comment by thomaseizinger** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by tcharding** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by tcharding** [comment]
@notmandatory you'll have to update the checklist yourself if needed, I don't have edit perms.

**Comment by ulrichard** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by danielabrozzoni** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by afilini** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.
<details>
  <summary>Signature and timestmap</summary>

#### GPG signature

```
-----BEGIN PGP MESSAGE-----

owEB1QIq/ZANAwAIAUMUAeSkUwBhAct1YgBgPKmaSSBoZXJlYnkgcmUtbGljZW5z
ZSBteSBwcmV2aW91cyBjb250cmlidXRpb25zIHRvIEJESyB1bmRlciBBcGFjaGUg
Mi4wIGluIGFkZGl0aW9uIHRvIHRoZSBleGlzdGluZyBNSVQgbGljZW5zZS4KiQJM
BAABCAA2FiEEN3HnuSjCMmq+90dKQxQB5KRTAGEFAmA8qa0YHGFsZWtvcy5maWxp
bmlAZ21haWwuY29tAAoJEEMUAeSkUwBhO+oQAKfdn38vUa66EDcOi86m+WLmWXFE
Kv4UMFpwpgFHjL5wmZKsnAC+c8jow5n5ceEmgcYcKULAhguyKLVuXySwZSXUQAcb
d27aTjlrChSKPJXyHOgEQ2hC6niMzqbHhhq1ILiT/8E+HOtA/X4iUs9PKFT10lZY
zQp3I0LlHGYo7XhCNB/lgT64NchAngsczE5een+cIKtdSkSkJNsGMmImVQX4Pbc/
wm2AapIycgxtMtrWwOlxy5sCwslzIOu8UnuLQ8CzCo+c53e1Jh83RiRMR6/6sCFQ
FB/7Y9OHDtfz7uRSFQSCm8f5Nfzhr1M4NTS3Ef9SP90iSCHGKQ4Zx/scWq8Ed02U
RLT72lUw8wUQA2dyYj7daw8q4cAY9bZs+xQob3pNLZxWo7oneQganVcj1+KcuyGv
Pik5hIuc+x3IuIsSgViHUG3t283YXVEnyFS0xt/IyxYQKJl1ojahEEdS56jrFrRG
tGgXw51gGMJR8FG3eyKfJpHBP4sFRw0WxO+dqJw/RZ4vfFM+BUIJ/ExH20aoe0Kd
X10a8lFnfNxEORSKmcf8DiJ9p+p+SD172OoIbuyGIa8HIDIE9pvjfzOSsNgSwuBQ
TOfM+pniy5b7ryTJvKL/KbSDlLLj5ITLwOU63cofecNKlP1RXXZ5qj4zxznf3Szr
45De680Gk2h/pByz
=7sFA
-----END PGP MESSAGE-----
```

#### OpenTimestamps proof

```
AE9wZW5UaW1lc3RhbXBzAABQcm9vZgC/ieLohOiSlAEIPkJHyqoNOn1MQiJ1zHmlY031mJwljisb
AJkLdKwmxj3wEOZ0aFfr4Jdxi/PUnkCPNtoI//AQAVXW8QnzZuG0M9OYFHjWHAjxBGA8qdbwCP2v
ztOdhsODAIPf4w0u+QyOLCtodHRwczovL2JvYi5idGMuY2FsZW5kYXIub3BlbnRpbWVzdGFtcHMu
b3Jn//AQMtc1KwZ7w/jDzCY5fX0tswjxBGA8qdbwCCQ1Fyis9UmPAIPf4w0u+QyOIyJodHRwczov
L2J0Yy5jYWxlbmRhci5jYXRhbGxheHkuY29t//AQhAD+j6MJzysTqL99xaobrwjxBGA8nALwCOus
eSDi/NIYAIPf4w0u+QyOKShodHRwczovL2Zpbm5leS5jYWxlbmRhci5ldGVybml0eXdhbGwuY29t
8BCRLgZ5JtczfGjcvCxjIzYzCPEEYDyp1vAItihAZvytJdIAg9/jDS75DI4uLWh0dHBzOi8vYWxp
Y2UuYnRjLmNhbGVuZGFyLm9wZW50aW1lc3RhbXBzLm9yZw==
```

</details>

**Comment by thunderbiscuit** [comment]
Does this apply to `bdk-cli` and `bdk-jni`? Or do they get their own issues for that?

**Comment by notmandatory** [comment]
> Does this apply to `bdk-cli` and `bdk-jni`? Or do they get their own issues for that?

I think for those projects we can just do PRs to make the LICENSE change and point back to this issue since they're all part of the bigger BDK effort.

**Comment by murchandamus** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by eupn** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by justinmoon** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.
