### ISSUE TITLE
Handle database migrations

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/bdk#359]
**Description**

We could store a "database structure serial" in the db and check it every time it's loaded, to detect when the structure changes.

A good example of how database migrations can be done is in the `database/sqlite` module. The goal of this issue is to add general support for any database module to update to a new structure when required.

**Expected Outcomes** 

* Create a new trait and possibly structs in the database module to support database schema migration
* Implement or update database migration for the `keyvalue` and `sqlite` modules 
* Any new public traits and structs should be documented 
* New trait implementations should have basic unit tests
* Error if database schema version is > version in code (ie. using older code on database migrated with newer version)

**Resources**  

* [BDK Website](https://bitcoindevkit.org)
* [BDK github repo](https://github.com/bitcoindevkit/bdk)
* [BDK Slack](https://discord.gg/dstn4dQ)

**Skills Required**  

* Experience with git. [Guide](https://git-scm.com/book/en/v2)
* Basic familiarity with rust. [First seven chapters of the book](https://doc.rust-lang.org/book/)
* Basic familiarity with SQL and JSON
* Familiarity with BDK’s keyvalue and sqlite database modules

**Mentor(s)**  
@notmandatory 

**Difficulty**  
Medium

**Competency Test**  

* Install rust, compile and run all bdk examples and tests. 
* Read through the BDK docs.
* Make a dummy wallet with BDK with key-value and sqlite backends. 
* Familiarity with basic rust, should be able to write basic custom trait implementations on foreign structures.

**Comment by notmandatory** [comment]
DB schema migration/upgrades are being done in #376 but only for the `sqlite` `Database`. Could we handle this as a `Database` specific feature? in that case we'd only need to add it as an internal part of the key-value DB.

**Comment by LLFourn** [comment]
^ can we add some kind of "transparently handle db upgrade architecture" task to upcoming hackathon?

**Comment by notmandatory** [comment]
Per our team chat yesterday I changed this into a summer-of-bitcoin project.

**Comment by LLFourn** [comment]
We don't have a `Database` trait anymore so this issue is stale. We could allow people to migrate from one persistence backend to another generically -- this would be pretty easy now. But that feels like another issue.
