### ISSUE TITLE
Confirmed transactions show up as pending on application restart

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk#391]
This is happening on `bdk-jni`, and I'm not sure if it has to do with the db/cache on mobile or if it's coming from the bdk side.

@RCasatta could this be related to the #370 fix?

The issue is the following. Once you've synced while a transaction was pending, the new type `confirmation_time` is `None` (`null` on the Kotlin side). This is great. What's more, if you `sync` the wallet and the transaction has been confirmed, the vallue is updated to reflect the timestamp and a block height. All good. The problem seem to happen on application restart: a call to `transaction_list()` will return that transaction as pending again. You can then `sync` the wallet and it will update the `confirmation_time` value, but this sync has to be done (from what I can tell) every time. It's like the database doesn't remember that the `transactionDetails` were updated.

<center>
<img src="https://user-images.githubusercontent.com/39974688/125169707-68c58680-e179-11eb-99b2-3e3e3833f60c.gif" width="300px" />
</center>

**Comment by RCasatta** [comment]
can you try with this patch?

```
diff --git a/src/database/keyvalue.rs b/src/database/keyvalue.rs
index 9978497..85de6ea 100644
--- a/src/database/keyvalue.rs
+++ b/src/database/keyvalue.rs
@@ -377,7 +377,9 @@ impl BatchDatabase for Tree {
     }
 
     fn commit_batch(&mut self, batch: Self::Batch) -> Result<(), Error> {
-        Ok(self.apply_batch(batch)?)
+        self.apply_batch(batch)?;
+        self.flush()?;
+        Ok(())
     }
 }

```

Just an untested quick try, I'll check it properly on Monday

**Comment by thunderbiscuit** [comment]
I'm sorry I don't really know how to pull this in the JNI in a quick/test way... but I do want to help test it. I'm just not sure how.

**Comment by afilini** [comment]
I had a brief discussion about this with @RCasatta, we think it might be a good idea to add a `flush()` method to `Database` and to explicitly call it after every write.

Then we'll implement it for `sled` to ensure writes are flushed to disk.

**Comment by notmandatory** [comment]
I think the new `sqlite` database backend might solve this for mobile apps. Will test it once #376 is in a merged. If so we may not need the `sync()` function after all, but will need to document it if the `key-value-db` isn't recommended for mobile.

**Comment by thunderbiscuit** [comment]
This issue is resolved on my end. Thanks!
