### ISSUE TITLE
BDK will select coinbase inputs that are not matured yet

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#413]
I just did `generatetoaddress` to a wallet address and tried to create a transaction. BDK wallet did it but RPC returned: `"sendrawtransaction RPC error: {\"code\":-26,\"message\":\"bad-txns-premature-spend-of-coinbase, tried to spend coinbase at depth 38\"}"`

**Comment by afilini** [comment]
I wonder what's the best way to fix this, should we ignore them completely even in the UTXO list/balance or just ignore them in the coin selection by default (maybe with a builder method to enable them explicitly)?

**Comment by LLFourn** [comment]
I think it should be in the UTXO list but should not be selected. `.balance` needs more work to account for things like unconfirmed vs confirmed balances #238 and "locked_coinbase_balance" could be added also added there.

**Comment by afilini** [comment]
Reopening since this hasn't been fixed in #459, it was just the first step
