### ISSUE TITLE
Should be able to spend already unconfirmed spent inputs without RBF

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#414]
When you do `add_utxo` you should be able to add a utxo that has already been spent in that there is a transaction that has spent it seen by the wallet. One way to do this would to not delete the utxo from the database after you see a transaction spending it but just mark the utxo with that txid.

**Comment by rajarshimaitra** [comment]
Just to clear my understanding. Why would we want to add a "spent" utxo to our transaction inputs?

**Comment by LLFourn** [comment]
@rajarshimaitra to double spend it. Sorry wasn't clear that bdk considers a utxo spent as soon as it sees a tx with it as an input in mempool. I also don't see why we shouldn't be able to create a tx with an already confirmed spend if we explicitly ask for that.
