### ISSUE TITLE
Consider deprecating functions instead of breaking the API right away

### ISSUE THREAD

**Issue by thomaseizinger** [bitcoindevkit/bdk#419]
I would like to ask to consider a slightly friendlier API evolution model for bdk.

At the moment, upgrading to a new version of bdk often breaks a build and it is not immediately obvious, how to fix things. For example, I've been using `set_single_recipient` in one of my applications and upgrading to from `0.8` to `0.10` made this function disappear.

After having dug up the changelog, I [could see](https://github.com/bitcoindevkit/bdk/blob/master/CHANGELOG.md#wallet) that I needed to change my code to use `drain_to` instead.

Overall that wasn't too difficult but it still broke my flow because updating to the latest version broke the compiler.

If we were to make use of `#[deprecated]` instead, I could have:

a) continued with my actual task and deal with the "use of deprecated API" warnings later
b) received a hint within my IDE on how to fix the issue

I do realize that maintaining deprecated APIs can be cumbersome and I think only maintaining them until the next version would be completely fine.

Thank you for considering :)

**Comment by LLFourn** [comment]
Hey @thomaseizinger. Thanks for bringing this up. I think we should try to do this. There will be many cases where breaking changes are necessary and we are unable to depreciate the way the old thing worked. In this case I *think* we could have made `set_single_recipient`  call `drain_to` internally and deprecated it. Good point.

**Comment by thomaseizinger** [comment]
Yes, I acknowledge that it is not always possible or sometimes it would add too much friction. Personally, I find it helpful to make a mental shift from "changing code" to "adding new code" because adding a new functions is never a breaking change.

In some cases, you can avoid internal code duplication by having now deprecated functionality call through to updated APIs. Where that is not possible, leaving the old code in and simply adding new code (possibly through duplication) can be a way of evolving APIs in a friendlier way.

Paired with a mentality where as many things as possible are private, cleaning up internally after such a duplication happened is not too hard actually. Once deprecated APIs are removed, the compiler will issue `unused_code` warnings if they are no longer publicly reachable which is the case if they are marked private.

**Comment by notmandatory** [comment]
This sounds like a reasonable approach to me, to deprecate changing APIs for at least one release (4-6 weeks) before removing them. We'll just need to make it part of our review process and to make sure folks with API breaking PRs follow-up with subsequent PRs a release later to remove the deprecated code.

@thomaseizinger would you like to submit a PR to update our `CONTRIBUTING.md` file a short section with your suggested approach to handing API breaking changes? 

We will also discuss this issues live with the team at our next team meetings on 8/24 @ 20:00 UTC.

**Comment by thomaseizinger** [comment]
> @thomaseizinger would you like to submit a PR to update our `CONTRIBUTING.md` file a short section with your suggested approach to handing API breaking changes?

See https://github.com/bitcoindevkit/bdk/pull/422.

**Comment by tcharding** [comment]
I already ack'ed the PR before I saw this, amusingly deprecating for one release cycle would not have helped you @thomaseizinger since you say you upgraded from v0.8 -> v0.10 :)

**Comment by thomaseizinger** [comment]
> I already ack'ed the PR before I saw this, amusingly deprecating for one release cycle would not have helped you @thomaseizinger since you say you upgraded from v0.8 -> v0.10 :)

Well, one reason why the upgrade to 0.9 was delayed was because the breaking changes made the dependabot PR fail and other things had priority. So in a way, it would have helped because the 0.9 upgrade would have had a bigger chance of landing.

**Comment by LLFourn** [comment]
+1 to close this since it has been considered.
