### ISSUE TITLE
Wasm support for bdk

### ISSUE THREAD

**Issue by josediegorobles** [bitcoindevkit/bdk#437]
I'tried to compile bdk for wasm target and i only get to compile without client, offline. When i add electrum always include socket library and that library is not compatible with wasm target. But i can compile with wasm electrum client too, so I think there must be a way to have bdk with electrum client in wasm.

**Comment by tcharding** [comment]
I'm not very knowledgeable about WASM but I believe the electrum client is not compatible with WASM at the moment because its not async. The esplora client (using `reqwest`) can be used with WASM however. Does that help?

**Comment by josediegorobles** [comment]
Yes i will try with esplora.

**Comment by josediegorobles** [comment]
It's running. Perfect then!
