### ISSUE TITLE
`bdk::testutils!` macro does not import required traits / types

### ISSUE THREAD

**Issue by thomaseizinger** [bitcoindevkit/bdk#446]
We are using the `bdk::testutils!` macro to create instances of `bdk::Wallet` for testing purposes which works quite well and is really useful.

I am not sure if it is meant to be used outside of bdk but I noticed that the macro often does not import required types and or traits for it to function in isolation. For example, with an upgrade from 0.10 to 0.12, our test code fails to compile with:

```
error[E0599]: no method named `derive_translated` found for enum `miniscript::Descriptor<miniscript::DescriptorPublicKey>` in the current scope
   --> swap/src/bitcoin/wallet.rs:621:17
    |
621 | /                 testutils! {
622 | |                     @tx ( (@external descriptors, index as u32) => self.utxo_amount ) (@confirmations 1)
623 | |                 },
    | |_________________^ method not found in `miniscript::Descriptor<miniscript::DescriptorPublicKey>`
    |
   ::: /home/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/bdk-0.12.0/src/testutils/mod.rs:69:8
    |
69  |       fn derive_translated<C: Verification>(
    |          ----------------- the method is available for `miniscript::Descriptor<miniscript::DescriptorPublicKey>` here
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use bdk::testutils::TranslateDescriptor;`
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

The fix is easy but I am wondering whether or not we could make this more ergonomic by having the macro always import all the required types and traits?

**Comment by thomaseizinger** [comment]
Scratch that, it actually works, I was just still depending on the `bdk-testutils` crate.

One other addition though, could we have the `bdk::populate_test_db!` macro reference `testutils!` via a full-qualified path?

It would be nice if I could do:

```rust
for index in 0..self.num_utxos {
    bdk::populate_test_db!(
        &mut database,
        bdk::testutils! {
            @tx ( (@external descriptors, index as u32) => self.utxo_amount ) (@confirmations 1)
        },
        Some(100)
    );
}
```

Without having to also do `use bdk::testutils;`.

**Comment by LLFourn** [comment]
I actually don't remember us making this public. What kind of test do you use this for? My theory was that you would only ever test bdk apps against a live regtest node and this kind of thing was only useful for testing the wallet itself within bdk.

I suppose I could see it being useful if you had a custom coin selection algorithm you wanted to test but then I think there could be better ways of doing that too.

**Comment by thomaseizinger** [comment]
> What kind of test do you use this for?

Anything that starts with funding a joint-output.

- https://github.com/comit-network/xmr-btc-swap/blob/7de3e23bb00276db33e00985dc04f1915b08b362/swap/src/bitcoin/wallet.rs#L391-L430
- https://github.com/comit-network/xmr-btc-swap/blob/7de3e23bb00276db33e00985dc04f1915b08b362/swap/src/bitcoin/lock.rs#L182-L278

Plus, it is really helpful for writing tests for protocols. Our latest protocol is started via an extension trait to `bdk::Wallet`: https://github.com/comit-network/hermes/blob/a62dcfb9ac7ccdb2a4885e07de247942eb1ba22d/cfd_protocol/src/protocol.rs#L38-L64

> My theory was that you would only ever test bdk apps against a live regtest node

Testing against a live regtest node is utterly slow and brittle due to the IO that is happening. Regtest nodes also need to be warmed up by mining 100 blocks etc.

**Comment by LLFourn** [comment]
> > What kind of test do you use this for?
> 
> Anything that starts with funding a joint-output.
> 
>     * https://github.com/comit-network/xmr-btc-swap/blob/7de3e23bb00276db33e00985dc04f1915b08b362/swap/src/bitcoin/wallet.rs#L391-L430

Taking this one for example, it looks to me like you are just testing that TxBuilder is behaving correctly? I think all the actual branches before using TxBuilder could be captured by checking result from finish() (e.g. Error::InsufficientFunds).

If we do want to do this then I think it makes sense to provide a more sensible API for "testutils". It's rather difficult to understand and document with its current syntax. It should be split up into distinct macros with proper docs if people want to test against TxBuilder logic.

PR for fixing the problem at hand is fine though I just wouldn't expect this to remain stable.

> Testing against a live regtest node is utterly slow and brittle due to the IO that is happening. Regtest nodes also need to be warmed up by mining 100 blocks etc.

Furious agreement here. But the tests do test something at least!

@afilini I wonder what your vision is for this?

**Comment by RCasatta** [comment]
> Testing against a live regtest node is utterly slow and brittle due to the IO that is happening. Regtest nodes also need to be warmed up by mining 100 blocks etc.

To speed up a bit regtest nodes and reduce disk IO, they could be run with datadir in memory (like using `/dev/shm` if available). for example: https://github.com/RCasatta/bitcoind/pull/35

**Comment by afilini** [comment]
> @afilini I wonder what your vision is for this?

Yeah I don't think the current testutils stuff are really meant to be used outside of bdk, but I guess we could try to provide a "test framework" if there's demand for it. 

I guess the difference would be that our internal testing stuff are designed to test that bdk itself works correctly, while what we provide to the outside should be designed to help testing protocols that use bdk.

Maybe we could just have a test `Blockchain` type and build `Wallet` instances with it. Then provide an API to control the `Blockchain` to simulate different scenarios.

**Comment by thomaseizinger** [comment]
> Maybe we could just have a test `Blockchain` type and build `Wallet` instances with it. Then provide an API to control the `Blockchain` to simulate different scenarios.

That would definitely suite our needs. The main things I'd want from it are:

- Specifying the total UTXO value
- Specifying the number of UTXOs

**Comment by LLFourn** [comment]
Closing this because `testutils` is not meant to be used publicly. Put test blockchain idea here: https://github.com/bitcoindevkit/bdk_wallet/issues/185
