### ISSUE TITLE
BDK should always scan addresses it has utxos for

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#451]
At the moment BDK stops syncing after it finds `stop_gap` addresses that don't have any associated tx. But what if has a utxo for an address after stop gap in the database. Despite BDK not scanning for them it can still find these utxos because they might be on a transaction that bdk is already interested for other reasons.

I think another way of thinking about it is that bdk should always sync addresses it has given out regardless if they fall after `stop_gap` empty addresses. In fact, stop gap shouldn't be used except for when doing an initial sync. BDK should just look up to the highest index address in the database (i.e. the highest index of an address it has given out).

**Comment by RCasatta** [comment]
I don't think you don't have to look for stop_gap addresses after initial sync because you may have more instances of the same descriptor (eg mobile and desktop)

**Comment by LLFourn** [comment]
True. Ok so I guess the right answer is the application should be able to control where to stop. The sync needs to be more flexible to be able to "sync up to last given out address" and "sync until you stop finding active addresses + stop gap". Though it seems to me like it should always sync addresses that have utxos.

**Comment by RCasatta** [comment]
Yes, having the sync configurable makes sense (I think with the default the safest/slower option of always looking for the stop_gap...)

> Though it seems to me like it should always sync addresses that have utxos.

 agreed

**Comment by evanlinjin** [comment]
My understanding of this ticket is we should always scan for `scriptPubKey`s that are already cached in `Database` (initially), unless `stop_gap` is greater than the amount cached (in which case, we respect the `stop_gap` parameter).

Subsequent syncs after should fully respect the `stop_gap` parameter.

Is my understanding correct?

**Comment by LLFourn** [comment]
I don't think so. What if you have a utxo that has a script pubkey that is after a gap greater than `stop_gap` addresses?

**Comment by evanlinjin** [comment]
> I don't think so. What if you have a utxo that has a script pubkey that is after a gap greater than `stop_gap` addresses?

It's up to the user/implementation to set `stop_gap` to an appropriate value right? Otherwise how should we know at what `scriptPubKey` index sync should stop?

**Comment by LLFourn** [comment]
You could sync via the utxos you have and not use `stop_gap` at all. I think this issue is just about making sync flexible. For example in `bdk_esplora` in the `bdk_core` repo I plan to make `stop_gap` an `Option<u32>`.
