### ISSUE TITLE
Intermittent errors when combining CompactFiltersBlockchain with MemoryDatabase

### ISSUE THREAD

**Issue by ulrichard** [bitcoindevkit/bdk#469]
My application runs totally fine with ElectrumBlockchain or RpcBlockchain, but it runs into frequent problems with CompactFiltersBlockchain. I constantly get CompactFilters(DataCorruption) or CompactFilters(Timeout) from wallet.sync(noop_progress(), None);
After I remove the contents of storage_dir, it works the first time, but on the second run, I start getting these errors again.
I also played with compact_filters in bdk-cli, and there everything was totally fine.
My local bitcoind node on localhost is the only one I'm connecting to.
It appears that the main difference is that bdk-cli uses sled database while my application uses MemoryDatabase.
Thus to reproduce the problem, I modified bdk-cli to also use MemoryDatabase in https://github.com/weareseba/bdk-cli/tree/memorydb
When running https://github.com/weareseba/bdk-cli/blob/memorydb/memorydb_compact_filters.sh in this configuration, I can reproduce the problem sometimes, but a lot less frequently than in my application.

**Comment by rajarshimaitra** [comment]
IIRC Unlike other blockchains, comapct filters stores filter data specific to a given wallet descriptor. And adding that with a non-persistent wallet db like memory db can cause problems. At each run memory db will create new wallet descriptors that will not match with previously stored compact filters. 
- This will not happen in sled, because sled will persistently store the wallet data. 
- This won't be an issue for other blockchains because with new descriptor they will happily sync from scratch, and memory db is not persistent, so each run will create a new db, so you won't see any error.

I am not sure what your application is, but I suspect something like that is going on. In general for most of the cases you would want to use sled or any other persistent db, not the memory db.

If you also post the 1) error log, 2) bdk-cli usage comamnd and 3) the changes you have made in bdk-cli, I can try to reproduce it..

**Comment by ulrichard** [comment]
I am working on a cold storage solution where only a subset of the machines has internet access. The descriptors are simple multisig, hence reproduceable. Since those wallets have only few transactions, I thought MemoryDatabase would be enough, so we don't have to care about persistence of additional data. But the system contains many different wallets. So, if we were going to use a persistent database, that would obviously have to be stored separately. And now I am not sure now if I also need to store the data for the compact filters separately per wallet? If so, that could be improved in the documentation.
https://docs.rs/bdk/0.13.0/bdk/blockchain/compact_filters/struct.CompactFiltersBlockchainConfig.html

I thought I made it easier to reproduce by posting links to the repo branch with the modification and the script with the commands. But here are the same in file format:
[memorydatabase.diff.txt](https://github.com/bitcoindevkit/bdk/files/7538217/memorydatabase.diff.txt)
[memorydb_compact_filters.sh.txt](https://github.com/bitcoindevkit/bdk/files/7538178/memorydb_compact_filters.sh.txt)

and the output of running that script looks like this:
`    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/bdk-cli -n testnet wallet --node '127.0.0.1:18334' --descriptor 'wpkh(cVpPVruEDdmutPzisEsYvtST1usBR3ntr8pXSyt6D2YYqXRyPcFW)' sync`
Keeping bundle #2103 as Tip
{}
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/bdk-cli -n testnet wallet --node '127.0.0.1:18334' --descriptor 'wpkh(cVpPVruEDdmutPzisEsYvtST1usBR3ntr8pXSyt6D2YYqXRyPcFW)' sync`
{}
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/bdk-cli -n testnet wallet --node '127.0.0.1:18334' --descriptor 'wpkh(cVpPVruEDdmutPzisEsYvtST1usBR3ntr8pXSyt6D2YYqXRyPcFW)' sync`
Keeping bundle #2103 as Tip
{}
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/bdk-cli -n testnet wallet --node '127.0.0.1:18334' --descriptor 'wpkh(cVpPVruEDdmutPzisEsYvtST1usBR3ntr8pXSyt6D2YYqXRyPcFW)' sync`
Keeping bundle #2103 as Tip
[2021-11-15T13:11:34Z ERROR bdk_cli] CompactFilters(DataCorruption)
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/bdk-cli -n testnet wallet --node '127.0.0.1:18334' --descriptor 'wpkh(cVpPVruEDdmutPzisEsYvtST1usBR3ntr8pXSyt6D2YYqXRyPcFW)' sync`
Keeping bundle #2103 as Tip
{}
`

**Comment by rajarshimaitra** [comment]
> I thought MemoryDatabase would be enough, so we don't have to care about persistence of additional data. But the system contains many different wallets. So, if we were going to use a persistent database, that would obviously have to be stored separately.

Hmm.. In case persistent storage is not an option for you, I think compact filters won't also be suitable for that application. 

> And now I am not sure now if I also need to store the data for the compact filters separately per wallet? If so, that could be improved in the documentation.

Yes you would need to store block filter data corresponding to each wallets. This is automatically done by bdk and the blockfilter data are stored in the same folder where wallet data are kept. But they should be consistent before each run. I suspect that's what the data corruption error is suggesting. And I agree, this should be included in the docs somewhere. 

Having a quick look into your script it seems you are using the same descriptor for each run. So it should not cause any trouble in theory. I will have to look deeper to see whats wrong..

**Comment by rajarshimaitra** [comment]
One way to quickly check if the data compatibility is the issue here, is to delete the default wallet db folder (that includes the compact filter data + wallet data) before each run. This should not be a problem for you application but should remove the error.

If that doesn't fix it, then something else is going off.

**Comment by ulrichard** [comment]
Ok so that seems to be the problem then. So, I close the issue now and implement the persistence separately per wallet. If that doesn't solve the problem, I can still re-open this one.
