### ISSUE TITLE
Use dust_value from rust-bitcoin

### ISSUE THREAD

**Issue by RCasatta** [bitcoindevkit/bdk#472]
Apparently rule for dust is more complicated than what we have here
https://github.com/bitcoindevkit/bdk/blob/9f04a9d82dcd7280efe520bf29d31779e2bde0d0/src/wallet/utils.rs#L41

see https://github.com/rust-bitcoin/rust-bitcoin/blob/ab97d2db1a4595058367edc80cd038f8467d538e/src/blockdata/script.rs#L457

**Comment by rajarshimaitra** [comment]
Yes and as per the comment here https://github.com/bitcoindevkit/bdk/blob/9f04a9d82dcd7280efe520bf29d31779e2bde0d0/src/wallet/utils.rs#L16 we should handle per output type cases. 

Maybe this can be added as a good first issue @notmandatory ? Should be simple changes.
