### ISSUE TITLE
rust-hwi improvements

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bdk#479]
**Description**  
 
[rust-hwi](https://github.com/bitcoindevkit/rust-hwi) is a small utility project under BDK, that wraps the python [HWI (Hardware Wallet Interface) of Bitcoin Core](https://github.com/bitcoin-core/HWI). This project hasn't been updated for some time, and warrants some housekeeping and updates to make it compatible with latest HWI standards. This can be very useful for other rust based bitcoin wallet projects.

**Expected Outcomes**  
   

- Basic understanding of HWI
- Using Bitcoin Core with a standard Hardware Wallet
- making rust-hwi up to date with current HWI standard
- Make rust-hwi installation automated.

**Resources**  
  
  
  
  
 

- Bitcoin HWI [doc](https://hwi.readthedocs.io/en/latest/?badge=latest). 

**Skills Required**  
  
  
  
  

- Experience with git. [Guide](https://git-scm.com/book/en/v2)
- Basic familiarity with rust. [First seven chapters of the book](https://doc.rust-lang.org/book/)
- Familiarity with Python.

**Mentor(s)** :  
@danielabrozzoni 

**Difficulty**  : Easy

**Competency Test (optional)**  

- Install rust, compile and run all bdk examples and tests.
- Familiarity with basic rust, should be able to write custom trait implementations on foreign structures.

**Comment by danielabrozzoni** [comment]
#682 finally solved this 🥹🥹
