### ISSUE TITLE
RocksDB Replacement in CBF Blockchain

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bdk#480]
**Description**  
  
Currently the Compact Block Filters ([BIP157](https://github.com/bitcoin/bips/blob/master/bip-0157.mediawiki)) blockchain backend implementation for BDK, uses RocksDB as the database to store the compact block filter data. [RocksDB](https://github.com/rust-rocksdb/rust-rocksdb) is quite a large dependency and it takes a significant amount of building time, while compiling bdk with `compact_filters` feature. Also RocksDB crate is not native rust, its a wrapper over [rocksdb](https://rocksdb.org/), which increases its compilation time even more. Thus it is desirable to replace RocksDB with a more smaller and compact DB implementation.

The required feature for a candidate DB for CBF would be

- Simple Key-Value storage.
- Automated disk flushing.
- Smaller build time than RocksDB.
- Preferably having its own rust implementation.   

**Expected Outcomes**  
  

- General understanding of BIP157, BIP158 and BDK CBF syncing mechanism.
- Literature survey and comparative study between different DB implementation.
- Complete replacement of RocksDB.
- Faster build and run time with new DB, demonstrated via benchmarking.

**Resources**  
  
  
  
  
  

**Skills Required**  
  
  
  
  

- Basic Familiarity with wallet syncing in general and [BDK sync mechanisms](https://github.com/bitcoindevkit/bdk/blob/master/src/blockchain/compact_filters/sync.rs).
- Basic Familiarity with BIP157, BIP158.
- Experience with git. [Guide](https://git-scm.com/book/en/v2)
- Basic familiarity with rust. [First seven chapters of the book](https://doc.rust-lang.org/book/)
- CRUD operations of standard rust based DB (ex: sqlite)

**Mentor(s)**  
@rajarshimaitra 

**Difficulty**: Hard  

**Competency Test (optional)**  

- Install rust, compile and run all bdk examples and tests. 
- Read through the BDK docs. 
- Familiarity with basic rust, should be able to write basic custom trait implementations on foreign structures.

**Comment by evanlinjin** [comment]
This is no longer relevant for BDK v1.0.
