### ISSUE TITLE
Improving Coinselection in BDK

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bdk#483]
**Description**  
  

Coinselection is the scheme to select a set of utxo, from all the available utxos, to create the most optimum spending transaction. Effective coinselection is beneficial for reducing transaction fees as well as improving operation privacy for a wallet. BDK currently uses two coinselection algorithms, [LargestFirst and BranchAndBound](https://docs.rs/bdk/0.13.0/bdk/wallet/coin_selection/index.html).

The aim of the project is to 

- include more coinselection algorithms in the library.
- Add a comparative mechanism to evaluate coinselection results from different algos.
- Use the most “effective” algorithm chosen by a “specific metric”.

**Expected Outcomes**  
 

- General understanding coinselection in Bitcoin protocol.
- Comparative study between different coinselection algorithms.
- Coming up with a metric to compare results of different coinselection algos.

  

**Resources**  
  
  
  
  
  

- What is [Coin Selection](https://bitcoin.stackexchange.com/questions/1077/what-is-the-coin-selection-algorithm)
- Generic Coin Selection [research paper](https://murch.one/wp-content/uploads/2016/11/erhardt2016coinselection.pdf)
- Bitcoin Core [PR Review Club](https://bitcoincore.reviews/22009) on "waste metric".
-  Proposed [waste metric in rust for BDK](https://github.com/bitcoindevkit/bdk/pull/435) to compare different coin selection algorithms.
- BDK Coin selection improvement [idea](https://github.com/bitcoindevkit/bdk/issues/120).
- Coin Selection [Literature](https://murch.one/wp-content/uploads/2016/11/erhardt2016coinselection.pdf).
- Scaling Bitcoin 2016, Milan, Coin Selection [PPT](https://scalingbitcoin.org/milan2016/presentations/D2%20-%204%20-%20Mark%20Erhardt.pdf) 
- Scaling Bitcoin 2016, Milan, Coin Selection [Transcript](https://scalingbitcoin.org/transcript/milan2016/coin-selection)

**Skills Required**  
  
  
  
  

- Experience with git. [Guide](https://git-scm.com/book/en/v2)
- Basic familiarity with rust. [First seven chapters of the book](https://doc.rust-lang.org/book/)
- Familiarity with Bitcoin’s Coin Selection algorithms.
- Familiarity with BDK’s [coinselection module](https://docs.rs/bdk/0.13.0/bdk/wallet/coin_selection/index.html).

**Mentor(s)**  
@danielabrozzoni 

**Difficulty** : Medium 

**Competency Test (optional)**  

- Install rust, compile and run all bdk examples and tests. 
- Read through the BDK docs.
- Make a dummy wallet with BDK with different blockchain backends. 
- Familiarity with basic rust, should be able to write custom trait implementations on foreign structures.

**Comment by notmandatory** [comment]
See also #120

**Comment by notmandatory** [comment]
Additional reading on coin selection.

Recent:
https://bitcoincore.reviews/22009
#435
#120  

Historical:
https://murch.one/wp-content/uploads/2016/11/erhardt2016coinselection.pdf
https://scalingbitcoin.org/milan2016/presentations/D2%20-%204%20-%20Mark%20Erhardt.pdf
https://scalingbitcoin.org/transcript/milan2016/coin-selection

**Comment by Tejasvigupta** [comment]
Hey, I am Tejasvi and I am looking forward to contributing to this project. I am new to rust so currently I am learning it. I have thoroughly gone through the research paper on coin selection. What should be my next step?

**Comment by notmandatory** [comment]
Hi @Tejasvigupta are you part of the summer of bitcoin group? And if so have you already gone through their screening? https://guide.summerofbitcoin.org/about/how-it-works

**Comment by Tejasvigupta** [comment]
Hi @notmandatory I am a member of the summer of bitcoin group and I have already gone through their screening round.

**Comment by notmandatory** [comment]
Closing this issue until we have officially move coin selection out of `bdk_wallet` and into a new `bdk_coin_select` crate.
