### ISSUE TITLE
Running into `TransactionNotFound` errors during sync

### ISSUE THREAD

**Issue by thomaseizinger** [bitcoindevkit/bdk#494]
**Describe the bug**  

In our application (https://github.com/itchysats/itchysats) we keep occasionally running into `TransactionNotFound` error's when `sync`ing the wallet. Once we run into this problem, the wallet database is completely broken and needs to be deleted before things work again. We are using the SQLite database and the Electrum backend.

**To Reproduce**  

Unfortunately, we don't quite know, how to reproduce the problem. The functionality of BDK that we are using is:

- BIP84 descriptor
- 2 parties create a PSBT and add inputs to fund a specific output
- Both parties exchange the set of inputs with each other
- Merge the PSBTs
- Both parties sign their inputs
- Exchange and merge the PSBTs
- Finalize and broadcast the transaction

Recently, we've managed to reproduce this problem once where the above process aborted half-way through because the coin-selection failed with "InsufficientFunds" for one party.

**Expected behavior**  

I am unsure what the best behaviour is but it is causing some headache that the DB is rendered unusable if you once run into this problem. It would be nice if the sync could still complete and only emit a warning that a certain transaction could not be processed.

I've read through the code a bit and checked where this error is returned but couldn't quite work out, how this is triggered by our use of BDK.

**Build environment**  
 - BDK tag/commit: **0.14**
 - OS+version: **Linux 5.10.79-1-MANJARO**
 - Rust/Cargo version: **1.57.0**
 - Rust/Cargo target: **x86_64-unknown-linux-gnu**

**Comment by notmandatory** [comment]
Do you happen to have a broken database file we can look at (ie. testnet or regtest) ? it might help shed some light on where things went wrong.

**Comment by LLFourn** [comment]
@notmandatory https://github.com/bitcoindevkit/bdk/pull/461 didn't get included in v0.14 right?

@thomaseizinger can you confirm whether you are using the `verify` feature? If so then turning it off will likely fix the issue.

**Comment by notmandatory** [comment]
> @notmandatory https://github.com/bitcoindevkit/bdk/pull/461 didn't get included in v0.14 right?
> 
Correct, #461 is not in v0.14.

**Comment by thomaseizinger** [comment]
> @thomaseizinger can you confirm whether you are using the `verify` feature? If so then turning it off will likely fix the issue.

Confirm, not using the verify feature!

**Comment by klochowicz** [comment]
> Do you happen to have a broken database file we can look at (ie. testnet or regtest) ? it might help shed some light on where things went wrong.

here's testnet database exhibiting the behaviour that we've ran into with @thomaseizinger  :
[maker_wallet.sqlite.zip](https://github.com/bitcoindevkit/bdk/files/7665704/maker_wallet.sqlite.zip)

**Comment by thomaseizinger** [comment]
> @notmandatory #461 didn't get included in v0.14 right?

We are depending on the latest HEAD now and the issue seems to be gone so #461 seems to fix this!

**Comment by notmandatory** [comment]
That's great! let's keep this issue open until `0.15.0` release is out (release candidate is out Dec 15, release ~Dec 22) and you can confirm this issue is fixed with that version, ok?

**Comment by LLFourn** [comment]
Fixed in 0.15.0
