### ISSUE TITLE
Non-Wallet Tx verification doesn't work for RPC backend

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bdk#498]
**Describe the bug**  
Recently @LLFourn described a possible problem with updated sync logic in `verify_tx` logic in dev discord https://discord.com/channels/753336465005608961/753367451319926827/917624709426855946. I verified the issue exists currently even without the updated sync logic in `rpc` blockchain too.

`verify_tx` doesn't work for non wallet transactions with a rpc blockhain without `txindex`.

This happens because `get_raw_transaction` here https://github.com/bitcoindevkit/bdk/blob/64e88f0e006c68315142d53dc35b633327dde4b5/src/blockchain/rpc.rs#L327-L329 will return error if the transaction is not wallet related.

**To Reproduce**  
This can be reproduced with the test code added here
https://github.com/rajarshimaitra/bdk-example/blob/13097bab3f7742e8cc46c9b4b78be0fd7d44a315/src/main.rs#L276-L335

with the following error message
```
running 1 test
thread 'test::test_transaction_validation' panicked at 'called `Result::unwrap()` on an `Err` value: Global(Rpc(JsonRpc(Rpc(RpcError { code: -5, message: "No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions.", data: None }))))', src/main.rs:335:63
stack backtrace:
```

**Expected behavior**  
`verify_tx` should verify any transaction, not only just wallet txs.

**Possible recourse**
We should enforce `txindex` to be used in `rpc` backend when using `verify` feature.

**Comment by LLFourn** [comment]
So on the call I think we agreed the solution here is not to verify the transactions on the rpc backend.

This bit of code has to be removed

https://github.com/bitcoindevkit/bdk/blob/64e88f0e006c68315142d53dc35b633327dde4b5/src/wallet/mod.rs#L1540-L1555

and instead each backend that benefits from verification (esplora, electrum) should verify the transactions as they come in during sync. Furthermore the `verified` field on `TransactionDetails` can be removed (this will be a non-breaking DB change hopefully).

**Comment by rajarshimaitra** [comment]
> and instead each backend that benefits from verification (esplora, electrum) should verify the transactions as they come in during sync.

Maybe I am missing something and forgot to ask this in the meeting, can you elaborate on whats the difference between electrum and esplora from rpc, in context of verification? They also have a bitcoin core backend running right? So transactions will be consensus verified in them too automatically?

Also in that case of refactoring, should `verify_tx` still be an public open function? or it will be something only internal to the syncs?

Another related thought, I feel like there's value in exposing the `bitcoinconsensus` through our API. There might be downstream usecases when dev needs to check for verification of custom transactions. There is no other exposed API wrapper around `bitcoinconsensus` as far as I know in the eco. I so feel like its important to keep the API live. Maybe make it an wallet API?

**Comment by notmandatory** [comment]
> Maybe I am missing something and forgot to ask this in the meeting, can you elaborate on whats the difference between electrum and esplora from rpc, in context of verification? They also have a bitcoin core backend running right? So transactions will be consensus verified in them too automatically?

I think what @LLFourn meant is that if you're using `rpc` then it must be on your localhost and therefore you implicitly trust what ever transaction data you're getting. But for `electrum` or `esplora` you may be connecting to someone else's hosted service (ie. blockstream) and in that case it's a good idea to verify the transaction data.

**Comment by rajarshimaitra** [comment]
Ah ok, yes that makes sense. And I agree, verification is a costly operation and we should avoid that whenever possible.

**Comment by rajarshimaitra** [comment]
I am working on a PR for this.

**Comment by rajarshimaitra** [comment]
Closing after #502
