### ISSUE TITLE
Should we expose `client` from the `wallet`?

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bdk#499]
The `verify_tx` function requires a `blockchain` reference. 
https://github.com/bitcoindevkit/bdk/blob/64e88f0e006c68315142d53dc35b633327dde4b5/src/wallet/verify.rs#L32-L36

We should expose the internal wallet `blockchain` client for downstream users to use the same `blockchain` used inside the `wallet`, and not have to make another one, just to use in `verify_tx()`. 

Another option is to make `verify_tx` an wallet API, and not have it as a free function.

**Comment by LLFourn** [comment]
There is a `client` method to get the client? The hard thing about `verify_tx` is the database.

As a side note I think that wallet should not have a `Blockchain` inside it. After @afilini refactored things so block height of last sync is stored we only need blockchain in `sync` which should just be changed to take a `Blockchain` as an argument (like `verify_tx`).

I don't know where to hang `verify_tx` but I guess `Wallet` would be an ok place for now.

**Comment by rajarshimaitra** [comment]
> There is a client method to get the client? The hard thing about verify_tx is the database.

Ah my bad, yes there is a client method. Also there is `database` method too for get the db reference. So I guess the main point of this issue is void. 

> As a side note I think that wallet should not have a Blockchain inside it. After @afilini refactored things so block height of last sync is stored we only need blockchain in sync which should just be changed to take a Blockchain as an argument (like verify_tx).

No strong feeling on this one. To me it makes sense to have the `blockchain` in `wallet` which is quite a important component of it. Maybe we can have another `sync_with_blockchain` method that takes in a different blockchain if user wants to have the wallet working on multiple blockchian backends?

> I don't know where to hang verify_tx but I guess Wallet would be an ok place for now.

Because we are using both the db and client for verification, it does make sense to me to put `verify_tx` as an wallet API.

**Comment by rajarshimaitra** [comment]
Closing this now because client is already exposed from wallet.
