### ISSUE TITLE
error: timeout when synchronizing a new wallet with skip_blocks: None

### ISSUE THREAD

**Issue by w0xlt** [bitcoindevkit/bdk#512]
The code below (when run on signet) throws the error: `Problem synchronizing wallet: Rpc(JsonRpc(Transport(Timeout)))`

```rust
// Setup the RPC configuration
let rpc_config = RpcConfig {
    url: rpc_url,
    auth,
    network: *network,
    wallet_name: wallet_name.clone(),
    skip_blocks: None,
};

// Use the above configuration to create a RPC blockchain backend
let blockchain = RpcBlockchain::from_config(&rpc_config).unwrap();

// ...

let wallet = Wallet::new(receive_desc, Some(change_desc), *network, db_tree, blockchain).unwrap();

// Sync the wallet
let sync_result = wallet.sync(LogProgress, None);

match sync_result {
    Ok(_) => return true,
    Err(error) => println!("Problem synchronizing wallet: {:?}", error),
};
```

If the`skip_blocks` field is changed to `Some(70_000)` or to the value equivalent to `get_block_count()` , the code will work fine.

The reason is that `skip_blocks: None` scans blocks since genesis. It might be better if there is a way to retrieve the block from which the wallet was created. Or `skip_blocks` can be a parameter of `pub fn sync` instead of `RpcConfig`.

**Comment by notmandatory** [comment]
Need to investigate if we can increase timeout so this doesn't happen on a long resync.

**Comment by w0xlt** [comment]
Closing this issue as `skip_blocks` is no longer part of `RpcConfig`.
