### ISSUE TITLE
inconsistent types for numbers of block in get_block_count and skip_blocks

### ISSUE THREAD

**Issue by w0xlt** [bitcoindevkit/bdk#513]
`bitcoincore_rpc::client::RpcApi pub fn get_block_count()` returns a `u64` value.

```rust
/// Returns the numbers of block in the longest chain.
fn get_block_count(&self) -> Result<u64> {
    self.call("getblockcount", &[])
}
```
But `bdk::blockchain::rpc pub struct RpcConfig` requires `u32` type for `skip_blocks`.

```rust
pub struct RpcConfig {
    /// The bitcoin node url
    pub url: String,
    /// The bitcoin node authentication mechanism
    pub auth: Auth,
    /// The network we are using (it will be checked the bitcoin node network matches this)
    pub network: Network,
    /// The wallet name in the bitcoin node, consider using [crate::wallet::wallet_name_from_descriptor] for this
    pub wallet_name: String,
    /// Skip this many blocks of the blockchain at the first rescan, if None the rescan is done from the genesis block
    pub skip_blocks: Option<u32>,
}
```

Although, in this case, `u64` type can apparently be converted without data loss to `u32`  via `let block_count = u32::try_from(get_block_count()).ok().unwrap()`, it might be better to have the same type for the same thing (numbers of block).

**Comment by rajarshimaitra** [comment]
Make sense. Also I think `bitcoincore_rpc` always gives block height in u64. So it might make sense to change block heights everywhere to `u64`.

**Comment by rajarshimaitra** [comment]
@w0xlt made the change in #523 . Let me know what you think..

**Comment by w0xlt** [comment]
Great. I will review soon. Thanks !

**Comment by LLFourn** [comment]
As noted in #523, `u32` is the right datatype for blockheight so if anything `bitcoincore_rpc` should change theirs.
