### ISSUE TITLE
`get_descriptor_for_keychain(KeychainKind::Internal)` should return `None` if there is no internal keychain

### ISSUE THREAD

**Issue by w0xlt** [bitcoindevkit/bdk#525]
The code below returns the external descriptor.

I understand that external descriptor will be used as (internal) change descriptor if it does not exist, but I think it would be better and less ambiguous if the function returned `None` or `Error` when explicitly calling  the internal descriptor.

This would also make a better distinction between external and internal descriptors and be more in line with the wallet structure.

```rust
let wallet = Wallet::new_offline(
        "<desc>",
        None,
        network,
        MemoryDatabase::default(),
)
.unwrap();

let desc = wallet.get_descriptor_for_keychain(KeychainKind::Internal);

println!("desc: {}", desc.to_string());
```

**Comment by LLFourn** [comment]
Or maybe just `has_descriptor_for_keychain` returning a `bool`.

**Comment by w0xlt** [comment]
Good suggestion.
I opened https://github.com/bitcoindevkit/bdk/pull/528 to add this function.

**Comment by LLFourn** [comment]
As mentioned in #528 you can do this with `Wallet::public_descriptor` and checking if the return value  is `is_none()`.
