### ISSUE TITLE
Set default transaction nLocktime to discourage fee sniping

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#533]
As suggested by @thebluematt and in [discussion with 0x10w#1026 on discord](https://discord.com/channels/753336465005608961/753367451319926827/934882144554192926), by default BDK should follow the anti-fee-sniping logic used by Bitcoin Core and Electrum to set the nLocktime when creating new transactions. This default nLocktime value should still be able to be overridden if the the existing `TxParams.locktime` parameter is set.  See:

Bitcoin Core anti-fee-sniping code:
https://github.com/bitcoin/bitcoin/blob/6d859cbd794a36ed1c0c72324a4ec54d029b3d3b/src/wallet/spend.cpp#L591-L631

Electrum anti-fee-sniping code:
https://github.com/spesmilo/electrum/blob/7e6d65ec11c0dccfc24478471c5951d3ae586937/electrum/wallet.py#L211-L224

Currently BDK sets the default transaction nLocktime to 0. See:

https://github.com/bitcoindevkit/bdk/blob/b1346d4ccf7b3c818ec73b4648825b1d20589de2/src/wallet/mod.rs#L511-L512

**Comment by afilini** [comment]
I think this could be tricky to implement with our planned architectural changes, because the code that builds the transaction will not have access to the blockchain to get the current height.

I don't think it's worth changing the architecture just to do this: after all it's very easy for the users of our library to explicitly set the nlocktime, so I don't think it's a huge problem if it's not done by default.

**Comment by kafaichoi** [comment]
Sorry where can I find information about the planned architectural changes you mentioned? I was thinking to give this issue a try but want to make sure I wasn't doing sth opposite of planned change🙏🏽

**Comment by afilini** [comment]
In this case I'm mainly referring to the idea of splitting up the `Blockchain` trait into multiple traits. After that we can make some methods of the `Wallet` struct available only if the given blockhain instance supports the right traits, which mean that we will probably make the transaction creation completely offline

**Comment by TheBlueMatt** [comment]
I'm sure its a nontrivial layer violation, but I'd implore you to think harder about at least setting this by default for most users. Sure, some designs may understandably not be able to support it, but making users explicitly think about passing a `None` instead of a `Some(blockchain_ref)` to the relevant functions is much better than nothing here. Its quite important for Bitcoin's long-term sustainability that wallets set nLocktime by default, not to mention privacy improvements for users.

**Comment by w0xlt** [comment]
I created a simple example that sets the nlocktime of a transaction using Bitcoin Core as backend.
https://github.com/w0xlt/bdk_nlocktime_test/blob/master/src/main.rs

I will add this code to https://github.com/bitcoindevkit/bdk/pull/526.

As mentioned by @afilini, this is difficult to do by default as the transaction builder is completely independent of the backend and works offline.

Perhaps exposing TxParams publicly, as suggested in the TODO below, might help.
https://github.com/bitcoindevkit/bdk/blob/master/src/wallet/tx_builder.rs#L131

**Comment by notmandatory** [comment]
I removed the "good first issue" label since sounds like this needs more discussion.

**Comment by notmandatory** [comment]
We discussed this one in our team chat yesterday and as @afilini mentioned above once we separate the blockchain traits from `Wallet` we won't be able to automatically get the current block height and set the nLockTime as recommended. But we can still do the following:
1. Store the latest block height after each `walled.sync` in the wallet cache DB and use this value for calculating the default anti-fee-sniping nLockTime. The only down side is if the user hasn't sync'd recently then we will use an older height and leave more room for sniping.
1. Provide some sort of function on the `TxBuilder` that takes the current block height (or a blockchain trait?) and calculates the nLockTime based on this value. Something like `TxBuilder.setAntiFeeSnipingLockTime`.
1. Document clearly in the Rust docs that the `Wallet` should be sync'd prior to using `TxBuilder` or if syncing isn't possible they should use the `TxBuilder.setAntiFeeSnipingLockTime` with the current block height (or a blockchain trait?).

**Comment by notmandatory** [comment]
PS. the current block height (and time) from the latest `Wallet.sync` are already stored in the wallet's `Database`.

https://docs.rs/bdk/latest/bdk/database/trait.Database.html#tymethod.get_sync_time

https://github.com/bitcoindevkit/bdk/blob/b1346d4ccf7b3c818ec73b4648825b1d20589de2/src/database/mod.rs#L155

**Comment by danielabrozzoni** [comment]
> Store the latest block height after each walled.sync in the wallet cache DB and use this value for calculating the default anti-fee-sniping nLockTime. The only down side is if the user hasn't sync'd recently then we will use an older height and leave more room for sniping.

This means that if we don't sync for a while, all our transactions are going to have the same nLockTime, which means that a potential observer could link all our transactions together. Are we ok with that?
(See https://github.com/bitcoin/bitcoin/pull/15039)

**Comment by afilini** [comment]
It shouldn't be a big issue imho. In general you should always sync before creating txs (otherwise you may accidentally double-spend an input)
