### ISSUE TITLE
CHANGELOG conflicts are very annoying

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#536]
During development we constantly have PRs that are unable to be merged due to conflicts in the CHANGELOG. I don't know what the solution is but here is the first result on google: https://about.gitlab.com/blog/2018/07/03/solving-gitlabs-changelog-conflict-crisis/

**Comment by evanlinjin** [comment]
It seems that the link you provided is the solution that everyone is using.

https://github.com/rubocop/rubocop/issues/8697#issuecomment-690875556

**Comment by notmandatory** [comment]
I also have a PR that I think is a good way to fix this issue, but I need to dust it off and get some more discussion on it. #544
