### ISSUE TITLE
[ci] Fix broken "build docs" in nightly_docs.yml

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#538]
There is currently a regression in `+nightly` rustdocs that is [breaking our CI docs build](https://github.com/bitcoindevkit/bdk/runs/5029906501?check_suite_focus=true). 

I believe this is caused by https://github.com/rust-lang/rust/issues/93476

I think we have two options:

1. For the docs CI jobs remove the `--cfg docsrs` flag and build docs with `+stable`
2. Wait for rustdocs in `+nightly` to be fixed

**Comment by notmandatory** [comment]
I prefer option 1, even though we won't see which feature is required to enable feature gated code, we can keep documenting it with the `docsrs` attribute and when the `feature(doc_cfg)` is available in `+stable` turn it back on. 

If we take option 2 the issue may get fixed in the next few days but we can still run into some other regression in a future `+nightly` and will have our CI randomly broken again.

**Comment by afilini** [comment]
Maybe a third option is to pin a specific nightly version that we know is working fine?

It's not the end of the world to lose the `doc_cfg` feature, but I would like to replicate the environment in docs.rs as much as we can, so that we can see if anything is wrong before publishing a release

**Comment by notmandatory** [comment]
Good idea! I forgot we can use specific nightly builds. I'll put together a PR to do that.
