### ISSUE TITLE
Add the KeychainKind to the AddressInfo struct

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#541]
Add the `KeychainKind` field to the `AddressInfo` struct and update any functions that return `AddressInfo` to set it. 

See discussion in #528

**Comment by ricknjacky** [comment]
@notmandatory I'd like to work on this issue.

I'm new to this project and I just started learning rust to contribute here. I hope this will be a good starting point for contributing.

Can I take this up ? I'll also be glad to get a heads up of sorts.
Thanks.

**Comment by notmandatory** [comment]
Hi @ricknjacky welcome!  yes I'll put your name on this one. Leave a comment here or we can discuss on discord if you need help or have any questions.

**Comment by Eunoia1729** [comment]
@ricknjacky With your permission, can I take this forward ? 
I've made the updates and only, making a PR is remaining.

Thanks in advance !

Edit: I've opened a PR so we can collaborate better.

**Comment by notmandatory** [comment]
@ricknjacky if you're still interested in working on this issue please help test and review @Eunoia1729's PR.
