### ISSUE TITLE
Write own BIP39 implementation

### ISSUE THREAD

**Issue by jblachly** [bitcoindevkit/bdk#561]
As suggested in the code base:

https://github.com/bitcoindevkit/bdk/blob/adf7d0c126aab471d6c52cb3129c065c5c2a2063/src/keys/bip39.rs#L14-L17

I also recommend writing own BIP39 implementation.

In issue #399, BDK transitioned from `tiny-bip39` to `rust-bip39`, however, the latter package (which BDK now depends on) appears to be unmaintained or poorly maintained, with PRs and issues ignored for about a year.

https://github.com/rust-bitcoin/rust-bip39

At a minimum, BIP39 wordlists, and words -> entropy -> seed generation would be valuable.

**Comment by notmandatory** [comment]
@jblachly I think it's too late to add this as a 2022 summer of bitcoin project, but I'll tag it as a good first issue for someone new.

**Comment by jblachly** [comment]
Thanks; accidentally started with that template (there was no other feature request template) and didn't realize it would add an issue tag.

**Comment by notmandatory** [comment]
No problem, it's on my todo list to add an enhancement issue template. 😅

**Comment by violet360** [comment]
Hey, guys !!
I am a bitcoin enthusiast and an SoB participant who recently started with RUST and new to this project as well, I was looking for cool rust issues to work on so that I can improve my understanding and this one really caught my attention, I would love to work on this project.

**Comment by Eunoia1729** [comment]
Hi @violet360! 
I've been working on this since past few days. Hope we can review/discuss if I'm going in the right direction. 
I can make a draft PR.

**Comment by violet360** [comment]
Ok cool, for sure :)

**Comment by evanlinjin** [comment]
@violet360 @Eunoia1729 How is progress on this issue so far?

**Comment by danielabrozzoni** [comment]
@Eunoia1729 are you stll working on this? :)

**Comment by Eunoia1729** [comment]
Sorry for the late response. 
I didnt progress much after that. Anyone interested can start with it, I'll be happy to join or help in any way.

**Comment by vladimirfomene** [comment]
Hello @danielabrozzoni, has this been worked on? Can I pick it up?

**Comment by danielabrozzoni** [comment]
Nobody that I know of, you can pick it up :)

**Comment by atalw** [comment]
Hey, sorry that I didn't update here but I started working on this earlier [today](https://github.com/atalw/bdk/commits/bip-0039). Should I continue? Perhaps we could work together?

**Comment by vladimirfomene** [comment]
@atalw, yes we can work on it together. Can I reach out to you over discord? What is your discord handle?

**Comment by atalw** [comment]
Awesome. It's `atalw#3934`.

**Comment by notmandatory** [comment]
I know we have @evanlinjin 's PR #644 in progress for this. But want to ask the question, since we already moved off of `tiny-bip39` and we're using `rust-bitcoin/rust-bip39` , does it make sense to create our own implementation? what features are we missing in `rust-bip39` ? And if it's just a maintenance issue what needs to be updated and can we do PRs for those?

**Comment by jblachly** [comment]
> And if it's just a maintenance issue what needs to be updated and can we do PRs for those?

The problem is that the maintainer of rust-bitcoin/rust-bip39 is unresponsive to PRs

**Comment by notmandatory** [comment]
If there are no technical reason against using rust-bitcoin/rust-bip39 then should we maintain and use a fork in the `bitcoindevkit` org? Then we can get PRs we need merged and upstream can still pull them in if/when they want.

**Comment by jblachly** [comment]
> 



> should we maintain and use a fork in the `bitcoindevkit` org?

Sounds reasonable; alternatively if anyone has personal connections to org owners of rust-bitcoin we could lobby for an additional person to get admin permissions to the repository as co-maintainer

**Comment by notmandatory** [comment]
@jblachly I'm going to close this issue as the rust-bitcoin/rust-bip39 crate seems to be back on track with new releases. Happy to reopen if you think more discussion is needed.
