### ISSUE TITLE
Remove Database::flush() function

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#567]
Remove `Database::flush()` function added in #409 ~~and call it internally in the `keyvalue::Database` impl in functions that create or update Tree data~~. 

Currently only the `keyvalue::Database` impl does anything in the `Database::flush` function and @thunderbiscuit and I confirmed it needs to be called to fix https://github.com/bitcoindevkit/bdk-ffi/issues/114 on Android. But the `Database::flush` is not used or needed for the `Memory` or `Sqlite` databases, see also https://github.com/bitcoindevkit/bdk-ffi/pull/116#issuecomment-1065942085.

EDIT: as discussed in [#575](https://github.com/bitcoindevkit/bdk/pull/575#issuecomment-1078585739) for now it's enough to only remove the `Database::flush()` function. The auto-flushing is probably not the right approach at this time.

**Comment by danielabrozzoni** [comment]
Fixed by #575
