### ISSUE TITLE
Unable to use a SyncOptions progress call back for wallet.sync()

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#592]
**Describe the bug**  
This might be a Rust lang question rather than a bug. I'm trying to sync a wallet with something other than `SyncOptions::default()`, but when I use anything else I get a build error.

**To Reproduce**  
 I tried creating a `LogProgress` instance of `Progress` this way:
```rust
#[test]
     fn test_sync_simple() {
          ...
          let progress = Some(Box::new(crate::blockchain::log_progress()));     
          let sync_options = SyncOptions {
                 progress
          };
          wallet.sync(&blockchain, sync_options).unwrap();
          ...
     }
```

But I get the build error:
```shell
   error[E0308]: mismatched types
   --> src/testutils/blockchain_tests.rs:420:21
    |
420 |                       progress
    |                       ^^^^^^^^ expected trait object `dyn blockchain::Progress`, found struct `LogProgress`
    |
   ::: src/blockchain/electrum.rs:323:1
    |
   ...
   = note: expected enum `std::option::Option<Box<(dyn blockchain::Progress + 'static)>>`
               found enum `std::option::Option<Box<LogProgress>>`
```

**Expected behavior**  
I expect it to build with one of the pre-canned SyncOptions progress structs.

**Build environment**  
 - BDK tag/commit: v0.18.0 
 - OS+version: Linux 
 - Rust/Cargo version: 1.58.0
 - Rust/Cargo toolchain: stable-x86_64-unknown-linux-gnu

**Additional context**  
If this is something I'm doing wrong in Rust then I'll add an example in our tests so others don't run into the same issue.

**Comment by notmandatory** [comment]
@LLFourn If you have a minute can you help me out with this one?

**Comment by LLFourn** [comment]
@notmandatory looks like a case of rust type inference behaving less than awesome. If you do:

```rust
let progress = Some(Box::new(crate::blockchain::log_progress()) as Box<(dyn blockchain::Progress + 'static)>);     
```

what happens?

**Comment by notmandatory** [comment]
That works! I'll use the approach in the bdk 0.18.0 upgrade I'm doing for bdk-ffi.

I'll also add a bdk test with this construction, but do you think there's something in the API we can do to make it easier?

**Comment by LLFourn** [comment]
@notmandatory I think we can probably require that `Progress` is `static` here. Dunno if that will fix this but it will at least make it a bit easier to type.

Do you have to do this if you directly inline the construction to the field?

**Comment by notmandatory** [comment]
Ah ha, yes if I directly inline the construction to the field it does work without the type coercion:

```rust
     let sync_options = SyncOptions {
          progress: Some(Box::new(crate::blockchain::log_progress()))
      };
```

**Comment by notmandatory** [comment]
These suggestions worked for me, closing issue. Thanks @LLFourn !
