### ISSUE TITLE
Add `blockchain::GetBlockHash` trait and implement for blockchains

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#603]
The new trait should have a function to get a block hash at a given height. The [Esplora API], [Electrum API], RPC, and CBF blockchains should all support getting a block hash at a given height.  This feature is needed to help support wallets that also use LDK, See https://github.com/bitcoindevkit/bdk-swift/issues/10.

[Esplora API]:https://github.com/Blockstream/esplora/blob/master/API.md#get-block-heightheight
[Electrum API]:https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-block-header

**Comment by vladimirfomene** [comment]
Hello @notmandatory , can I take this one up?

**Comment by notmandatory** [comment]
Here's the LDK API we're working with: https://lightningdevkit.org/tutorials/build_a_node_in_java/#11-initialize-the-channelmanager

**Comment by thunderbiscuit** [comment]
And just for reference [on the Rust side](https://lightningdevkit.org/tutorials/build_a_node_in_rust/).
