### ISSUE TITLE
Support lighting's special feerates

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoindevkit/bdk#608]
Lightning is a special snowflake and does fees in satoshis per 1000-weight-units. It'd be nice if BDK supported that, and while we're at it maybe satoshis per 1000-vbytes, which also seems to be missing.

One concern with lightning, that doesn't appear to be handled in the BDK feerate logic is that rounding can push below the bitcoin core 1 sat/vbyte limit, so lightning actually requires a minimum of 253 sats-per-1000-weight. I'm not sure how best to capture this dozen in the BDK API, but I guess just being careful when calculating the concrete fee.

**Comment by vladimirfomene** [comment]
@notmandatory , let me take this up.
