### ISSUE TITLE
Remove partial signatures after finalizing the psbt

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/bdk#612]
Ideally we should remove the partial signatures after we've managed to finalize the tx.

Since now we automatically finalize and don't remove the signatures, we should add two new `SignOptions`:

- `do_not_finalize`: just sign without trying to finalize at the end
- `do_not_remove_partial_sigs`: even if you manage to finalize, leave the sigs there

The current default is `(false, true)`, but maybe we should switch to `(false, false)` since that's more in line with what BIP174 describes

**Comment by kafaichoi** [comment]
May I I work on this issue?(probably take 1-2 weeks though as I only has time in weekend)

**Comment by afilini** [comment]
Sure, no worries about the time, it's not very high priority in my opinion.

I'll assign it to you for now

**Comment by notmandatory** [comment]
fixed by #621
