### ISSUE TITLE
Disambiguate descriptor type in Wallet::new

### ISSUE THREAD

**Issue by ok300** [bitcoindevkit/bdk#617]
**Describe the bug**  

`Wallet::new` accepts two kinds of descriptors:
- `Descriptor<DescriptorPublicKey, KeyMap, ValidNetworks>` (the result of the `descriptor!()` macro)
  - resulting in a wallet with signers
- `ExtendedDescriptor` (the result of calling `.into_wallet_descriptor()` on the above type)
  - resulting in a watch-only wallet with no signers

This can be very confusing for new people looking into bdk, because the 2nd approach above seems the intuitive one (a wallet should need a wallet descriptor). However later on, when `wallet.sign()` has no effect, its not clear where the mistake lies.

One solution is to not allow `ExtendedDescriptor` as a possible arg in the wallet constructor. This would force callers to use the other kind of descriptor which, depending how it's built, can also cover watch-only wallets (for example, `wsh(multi(x, <only pubkeys>))`).

**To Reproduce**  
- create a wallet for Alice in a `1-of-2` multisig
  - create a `let desc = descriptor!( wsh(multi(1, xprvAlice, xpubBob)) ).unwrap();`
  - from it, create a `let (wallet_desc, keymap) = desc.into_wallet_descriptor(&secp, network).unwrap();`
  - create wallet `let wallet = Wallet::new(wallet_desc, None,  network, MemoryDatabase::new())?;`
- try to create a tx and sign the psbt
- realize that signing had no effect and the psbt is not finalized, not even signed, even though `xprvAlice` was used in the wallet descriptor

**Expected behavior**  
Either:
- ideally signing should fail with a `NoSignersFound` type of error (it could include a more detailed reason like `You cannot sign with a watch-only wallet`)
- or `Wallet::new` shouldn't accept the `desc.into_wallet_descriptor(..)` result as arg
- or a sort of note in the `Wallet::new` rustdoc telling callers what to use if they want to be able to sign
- or perhaps a separate constructor like `Wallet::new_watchonly` which would accept the type of descriptor with no keymap
- or maybe rename `into_wallet_descriptor` => `into_watchonly_wallet_descriptor`

**Build environment**  
 - BDK tag/commit: `v0.18.0` and latest `v.0.19.0-dev`
 - OS+version: tested on Debian 11
 - Rust/Cargo version: `1.61.0`
 - Rust/Cargo target: `x86_64-unknown-linux-gnu`

**Comment by notmandatory** [comment]
This sounds like a documentation issue where we should have more examples of how to create descriptors, and how to sign and finalize them. Below is some sample code that I think demonstrates how to do what you're trying to do, you don't need to use `desc.into_wallet_descriptor(..)`. Does this help? 

```rust
use bdk::bitcoin::secp256k1::Secp256k1;
use bdk::bitcoin::{Address, Network};
use bdk::blockchain::{Blockchain, ElectrumBlockchain};
use bdk::database::MemoryDatabase;
use bdk::descriptor;
use bdk::electrum_client;
use bdk::keys::DescriptorSecretKey;
use bdk::wallet::{AddressIndex, Wallet};
use bdk::{SignOptions, SyncOptions};
use core::str::FromStr;

fn main() {
    let secp = Secp256k1::new();
    let xprv_alice = DescriptorSecretKey::from_str("tprv8ZgxMBicQKsPdAxV6rMd9Vx9qQobFxT4ykwTgMVLMiyNP7ds9BApjr19hfYGi8hqatUskHfrSyXWe2J4oYWvpggkPVYcfhDZEwpPA9GtcPc/*").unwrap();
    let xprv_bob = DescriptorSecretKey::from_str("tprv8ZgxMBicQKsPdmzBX2J2MSDgwFQQ8erxTa1UwJ7P4zTJz9m8jMpkFkcMe8oaqdc9EkHoPRHoQLwaaMHrjbhSZXG8dPKKXGAYF3nHsrKPEyD/*").unwrap();
    let xpub_bob = xprv_bob.as_public(&secp).unwrap();
    let (desc, keys, networks) = descriptor!(wsh(multi(1, xprv_alice, xpub_bob))).unwrap();
    println!(
        "descriptor = {}\n\nkeys = {:?}\n\nnetworks = {:?}\n",
        &desc.to_string(),
        &keys.keys().last().unwrap().to_string(),
        networks
    );
    let wallet = Wallet::new(
        (desc, keys, networks),
        None,
        Network::Testnet,
        MemoryDatabase::new(),
    ).unwrap();
    let address = wallet.get_address(AddressIndex::New).unwrap();
    println!("deposit address = {}", address.to_string());
    let client = electrum_client::Client::new("ssl://electrum.blockstream.info:60002").unwrap();
    let blockchain = ElectrumBlockchain::from(client);
    wallet.sync(&blockchain, SyncOptions::default()).unwrap();
    let balance = wallet.get_balance().unwrap();
    println!("balance = {}", balance);
    let (mut psbt, tx_details) = {
        let mut builder = wallet.build_tx();
        builder.add_recipient(
            Address::from_str("tb1ql7w62elx9ucw4pj5lgw4l028hmuw80sndtntxt")
                .unwrap()
                .script_pubkey(),
            1000,
        );
        builder.finish().unwrap()
    };
    println!("tx_details = {:?}", &tx_details);
    let signed = wallet.sign(&mut psbt, SignOptions::default()).unwrap();
    println!("psbt signed = {}", signed);
    let finalized = wallet
        .finalize_psbt(&mut psbt, SignOptions::default())
        .unwrap();
    println!("psbt finalized = {}", finalized);
    if finalized {
        blockchain.broadcast(&psbt.extract_tx()).unwrap();
        wallet.sync(&blockchain, SyncOptions::default()).unwrap();
        let balance = wallet.get_balance().unwrap();
        println!("balance = {}", balance);
    }
}
```
```shell
## this is a second run after sending testnet sats to the wallet deposit address
cargo run
...
descriptor = wsh(multi(1,tpubD6NzVbkrYhZ4WdzGzW2DYucGQSKXRHdyZ4YExsXdmzmmDbtdmZzQvLd1snodpguutA9i79CxycqQYp7fhJtvCRfUfk7jCLqghFBCyW2fEbv/*,tpubD6NzVbkrYhZ4XF1yQfxckqsoWGvLHz3s2scGDp9gVGFhpe1uMkeLSFEDpGwfKBpiPxVF87WSU5CwmSJh4LSdoq9cCrpPEZG5HtNZi3sFbJb/*))#ejp49ugz

keys = "tpubD6NzVbkrYhZ4WdzGzW2DYucGQSKXRHdyZ4YExsXdmzmmDbtdmZzQvLd1snodpguutA9i79CxycqQYp7fhJtvCRfUfk7jCLqghFBCyW2fEbv/*"

networks = {Signet, Testnet, Regtest}

deposit address = tb1qm89h025prjszq0h0yzqlh8czkz2pt33zezzt3sd3qzaw2eaa3r5qnt8wlw
balance = 30842
tx_details = TransactionDetails { transaction: None, txid: 7ea89c94520e0b2ca492df4c821153d41a45c20f2d4a5b240dd28d3c9929008a, received: 8842, sent: 10005, fee: Some(163), confirmation_time: None }
psbt signed = true
psbt finalized = true
balance = 29679
```

**Comment by ok300** [comment]
Thank you @notmandatory, that's awesome. Yes it helps, multisig works now.

**Comment by ok300** [comment]
@notmandatory on an unrelated note: the RSS feed on your website notmandatory.org isn't working. Wanted to add it to my feed reader but 404 not found.

**Comment by notmandatory** [comment]
Thanks for heads up about my RSS feed, it's a bit out of date but will get it fixed 🙂.

EDIT: Fixed!
