### ISSUE TITLE
Taproot / Schnorr

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#63]
This is a tracking issue for other issues and PRs related to supporting Taproot in BDK.

## Dependencies

[Overall rust-bitcoin org tracking project](https://github.com/orgs/rust-bitcoin/projects/3#card-53894767)

### rust-bitcoin/rust-bitcoin 

- [x] https://github.com/rust-bitcoin/rust-bitcoin/issues/503

### rust-bitcoin/rust-miniscript 

- [x] https://github.com/rust-bitcoin/rust-miniscript/pull/267
- [x] https://github.com/rust-bitcoin/rust-miniscript/pull/275
- [x] https://github.com/rust-bitcoin/rust-miniscript/pull/278
- [ ] https://github.com/rust-bitcoin/rust-miniscript/issues/182

## Send to Single Signature TR Address

- [x] bitcoindevkit/bdk#402  
- [ ] bitcoindevkit/bdk_wallet#189

## Create Single Signature TR Descriptor Wallet

- [ ]  bitcoindevkit/bdk#463

**Comment by jrawsthorne** [comment]
Upstream issue to track changes needed for taproot https://github.com/rust-bitcoin/rust-bitcoin/issues/503
