### ISSUE TITLE
Mobile hardware security

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#64]
- Secure enclave key storage and signing
- Hardware wallet / HWI
- HSM runtime support like the nShield

This may need to be moved or companion issues created in bdk-jni (and future bdk-ios) repos

**Comment by remyers** [comment]
@afilini has a demo on telegram: "HWI is actually fairly easy to integrate, ~100 lines of code at most. Obviously it doesn't work on mobile devices, but for desktop wallets it's not that bad"

**Comment by notmandatory** [comment]
Closing this in favor of platform specific issues in the `bdk-kotlin` (android) and `bdk-swift` (ios) repos, once those projects are ready to tackle this.
