### ISSUE TITLE
codecov doesn't cover the blockchain module

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#696]
**Describe the bug**  
Codecoverage says that out coverage for the blockchain module is 1.87%, even do we do have tests covering that module. It might be configured in the wrong way. 

**To Reproduce**  
Open https://app.codecov.io/gh/bitcoindevkit/bdk, look at the end of the page, where it shows coverage for the different directories:

![Selection_093](https://user-images.githubusercontent.com/25042473/182366663-ea44a1f7-f2ad-41e0-8bb4-25359014f3ec.png)

**Expected behavior**  
Decent blockchain module coverage

**UPDATE**: after #708, we can see most of the blockchain module coverage at https://coveralls.io/github/bitcoindevkit/bdk?branch=master . More work is needed for including the missing blockchains (esplora, compact filters) in the coverage. See https://github.com/bitcoindevkit/bdk/issues/696#issuecomment-1235908073

**Comment by rajarshimaitra** [comment]
The problem is we are separately specifying a code coverage job which only includes features `all-keys,compiler,esplora,ureq,compact_filters --no-default-features`.. 

So our code coverage reports are rightly incomplete.. The right thing to do here is run all the tests in one job and report coverage from there..

**Comment by notmandatory** [comment]
The work done for #708 should also help address this issue.

**Comment by danielabrozzoni** [comment]
With #708 we cover most of the blockchain modules, but esplora. I'll update the title accordingly. The solution is probably to run the tests multiple time and then merge the reports.

**Comment by danielabrozzoni** [comment]
I've tried merging the reports in https://github.com/bitcoindevkit/bdk/pull/748, but it doesn't seem to be working very well, and there's not much we can do (see https://github.com/bitcoindevkit/bdk/pull/748#issuecomment-1242721040). I'm closing this for now.
