### ISSUE TITLE
We shouldn't mark replaced transactions as spent 

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#700]
See https://github.com/bitcoindevkit/bdk/pull/683/files#r934019304

Maybe we should have a `is_replaced` field in LocalUtxo

**Comment by Weijun-H** [comment]
Hi there, does this issue still need to be fixed?

**Comment by danielabrozzoni** [comment]
> Hi there, does this issue still need to be fixed?

BDK is still affected, but we are fixing this in bdk_core (https://bitcoindevkit.org/blog/road-to-bdk-1/)
