### ISSUE TITLE
Add `allow_shrinking` to a non-signed, non-broadcasted transaction

### ISSUE THREAD

**Issue by terror** [bitcoindevkit/bdk#714]
We want to be able to use `TxBuilder::allow_shrinking()` on a transaction that is created using `Wallet::build_tx()` but currently `TxBuilder::allow_shrinking()` is only allowed on transactions built with `Wallet::build_fee_bump(txid)`, which requires a previous transaction to be signed and broadcasted to the network. Is there a way to use `TxBuilder::allow_shrinking()` without signing or broadcasting a transaction?

**Comment by rajarshimaitra** [comment]
Hey @terror. `allow_shrinking()` is an api that is specifically intended to be used in fee bumping situation. Although the function of the api is very straight forward. It just removes the specified script from recipient list and adds it into `drain_to`.. 

https://github.com/bitcoindevkit/bdk/blob/9f9ffd0efd94f172bf28ca23477a4b13757ac4b0/src/wallet/tx_builder.rs#L655-L656

And then goes on building the transaction as per regular create transaction logic.
 
So maybe you can use `drain_to` on transaction param directly to have the intended effect you are looking for??

**Comment by terror** [comment]
> Hey @terror. `allow_shrinking()` is an api that is specifically intended to be used in fee bumping situation. Although the function of the api is very straight forward. It just removes the specified script from recipient list and adds it into `drain_to`..
> 
> https://github.com/bitcoindevkit/bdk/blob/9f9ffd0efd94f172bf28ca23477a4b13757ac4b0/src/wallet/tx_builder.rs#L655-L656
> 
> And then goes on building the transaction as per regular create transaction logic.
> 
> So maybe you can use `drain_to` on transaction param directly to have the intended effect you are looking for??

Sweet, using the implementation does what we want, thanks!
