### ISSUE TITLE
Remove genesis_block lazy initialization

### ISSUE THREAD

**Issue by RCasatta** [bitcoindevkit/bdk#752]
Remove this genesis block initialization:

https://github.com/bitcoindevkit/bdk/blob/7b12f35698ff468f676665704fb274c36cb305df/src/blockchain/compact_filters/store.rs#L40-L45

by using https://docs.rs/bitcoin/0.29.1/bitcoin/blockdata/constants/fn.genesis_block.html#

After that lazy_static could probably be removed or set as dev-dep only

**Comment by notmandatory** [comment]
closed by #756
