### ISSUE TITLE
Release 0.23.0

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/bdk#769]
### Summary

This release brings new utilities functions on PSBTs like `fee_amount()` and `fee_rate()` and migrates BDK to use our new external esplora client library. As always many bug fixes, docs and tests improvement are also included.

### Commit

0facb99c8143ef20bcd4891f19b570c61112622c

## What's Changed
* Update electrum-client to 0.11.0 by @afilini in https://github.com/bitcoindevkit/bdk/pull/737
* Change configs for source-base code coverage by @wszdexdrf in https://github.com/bitcoindevkit/bdk/pull/708
* Run code coverage on every PR by @danielabrozzoni in https://github.com/bitcoindevkit/bdk/pull/747
* Add psbt_signer.rs example by @notmandatory in https://github.com/bitcoindevkit/bdk/pull/744
* Add fee_amount() and fee_rate() functions to PsbtUtils trait by @notmandatory in https://github.com/bitcoindevkit/bdk/pull/728
* Improve docs regarding PSBT finalization by @tnull in https://github.com/bitcoindevkit/bdk/pull/753
* Add tests to improve coverage by @vladimirfomene in https://github.com/bitcoindevkit/bdk/pull/745
* Enable signing taproot transactions with only `non_witness_utxos` by @afilini in https://github.com/bitcoindevkit/bdk/pull/757
* Add datatype for is_spent sqlite column by @vladimirfomene in https://github.com/bitcoindevkit/bdk/pull/713
* Update compiler example to a Policy example by @rajarshimaitra in https://github.com/bitcoindevkit/bdk/pull/730
* Remove redundant duplicated keys check by @afilini in https://github.com/bitcoindevkit/bdk/pull/761
* Fix the release process by @afilini in https://github.com/bitcoindevkit/bdk/pull/754
* Remove genesis_block lazy initialization by @shobitb in https://github.com/bitcoindevkit/bdk/pull/756
* Add vscode filter to gitignore by @evanlinjin in https://github.com/bitcoindevkit/bdk/pull/762
* Fix `Wallet::descriptor_checksum` to actually return the checksum by @evanlinjin in https://github.com/bitcoindevkit/bdk/pull/763
* Use the esplora client crate by @afilini in https://github.com/bitcoindevkit/bdk/pull/764

#### On the day of the feature freeze

Change the `master` branch to the next MINOR+1 version:

- [x] Switch to the `master` branch.
- [x] Create a new PR branch called `bump_dev_MAJOR_MINOR+1`, eg. `bump_dev_0_22`.
- [x] Bump the `bump_dev_MAJOR_MINOR+1` branch to the next development MINOR+1 version.
  - Change the `Cargo.toml` version value to `MAJOR.MINOR+1.0`.
  - The commit message should be "Bump version to MAJOR.MINOR+1.0".
- [x] Create PR and merge the `bump_dev_MAJOR_MINOR+1` branch to `master`. #768 
  - Title PR "Bump version to MAJOR.MINOR+1.0".

Create a new release branch and release candidate tag:

- [x] Double check that your local `master` is up-to-date with the upstream repo.
- [x] Create a new branch called `release/MAJOR.MINOR+1` from `master`.
- [x] Bump the `release/MAJOR.MINOR+1` branch to `MAJOR.MINOR+1.0-rc.1` version.
  - Change the `Cargo.toml` version value to `MAJOR.MINOR+1.0-rc.1`.
  - The commit message should be "Bump version to MAJOR.MINOR+1.0-rc.1".
- [x] Add a tag to the `HEAD` commit in the `release/MAJOR.MINOR+1` branch.
  - The tag name should be `vMAJOR.MINOR+1.0-rc.1`
  - Use message "Release MAJOR.MINOR+1.0 rc.1".
  - Make sure the tag is signed, for extra safety use the explicit `--sign` flag.
- [x] Push the `release/MAJOR.MINOR` branch and new tag to the `bitcoindevkit/bdk` repo.
  - Use `git push --tags` option to push the new `vMAJOR.MINOR+1.0-rc.1` tag.

If any issues need to be fixed before the *MAJOR.MINOR+1.0* version is released:

- [ ] Merge fix PRs to the `master` branch.
- [ ] Git cherry-pick fix commits to the `release/MAJOR.MINOR+1` branch.
- [ ] Verify fixes in `release/MAJOR.MINOR+1` branch.
- [ ] Bump the `release/MAJOR.MINOR+1` branch to `MAJOR.MINOR+1.0-rc.x+1` version.
  - Change the `Cargo.toml` version value to `MAJOR.MINOR+1.0-rc.x+1`.
  - The commit message should be "Bump version to MAJOR.MINOR+1.0-rc.x+1".
- [ ] Add a tag to the `HEAD` commit in the `release/MAJOR.MINOR+1` branch.
  - The tag name should be `vMAJOR.MINOR+1.0-rc.x+1`, where x is the current release candidate number.
  - Use tag message "Release MAJOR.MINOR+1.0 rc.x+1".
  - Make sure the tag is signed, for extra safety use the explicit `--sign` flag.
- [ ] Push the new tag to the `bitcoindevkit/bdk` repo.
  - Use `git push --tags` option to push the new `vMAJOR.MINOR+1.0-rc.x+1` tag.

#### On the day of the release

Tag and publish new release:

- [x] Bump the `release/MAJOR.MINOR+1` branch to `MAJOR.MINOR+1.0` version.
  - Change the `Cargo.toml` version value to `MAJOR.MINOR+1.0`.
  - The commit message should be "Bump version to MAJOR.MINOR+1.0".
- [x] Add a tag to the `HEAD` commit in the `release/MAJOR.MINOR+1` branch.
  - The tag name should be `vMAJOR.MINOR+1.0`
  - The first line of the tag message should be "Release MAJOR.MINOR+1.0".
  - In the body of the tag message put a copy of the **Summary** and **Changelog** for the release.
  - Make sure the tag is signed, for extra safety use the explicit `--sign` flag.
- [x] Wait for the CI to finish one last time.
- [x] Push the new tag to the `bitcoindevkit/bdk` repo.
- [x] Publish **all** the updated crates to crates.io.
- [x] Create the release on GitHub.
  - Go to "tags", click on the dots on the right and select "Create Release".
  - Set the title to `Release MAJOR.MINOR+1.0`.
  - In the release notes body put the **Summary** and **Changelog**.
  - Use the "+ Auto-generate release notes" button to add details from included PRs.
  - Until we reach a `1.0.0` release check the "Pre-release" box.
- [x] Make sure the new release shows up on [crates.io] and that the docs are built correctly on [docs.rs].
- [x] Announce the release, using the **Summary**, on Discord, Twitter and Mastodon.
- [x] Celebrate 🎉

[Semantic Versioning]: https://semver.org/
[crates.io]: https://crates.io/crates/bdk
[docs.rs]: https://docs.rs/bdk/latest/bdk
["keep a changelog"]: https://keepachangelog.com/en/1.0.0/

**Comment by notmandatory** [comment]
Looks like everything went smoothly, closing the issue.
