### ISSUE TITLE
[Bindings] Allow to generate keys directly without having to rely on mnemonics

### ISSUE THREAD

**Issue by kirillzh** [bitcoindevkit/bdk#786]
**Describe the enhancement**  
Current bindings expose API for generating and deriving master key which requires generation of mnemonic first. This enhancement request proposes to add bindings API which allows to skip mnemonics altogether and can generate master [directly](https://docs.rs/bdk/0.15.0/bdk/keys/trait.GeneratableKey.html).

**Use case**  
Our product does not rely on mnemonics at all - we don't expose mnemonics to customers and implement backups in a different way by fully relying on the master key. With that, we are currently generating and storing mnemonic unnecessarily which is wasteful and less efficient, when comparing to derive the key directly.

**Comment by jesseposner** [comment]
Another benefit is being able to use the full 512 bits of entropy for BIP32, instead of just 256 bits that the mnemonic limits us to.

**Comment by thunderbiscuit** [comment]
If I understand your request correctly, I think this should be fairly straightforward to implement in the bindings. Let me know if this is what you have in mind: you provide the initial entropy, and the bindings would expose an API to generate the BIP32 root key from that entropy. You'd then use this extended master key and create a descriptor from it, which you'd feed to the wallet.

One question: do I understand correctly that you'd like to provide the entropy yourself, or would you rather BDK creates the root key for you and simply returns it to you so you can save it? (basically wondering if you're after the master key itself without going through the mnemonic or the _creation_ of that master key as well—we can certainly do both I just want to make sure I understand your request).

**Comment by jesseposner** [comment]
We want something like this: https://github.com/bitcoindevkit/bdk/blob/ea47d7a35bf3c3a1592b473ae93102e52ddf47f4/src/keys/mod.rs#L955

where we can pass an entropy length and get back a master key.

**Comment by thunderbiscuit** [comment]
Yep gotcha. I was looking at this indeed, which might do exactly what we'd need: [`ExtendedPrivKey::new_master()`](https://docs.rs/bitcoin/0.29.1/bitcoin/util/bip32/struct.ExtendedPrivKey.html#method.new_master)

```rust
impl ExtendedPrivKey {
    /// Construct a new master key from a seed value
    pub fn new_master(network: Network, seed: &[u8]) -> Result<ExtendedPrivKey, Error> {
    /// ...
}
```

This method in fact allows for any length of initial entropy you want to give it and [passes it through the Hmac-512](https://docs.rs/bitcoin/0.29.1/src/bitcoin/util/bip32.rs.html#532-545).

And in Kotlin the function signature might be something like
```kotlin
fun generateMasterKeyFromEntropy(network: Network, entropy: ByteArray): DescriptorSecretKey
```

**Comment by jesseposner** [comment]
That would be useful if we want to use a custom RNG and generate our own seed, but it's also nice to have an API that uses the default rng like here: https://github.com/bitcoindevkit/bdk/blob/8fbe40a9181cc9e22cabfc04d57dac5d459da87d/src/keys/mod.rs#L631-L637

**Comment by thunderbiscuit** [comment]
Oh I see ok! Sorry I misread your line above about passing an _entropy length_ instead of just entropy ("where we can pass an entropy length and get back a master key."). The example linked (the `generate_with_entropy_default()`) also uses entropy to create the key so I got confused there, but now with the example on line 631 to 637 it's all clear.

Yes I think we can most definitely provide an API to generate a `DescriptorSecretKey` struct we have on the FFI layer directly, without going through any mnemonics.

**Comment by thunderbiscuit** [comment]
Linking bitcoindevkit/bdk-ffi#218.

**Comment by thunderbiscuit** [comment]
Closing this now. More discussion on API shape in bitcoindevkit/bdk-ffi#218.
