### ISSUE TITLE
Report progress on blockchains that don't currently report intermediate progress

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#798]
**Describe the enhancement**  
Blockchains electrum and esplora don't currently update the progress callback. For apps that expect progress this causes a problem. The blockchains that don't report progress should just call the progress call back with 0 and then 100 when done.

**Use case**  
On apps that let the user select which blockchain there needs to be at least starting and ending progress call backs even if the underlying blockchain doesn't have intermediate progress updates.

**Additional context**
https://github.com/bitcoindevkit/bdk/blob/5c42102c79730ea1d9b5c55045dbf9afcf72e27e/src/blockchain/electrum.rs#L121
https://github.com/bitcoindevkit/bdk/blob/5c42102c79730ea1d9b5c55045dbf9afcf72e27e/src/blockchain/esplora/blocking.rs#L121
https://github.com/bitcoindevkit/bdk/blob/5c42102c79730ea1d9b5c55045dbf9afcf72e27e/src/blockchain/esplora/async.rs#L139

**Comment by LLFourn** [comment]
FWIW the plan is to remove  `Progress` from `bdk` in `v1`. Instead, you can attach to the iterator that electrum/esplora type syncs use and as they consume more addresses you can see them with `.inspect`: https://github.com/LLFourn/bdk_core_staging/blob/c1fea6df1c0cb8ee514ec67b50b67ff12e430c8d/bdk_core_example/src/main.rs#L200

This effectively allows you to get a callback any time a new address is consumed by them. Of course not all blockchain data is fetched in the same way but for those that iterate over script pubkeys and find related transactions this is a very convenient way.

**Comment by notmandatory** [comment]
Thanks, make sense not to change anything now then, but I will leave this issue open as a place holder to create example code to demo now to do this once we have the `v1` apis out. Or possibly implement something for the `bdk_compat` layer if we're going to have that as a bridge for pre-`v1` apps.

**Comment by notmandatory** [comment]
Related to #1153 and #1194.
