### ISSUE TITLE
`Balance` should use `bitcoin::Amount`

### ISSUE THREAD

**Issue by tnull** [bitcoindevkit/bdk#823]
**Describe the bug**  
Currently, the `Balance` type returned by `get_balance()` only uses non-descript `u64`s, while not even stating a denomination anywhere in the documentation (I assume it's sats?). To avoid any confusion and make this much less error prone BDK should reuse the `Amount` type provided by `rust-bitcoin`.

Also, the documentation could generally be improved, e.g., clarifying what exactly it means that some funds are `immature`/`trusted_pending`/`untrusted_pending`/`confirmed`.

**To Reproduce**  
Call `Wallet::get_balance()`.

**Expected behavior**  
Receive a meaningful return value.

**Additional context**  
This is in particular confusing since similar `u64` values are used in the Lightning space very often to denominate millisatoshis. It's best practice to append `_msat` to the names of such variables, which however still doesn't make use of the type system to avoid any conversion errors (we can't, as `Amount` doesn't  allow to express millisatoshis). As BDK doesn't have to deal with millisatoshis, it really should make use of `Amount` here.

**Comment by LLFourn** [comment]
If we're going to return it in balance we should probably use it everywhere. The main downside with this is that `rust-bitcoin` itself doesn't use amounts everywhere e.g. TxOut's value field so there'll still be a some converting to do.

**Comment by tnull** [comment]
I mean I'd def. be +1 for more making use of the type system everywhere possible to avoid any conversion errors, but maybe `Balance` is a good place to start out? Or would BDK Core be able to adopt and introduce `Amount` everywhere?

**Comment by notmandatory** [comment]
Discussed in team chat, this would be a good change for bdk_core 1.0 release since it's a big API break.

**Comment by notmandatory** [comment]
See also: https://github.com/bitcoindevkit/bdk/issues/797#issuecomment-1467921897

**Comment by notmandatory** [comment]
I re-tagged this as an enhancement since balances work, just needs a better API.

**Comment by oleonardolima** [comment]
dev call: I'll give it a try on this one
