### ISSUE TITLE
Failed to build this project using wasm-pack

### ISSUE THREAD

**Issue by h76oeI6pMxU9g4p8aCpc6Q** [bitcoindevkit/bdk#843]
I already done all prerequisities of the wasm-pack by following to their guide.
https://rustwasm.github.io/wasm-pack/book/prerequisites/index.html

Environment:
- Ubuntu 22.04
- rustc 1.66.1
- wasm-pack 0.10.3
- bdk 0.26.0 (also tested using master branch)

Run "wasm-pack build" on the "bdk 0.26.0" project root

**The compilation process have stopped each time when "Compiling electrum-client v0.12.0"**

[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling electrum-client v0.12.0
error[E0599]: no method named `writev` found for struct `UdpSocket` in the current scope
   --> /home/vscode/.cargo/registry/src/github.com-1ecc6299db9ec823/electrum-client-0.12.0/src/socks/v5.rs:498:21
    |
498 |         self.socket.writev([&header[..len + 3], buf])
    |                     ^^^^^^ method not found in `UdpSocket`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `WritevExt` defines an item `writev`, perhaps you need to implement it
   --> /home/vscode/.cargo/registry/src/github.com-1ecc6299db9ec823/electrum-client-0.12.0/src/socks/writev.rs:4:1
    |
4   | pub trait WritevExt {
    | ^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `readv` found for struct `UdpSocket` in the current scope
   --> /home/vscode/.cargo/registry/src/github.com-1ecc6299db9ec823/electrum-client-0.12.0/src/socks/v5.rs:504:31
    |
504 |         let len = self.socket.readv([&mut header, buf])?;
    |                               ^^^^^ method not found in `UdpSocket`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `WritevExt` defines an item `readv`, perhaps you need to implement it
   --> /home/vscode/.cargo/registry/src/github.com-1ecc6299db9ec823/electrum-client-0.12.0/src/socks/writev.rs:4:1
    |
4   | pub trait WritevExt {
    | ^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0599`.
error: could not compile `electrum-client` due to 2 previous errors
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"

**Comment by notmandatory** [comment]
To use BDK with WASM you must use the Esplora blockchain client. This is because the WASM sandbox only allows HTTP(S) connections and does not support raw socket connections which the Electrum protocol requires.

**Comment by notmandatory** [comment]
@Bzvwf16WSDKoSZd8 I'm closing this issue per above comment. If you're still getting and error after disabling electrum and enabling the esplora client (--no-default-features --features use-esplora-async) then comment here and we can see if it needs to be reopened.
