### ISSUE TITLE
Improving the documentation for TxBuilder

### ISSUE THREAD

**Issue by prakharjain-slice** [bitcoindevkit/bdk#856]
**Describe the enhancement**  
Documentation regarding absolute fee and fee rate is little unclear in BDK docs. Common concerns are:
- Is absolute fee in sats or btc?
- If we add both absolute fee and fee rate while building the transaction which will be honoured?

**Use case**  
This documentation will help users in better understanding of Tx object and can optimise their transaction fees.

**Comment by notmandatory** [comment]
See also discussion in #823

**Comment by roy9495** [comment]
Can someone please review this #957

**Comment by 15IITian** [comment]
Is it appropriate to close this issue as  IMO all of its tasks are completed.

**Comment by danielabrozzoni** [comment]
https://github.com/bitcoindevkit/bdk/pull/1159 still needs to be merged, but CI is broken

**Comment by notmandatory** [comment]
fixed by #957
