### ISSUE TITLE
Provide easy way for wallet to connect to your own full node

### ISSUE THREAD

**Issue by moneyball** [bitcoindevkit/bdk#86]
I suggest adding this to the roadmap on the website.

Inspired by this tweet https://twitter.com/matt_odell/status/1286659125322162176?s=19

"All wallets should have the option to use your own node easily by simply scanning a QR code or pasting a connection code."

The BDK can build this and make it easy-to-use / default for any wallet based on BDK.

**Comment by tcharding** [comment]
Can we close this issue since `RpcBlockchain` exists now?
