### ISSUE TITLE
[enhancement] Make Wallet shareable across threads

### ISSUE THREAD

**Issue by matthunz** [bitcoindevkit/bdk#864]
**Describe the enhancement**  
Currently the `Wallet` struct uses a combination of `Arc`s and a `RefCell` in the following way
```rust
pub struct Wallet<D> {
    descriptor: ExtendedDescriptor,
    change_descriptor: Option<ExtendedDescriptor>,

    signers: Arc<SignersContainer>,
    change_signers: Arc<SignersContainer>,

    network: Network,

    database: RefCell<D>,

    secp: SecpCtx,
}
```

This is confusing because those `Arc` fields can be shared across threads but the `RefCell` prevents this type from implementing `Sync`. Also I can't figure out why the RefCell is required here. Is it totally required to have wallet methods act on a shared reference rather than a mutable one? I believe we should commit to either `Rc` and `!Sync` or `Arc` and `Sync`.

For example:

```rust
pub struct Wallet<D> {
    descriptor: ExtendedDescriptor,
    change_descriptor: Option<ExtendedDescriptor>,

    signers: Rc<SignersContainer>,
    change_signers: Rc<SignersContainer>,

    network: Network,

    database: D,

    secp: SecpCtx,
}
```

**Use case**  
For my use case it would be easier to share this struct with a Mutex or something similar but I don't imagine that's required for every use. For example, this currently requires some complicated message passing to share the wallet across threads

**Comment by notmandatory** [comment]
This issue will be address as part of the `bdk_core` work, if you want to get a preview take a look at [LLFourn/bdk_core_staging](https://github.com/LLFourn/bdk_core_staging). Also checkout blog posts:

[bdk_core: a new architecture for the Bitcoin Dev Kit](https://bitcoindevkit.org/blog/bdk-core-pt1/)
[The Road to BDK 1.0](https://bitcoindevkit.org/blog/road-to-bdk-1/)

Getting this into BDK will be the teams main focus this year, with the first steps being to start migrating the code from `bdk_core_staging` into the `master` bdk branch and adding lots of testing and updating docs.

**Comment by LLFourn** [comment]
Indeed. We've put a lot of work into this to make the `Wallet` not only threadsafe (`Send` + `Sync`) but also to make the higher level operations thread safe in the sense that operations on different threads don't conflict with each other (e.g. two threads creating transactions right after each other won't use the same change address).

**Comment by notmandatory** [comment]
I added this to the 1.0.0-alpha milestone as a reminder to confirm `Wallet` is shareable now across threads.
