### ISSUE TITLE
Provide built-in UTXO labeling for privacy

### ISSUE THREAD

**Issue by moneyball** [bitcoindevkit/bdk#87]
I suggest adding this to the roadmap on the website.

Inspired by this tweet https://twitter.com/matt_odell/status/1286659125322162176?s=19

"All wallets should have the option to use advanced coin control with labeling."

The BDK can build this and make it easy-to-use / default for any wallet based on BDK.

Another contributor suggested this as inspiration too: https://twitter.com/SifirApps/status/1269970305977585665

**Comment by afilini** [comment]
See my comment here on this topic: https://github.com/bitcoindevkit/bdk/issues/98#issuecomment-697228850

TL;DR is: we should try to give developers full control on how a transaction is built, but I don't think storing labels in our database is the right way of doing it.

**Comment by moneyball** [comment]
Thanks @afilini you make a good case. I'll close this.
