### ISSUE TITLE
Move hardware signer into its own crate

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#872]
It has its own very bespoke python runtime dependency and needs hardware to test (if I understand correctly). It doesn't need to be in the main `bdk` crate and I think it's desirable not to have non cargo dependencies for tests in the main `bdk` crate.

**Comment by danielabrozzoni** [comment]
Just to clarify, it would be moved to the same bdk workspace but in a different crate under `crates`, right? And I suppose there wouldn't be any feature inside of bdk for enabling it, but the people interested can just import bdk_hardware_signer themselves
