### ISSUE TITLE
Implement EsploraExt for esplora_client::AsyncClient

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#880]
**Describe the enhancement**  
https://github.com/bitcoindevkit/bdk/blob/97631328ff0dcfc9b72637cb0d6106dd3cb69e2e/crates/esplora/src/lib.rs#L309-L318
**Use case**  
Using bdk_esplora in wasm

**Comment by evanlinjin** [comment]
This is done in #885 which is merged into #793. Essentially, we now have `EsploraAsyncExt`.
