### ISSUE TITLE
Eclipse attack protection

### ISSUE THREAD

**Issue by remyers** [bitcoindevkit/bdk#89]
Generally need to think about how to prevent eclipse attacks for light clients that sync block headers from peers. Some ideas of strategies that can be borrowed from Bitcoin Core:

- general core heuristics: feeler connections, new/tried nodes tables, test-before-evict, etc.
- using ASMAP table information (https://bitcoincore.reviews/16702.html)
- reverse header lookup strategies and banning peers that give bad headers

**Comment by notmandatory** [comment]
This is primarily relevant to compact block filters and covered by #81.
