### ISSUE TITLE
Changesets should commit to previous changesets to avoid applying out of order

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#900]
**Describe the enhancement**

Now we have persistent storage we want to make sure that we apply changesets in order. One way to ensure this is that each changeset commits to the previous one. This can be checked by the persistent storage backend before applying it.

**Additional context**

I'm not 100% sure if this will be useful due to the #895 going forward. Leaving this here for now.

Old ticket: https://github.com/LLFourn/bdk_core_staging/issues/70

**Comment by evanlinjin** [comment]
The alternative way to do this is to stage changesets inside the objects themselves and commit them when appropriate to return the changeset which can be persisted (I guess we are already doing this for `bdk::Wallet`).

---

**A more detailed description of the issue (copied from https://github.com/LLFourn/bdk_core_staging/issues/161):**

Non-monotone changes (i.e. SparseChain changesets) must be generated and applied in order. If in between generating a changeset and applying it you apply another changeset that changeset must be thrown away. This is especially likely to happen if you need to do some IO after generating a changeset before you apply it and so you drop your mutex lock on the chain allowing another thread to make modifications while you wait for the result of your IO.

We current have baked in this mistake into our electrum example and the idea the "inflate_changeset" API on chaingraph. There we first generate a sparse chain changeset, we do some IO to get the full transactions (and drop the lock), and then inflate the changeset and apply it. What if another thread makes contradictory changes to the blockchain during this time i.e. there is a new block and the blocks and transactions have moved position since then? It breaks. This particular approach can be changed by instead of keeping a changeset over the IO boundry we inflate to a full ChainGraph and apply that -- this will enforce consistency.

**Comment by LLFourn** [comment]
Yes I don't think that this ticket should be done. Instead we should make `SparseChain` changesets monotone. #895 is a prerequisite for this.
