### ISSUE TITLE
`TxGraph` should disallow coinbase transactions at an unconfirmed position. 

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#901]
Because this is impossible.

Note that this should be implemented as part of #895 (or after it is completed).

Old ticket: https://github.com/LLFourn/bdk_core_staging/issues/125

**Comment by LLFourn** [comment]
Indeed if #895 if we add a "position" that is "last seen in the mempool" we could not not allow coinbases to be at this position.

**Comment by danielabrozzoni** [comment]
I think this is a duplicate of #1144, closing
