### ISSUE TITLE
Make outputs of CLI examples nice.

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#905]
The CLI output is a bit messy and this makes it difficult to read.

I suggest putting everything into tables and to reduce the amount of data in the `list` commands and to add additional commands to see more details about a particular item.

We can use a dependency such as https://docs.rs/tabled/latest/tabled/ to achieve this.

**Comment by notmandatory** [comment]
This is a good idea, but users should also keep the option to get the outputs as JSON as they are now to make it easier to parse the outputs with something like `jq`, which we use in some of the tutorials.

**Comment by evanlinjin** [comment]
> This is a good idea, but users should also keep the option to get the outputs as JSON as they are now to make it easier to parse the outputs with something like `jq`, which we use in some of the tutorials.

That's a good point. Originally, the outputs were just from `println!` and not proper JSON so #909 is objectively better. However, I think having the option for different output formats is the way to go.
