### ISSUE TITLE
Esplora may return conflicting transactions which should be tiebroken by feerate

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#907]
In general when inserting txs from esplora we should insert where unconfirmed conflicts are resolved by choosing the one with the higher feerate. This is because it may return a txid that has been fully evicted from the mempool. This is probably a feature where you can see a tx that has been rbf'd.

Original ticket: https://github.com/LLFourn/bdk_core_staging/issues/128

**Comment by LLFourn** [comment]
Doing #895 makes this issue redundant because whatever tools you build to generate a UTXO set including the unconfirmed transactions will force you to choose which transaction to use.
