### ISSUE TITLE
Fast indexing of UTXOs

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#908]
Right now our APIs allow you to find unspent outputs by iterating over all outputs and checking if they're spent. This is fine for most applications but for users with hundreds of thousands of historical txos doing all this work just to get the balance is a bit much. How can we do better?

Things that I imagine would be useful:

* What utxos are unspent
* What utxos are only spent by unconfirmed transactions
* What utxos that were unspent at a certain height

---

Original ticket: https://github.com/LLFourn/bdk_core_staging/issues/127

**Comment by LLFourn** [comment]
So I think this issue is premature having studied the problem a bit more. Making generating the utxo set faster is certainly something that could be done but let's not preempt this.
