### ISSUE TITLE
`rust-bitcoin` 0.30.0 upgrade may be annoying

### ISSUE THREAD

**Issue by tcharding** [bitcoindevkit/bdk#916]
Hi,

We just released v0.30.0 of `rust-bitcoin`, assuming you guys are going to upgrade, can I ask a favour please. If the upgrade is painful can you please give me feedback. There is a fair bit of churn going on with crate smashing and I'd like to make it as painless as possible for downstream. I don't personally work on any code that uses `rust-bitcoin` so I have a tendency to get tunnel vision.

If its super painful, just prod me and I can lend a hand.

Thanks

**Comment by notmandatory** [comment]
Thanks, we'll also need rust-bitcoin/rust-miniscript#527 to be released, but we can still start getting a bdk PR ready.

**Comment by tcharding** [comment]
Oh of course, I probably should help out there first huh :)

**Comment by notmandatory** [comment]
Reopening this issue since @danielabrozzoni is working on it in #1023.

**Comment by nondiremanuel** [comment]
@notmandatory shall we close this issue? I saw that #1023 was merged

**Comment by notmandatory** [comment]
Yes! fixed by #1023.
