### ISSUE TITLE
Kill TransactionDetails

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#922]
Kill TransactionDetails, get details of txs via methods from Wallet instead. Ensure rich data we have from `bdk_chain` can be observed from `Wallet`.

**Comment by evanlinjin** [comment]
This will most likely conflict with the work done for #895, please only start after PR #926 is complete!

**Comment by LLFourn** [comment]
Two places left where `TransactionDetails` is being used:

1. `get_tx` should just return a `Option<&Transaction>` or potentially a `TxNode` from `TxGraph`.
2. as a return value from creating a transaction.

removing (1) is higher priority. You could even keep something like it for (2) so you can return the fee/feerate etc. Changing what gets returned here depends on what happens with transaction building.
