### ISSUE TITLE
`ChainGraph` no longer uses `Cow` and docs need update

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#935]
(Doesn't have to be in this PR, but the docs for this method need to be updated, as ChainGraph doesn't contain a Cow anymore)

_Originally posted by @danielabrozzoni in https://github.com/bitcoindevkit/bdk/pull/926#discussion_r1154661131_

**Comment by notmandatory** [comment]
I can't find the docs that need to be fixed for this so must have been fixed. Closing.
