### ISSUE TITLE
Create random mnemonic codes and extended private/public keys

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#95]
Generate new random [BIP-39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) mnemonic codes. Allow 12, 18, or 24 word codes. 

Create [BIP-32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) extended private keys (xprv/tprv) from BIP-39 mnemonic codes OR from a randomly generated seed. 

Create extended public keys (xpub/tpub) from corresponding extended private keys.

**Comment by notmandatory** [comment]
This will probably be covered in https://github.com/bitcoindevkit/bdk/pull/92 or a related PR.

**Comment by afilini** [comment]
This was fixed by #92, it added the `GeneratableKey` trait (horrible name, we should change it) that can be implemented on types that can be generated.

It's always implemented for `bip32::ExtendedPrivKey` and it's also implemented for `bip39::Mnemonic` if the `keys-bip39` feature is enabled.
