### ISSUE TITLE
Resolve where to put Confirmation Height

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bdk#951]
**Describe the enhancement**  
ref: https://github.com/bitcoindevkit/bdk/pull/926#discussion_r1174347046

We need to find a way to put the transaction's confirmation height in `IndexedTxGraph` so we can calculate maturity correctly.

**Comment by LLFourn** [comment]
Put it into the anchor and implement `confirmation_height_upper_bound`. I think this is already possible in #926.

**Comment by danielabrozzoni** [comment]
Fixed in #963
