### ISSUE TITLE
Rename the `tx` field of additions as `txs`

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#954]
Nits: Maybe rename the `tx` field of additions as `txs`. Also, maybe rename the `txout` field as `txouts`.

_Originally posted by @vladimirfomene in https://github.com/bitcoindevkit/bdk/pull/926#discussion_r1172934653_

**Comment by Shourya742** [comment]
May I work on this issue? Can you please assign this to me?

**Comment by vladimirfomene** [comment]
@Shourya742 you can go ahead and work on it. You can create a PR on top of #926 that fixes that issue.

**Comment by vladimirfomene** [comment]
I'm closing this. @Shourya742 changes were added to #976
