### ISSUE TITLE
Descriptor checksum doesn't match bitcoind

### ISSUE THREAD

**Issue by bodymindarts** [bitcoindevkit/bdk#968]
**Describe the bug**  
Descriptors generated via bdk cannot be imported into bitcoind due to checksum mismatch.

**To Reproduce**  
I have documented a reproduce [here](https://github.com/bitcoindevkit/bdk/blob/8d3dd9ea54b263fc022680f1b0ab1e594e4c1db7/reproduce/README.md) as part of https://github.com/bitcoindevkit/bdk/pull/967

I try to import the descriptor from [here](https://github.com/bitcoindevkit/bdk/blob/c61995ca971e0d3461d7dc63aec8f1329c625d93/crates/bdk/src/descriptor/checksum.rs#L165) into a bitcoind running on regtest but it won't.

**Expected behavior**  
I would expect to be able to import the descriptor.

**Comment by notmandatory** [comment]
I was able to repro that if you add with ' or h bdk always converts first to ' and compute the checksum from that. To match with core's checksums you'll need to use ' in your descriptor string.

```rust
    #[test]
    fn test_hash_vs_tick() {

        let secp = Secp256k1::new();
        let network = Network::Regtest;

        let descriptor1 = "pkh(tpubD6NzVbkrYhZ4XHndKkuB8FifXm8r5FQHwrN6oZuWCz13qb93rtgKvD4PQsqC4HP4yhV3tA2fqr2RbY5mNXfM7RxXUoeABoDtsFUq2zJq6YK/44'/1'/0'/0/*)";
        let descriptor2 = "pkh(tpubD6NzVbkrYhZ4XHndKkuB8FifXm8r5FQHwrN6oZuWCz13qb93rtgKvD4PQsqC4HP4yhV3tA2fqr2RbY5mNXfM7RxXUoeABoDtsFUq2zJq6YK/44h/1h/0h/0/*)";

        let (descriptor1, _keymap) = descriptor1.into_wallet_descriptor(&secp, network).unwrap();
        let (descriptor2, _keymap) = descriptor2.into_wallet_descriptor(&secp, network).unwrap();

        //println!("descriptor1: {}", descriptor1);
        //println!("descriptor2: {}", descriptor2);
        assert_eq!("pkh(tpubD6NzVbkrYhZ4XHndKkuB8FifXm8r5FQHwrN6oZuWCz13qb93rtgKvD4PQsqC4HP4yhV3tA2fqr2RbY5mNXfM7RxXUoeABoDtsFUq2zJq6YK/44'/1'/0'/0/*)#lasegmfs", descriptor1.to_string());
        assert_eq!("pkh(tpubD6NzVbkrYhZ4XHndKkuB8FifXm8r5FQHwrN6oZuWCz13qb93rtgKvD4PQsqC4HP4yhV3tA2fqr2RbY5mNXfM7RxXUoeABoDtsFUq2zJq6YK/44'/1'/0'/0/*)#lasegmfs", descriptor2.to_string());
    }
```

**Comment by bodymindarts** [comment]
Yup confirmed - its just not intuitive when looking at the tests (as they use `h`).
