### ISSUE TITLE
while building bdk inside my project the rocksdb build failed

### ISSUE THREAD

**Issue by vincenzopalazzo** [bitcoindevkit/bdk#978]
I am using bdk in my project with the following key-value database enabled, but cargo while building stops with the following error https://gist.github.com/vincenzopalazzo/9ddd6dcc63d44d4a6aac6bcccad279b5

Any ideas? I guess this is not related to bdk but maybe someone knows the answer

**Comment by notmandatory** [comment]
Are you using the `compact_filters` feature? We're currently planning to move to the `nakamoto` CBF crate in future BDK 1.0 versions and will probably be deprecating, or at least removing rocksdb from our current `compact_filters` support. In the meantime it's not well supported. See also: #480

**Comment by vincenzopalazzo** [comment]
Yeah, in fact, I removed the `compact_filters` to be able to compile, and support nakamoto is excellent.

My application is based on nakamoto so I was planning to do a fork of bdk to support it.

But maybe we want to work together to support it in bdk, I am planning to help to maintain nakamto in the near future

**Comment by danielabrozzoni** [comment]
Closing as this is not bdk related, but some problem while compiling rocksdb, and after a while it seems that no one else experienced it :( Sorry!

**Comment by vincenzopalazzo** [comment]
>Closing as this is not bdk related, but some problem while compiling
rocksdb, and after a while it seems that no one else experienced it :(
Sorry!

Yeah I removed the rocksdb because did not build on arch linux, but this is
a rocksdb bug
