### ISSUE TITLE
Adding BIP47 support

### ISSUE THREAD

**Issue by Sosthene00** [bitcoindevkit/bdk#982]
I still think it would be useful for bdk to support bip47, and if the maintainers agree with that I'd like to open a new PR that will resume work already made in #574 (see it for use case, rationale, and additional context).

As for the debate around bip47, I think pretty much everything have already been said, and I don't intend to argue over it again here.

I tried to rebase and rework the previous PR over 1.0.0-alpha release, but it's actually not that trivial. Besides I worry that there's some of the WIP that could impact an eventual bip47 support.

**Comment by notmandatory** [comment]
I think this would probably better to tackle as a separate crate that works with the new bdk 1.0 APIs after they are settled.

**Comment by nondiremanuel** [comment]
> I think this would probably better to tackle as a separate crate that works with the new bdk 1.0 APIs after they are settled.

Should I assign it to BDK 1.0 project then?

**Comment by notmandatory** [comment]
> Should I assign it to BDK 1.0 project then?

No, in this case since it should be a project outside of the bitcoindevkit project org it won't be on any of our project boards. In the future if any help/support discussion issues come up those may go to the 1.0 project board.

**Comment by Sosthene00** [comment]
> I think this would probably better to tackle as a separate crate that works with the new bdk 1.0 APIs after they are settled.

Thanks for the feedback after spending a few hours fiddling with bdk 1.0 I actually agree. I will think it again as a separate crate and wait for the bdk API to stabilize. 

Closing the issue.
