### ISSUE TITLE
Fix `base64` dependency error

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#986]
This looks like a new error that just popped up in the `master` and `release/0.28` branches.

`error: package `base64 v0.21.1` cannot be built because it requires rustc 1.60.0 or newer, while the currently active rustc version is 1.57.0`

see: https://github.com/bitcoindevkit/bdk/actions/runs/5018045314/jobs/9067260985?pr=957

**Comment by Sosthene00** [comment]
It seems that base64 updated it's MSRV 2 days ago: https://github.com/marshallpierce/rust-base64/pull/238

**Comment by notmandatory** [comment]
Thanks @Sosthene00 , @danielabrozzoni is working on a fix for the `master` branch to pin the version:
`base64 = "=0.21.0"`. I'll do a corresponding PR for the `release/0.28` branch.

**Comment by notmandatory** [comment]
Root cause is that `rust-base64` project changed their MSRV in patch release 0.21.1 from `1.57.0` to `1.60.0`.  I wish projects wouldn't do that but it happens.
