### ISSUE TITLE
`bdk::Wallet` should have context-specific error types

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#994]
I agree that the errors aren't great.

However, I disagree about having a single error enum with a large number of variants. I think we should fix errors in one go with a separate PR, otherwise it's duplicate work.

_Originally posted by @evanlinjin in https://github.com/bitcoindevkit/bdk/pull/976#discussion_r1204823980_

**Comment by LLFourn** [comment]
I think the `bdk::Error` enum should go but I don't know when that can happen. I'd probably put it last on the list of things needing to be done. All new fallible functions should have their own error type.

**Comment by notmandatory** [comment]
Moving this to milestone alpha.4 where we're going to focus on Wallet APIs.

**Comment by nondiremanuel** [comment]
As per what we said during the last Lib Team Call, the fix for this should be into #1028 PR
